/**
 * @file src/cli/init-wizard/generate.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description .env / .json / .ini config-file generators for the `aimeat init` wizard. Extracted from src/cli/init-wizard.ts to satisfy max-file-lines.
 * @version-history
 *   v1.1.0 — 2026-08-21 — Add the "Security (encryption at rest)" .env section for the two
 *     per-instance secrets (AIMEAT_TOTP_ENCRYPTION_KEY, AIMEAT_KEY_PASSPHRASE) the wizard now
 *     auto-generates, each with a never-change-on-a-live-instance warning.
 *   v1.0.0 — 2026-07-13 — Extracted from src/cli/init-wizard.ts (max-file-lines)
 */

import ini from 'ini';
import { ENV_TO_DOT_PATH } from '../../services/config-schema.js';

// ── .env generation ─────────────────────────────────────────────────

export function generateEnvContent(settings: Record<string, string>): string {
  const lines: string[] = [
    '# AIMEAT Node Configuration',
    '# Generated by: aimeat init',
    '',
  ];

  const sections: Array<{ title: string; vars: Array<{ key: string; comment?: string }> }> = [
    {
      title: 'Node Identity',
      vars: [
        { key: 'AIMEAT_NODE_ID' },
        { key: 'AIMEAT_PORT' },
        { key: 'AIMEAT_NODE_TYPE' },
        { key: 'AIMEAT_BASE_URL', comment: 'Public URL (default: http://localhost:$PORT)' },
      ],
    },
    {
      title: 'Storage Backend',
      vars: [
        { key: 'AIMEAT_STORAGE', comment: 'Storage backend: memory (default), sqlite (file-based), postgres-kysely (production)' },
        { key: 'AIMEAT_SQLITE_PATH', comment: 'SQLite database file path (when AIMEAT_STORAGE=sqlite)' },
        { key: 'DATABASE_URL', comment: 'PostgreSQL connection URL (when AIMEAT_STORAGE=postgres-kysely)' },
      ],
    },
    {
      title: 'Operator / Admin',
      vars: [
        { key: 'AIMEAT_ADMIN_PASSWORD', comment: 'Auto-generated on startup if not set' },
      ],
    },
    {
      title: 'Security (encryption at rest)',
      vars: [
        { key: 'AIMEAT_TOTP_ENCRYPTION_KEY', comment: 'Per-instance AES-256-GCM key for stored 2FA secrets (64 hex chars). Auto-generated once by `aimeat init`. Never change it on a live instance — a new key cannot decrypt already-stored TOTP secrets.' },
        { key: 'AIMEAT_KEY_PASSPHRASE', comment: 'Per-instance passphrase that encrypts the node identity key on disk. Auto-generated once by `aimeat init`. Never change it on a live instance — a new passphrase cannot decrypt the existing node key.' },
      ],
    },
    {
      title: 'Modes',
      vars: [
        { key: 'AIMEAT_DEV_MODE' },
        { key: 'AIMEAT_ANONYMOUS' },
      ],
    },
    {
      title: 'Auth & Tokens',
      vars: [
        { key: 'AIMEAT_JWT_TTL', comment: 'Legacy / agent JWT lifetime in seconds (default: 1h)' },
        { key: 'AIMEAT_ACCESS_TTL', comment: 'Owner access-token lifetime in seconds (default: 15min)' },
        { key: 'AIMEAT_REFRESH_IDLE_DAYS', comment: 'Owner refresh-cookie idle window in days (default: 30)' },
        { key: 'AIMEAT_REFRESH_ABSOLUTE_DAYS', comment: 'Owner refresh-cookie hard cap in days (default: 90)' },
        { key: 'AIMEAT_REFRESH_GRACE_MS', comment: 'Refresh-rotation grace window in ms (default: 60s)' },
      ],
    },
    {
      title: 'Morsel Economy',
      vars: [
        { key: 'AIMEAT_WELCOME_BONUS' },
        { key: 'AIMEAT_DAILY_ALLOWANCE' },
        { key: 'AIMEAT_DAILY_ALLOWANCE_CAP' },
        { key: 'AIMEAT_BURN_RATE' },
        { key: 'AIMEAT_MAX_OPERATOR_MINT_PER_DAY' },
        { key: 'AIMEAT_BOARD_POST_BASE_COST' },
        { key: 'AIMEAT_BOARD_POST_COST_PER_KB' },
      ],
    },
    {
      title: 'Features',
      vars: [
        { key: 'AIMEAT_EXTENDED_FEATURES' },
      ],
    },
    {
      title: 'Quotas',
      vars: [
        { key: 'AIMEAT_MEMORY_QUOTA_MB' },
        { key: 'AIMEAT_MEMORY_MAX_VALUE_SIZE_KB', comment: 'Max size of a single memory value (KB)' },
        { key: 'AIMEAT_MEMORY_MAX_KEYS', comment: 'Max memory keys per agent' },
        { key: 'AIMEAT_STORAGE_QUOTA_MB' },
        { key: 'AIMEAT_STORAGE_MAX_FILE_SIZE_MB', comment: 'Max single file upload size (MB)' },
        { key: 'AIMEAT_MAX_ACTIONS_PER_AGENT', comment: 'Max action definitions per agent' },
        { key: 'AIMEAT_APP_MAX_SIZE_MB', comment: 'Max app file size (MB)' },
        { key: 'AIMEAT_AGENT_PORTING_FEE', comment: 'Morsels charged for agent porting' },
      ],
    },
    {
      title: 'Federation',
      vars: [
        { key: 'AIMEAT_FEDERATION_ROLE', comment: 'operator = genesis directory | contributor = join genesis | standalone = independent' },
        { key: 'AIMEAT_GENESIS_URL', comment: 'Genesis node URL (for contributor role)' },
        { key: 'AIMEAT_MAX_RELAY_HOPS' },
        { key: 'AIMEAT_CROSS_FEDERATION_ENABLED', comment: 'Enable cross-federation genesis peering (connects independent nodes/clusters)' },
        { key: 'AIMEAT_MAX_GENESIS_PEERS', comment: 'Max genesis peer connections (1-100)' },
        { key: 'AIMEAT_GENESIS_SYNC_INTERVAL_HOURS', comment: 'Hours between catalogue sync with genesis peers (1-168)' },
      ],
    },
    {
      title: 'IndexNow (Bing/Yandex search indexing)',
      vars: [
        { key: 'AIMEAT_INDEXNOW_KEY', comment: 'Hex key for IndexNow. Generate: openssl rand -hex 16. After setting, run: pnpm indexnow' },
      ],
    },
    {
      title: 'Node Portal (Site)',
      vars: [
        { key: 'AIMEAT_SITE_ENABLED', comment: 'Enable custom HTML template portal at GET /' },
        { key: 'AIMEAT_SITE_MAX_TEMPLATE_SIZE_KB', comment: 'Max template size in KB' },
        { key: 'AIMEAT_SITE_CACHE_TTL_SECONDS', comment: 'Resolved template cache TTL (0 = no cache)' },
      ],
    },
    {
      title: 'Push Notifications (REQ-007)',
      vars: [
        { key: 'AIMEAT_PUSH_ENABLED' },
        { key: 'AIMEAT_VAPID_PUBLIC_KEY', comment: 'Generate: npx web-push generate-vapid-keys' },
        { key: 'AIMEAT_VAPID_PRIVATE_KEY' },
        { key: 'AIMEAT_VAPID_SUBJECT' },
        { key: 'AIMEAT_PUSH_NOTIFY_TYPES', comment: 'Comma-separated message types that trigger push' },
        { key: 'AIMEAT_PUSH_COOLDOWN_MIN' },
        { key: 'AIMEAT_PUSH_MAX_SUBSCRIPTIONS_PER_NODE' },
        { key: 'AIMEAT_PUSH_MAX_FAILURES' },
        { key: 'AIMEAT_EMAIL_RATE_LIMIT_MIN' },
      ],
    },
    {
      title: 'Email / SMTP',
      vars: [
        { key: 'AIMEAT_SMTP_HOST' },
        { key: 'AIMEAT_SMTP_PORT' },
        { key: 'AIMEAT_SMTP_USER' },
        { key: 'AIMEAT_SMTP_PASS' },
        { key: 'AIMEAT_SMTP_FROM' },
        { key: 'AIMEAT_SMTP_SECURE' },
      ],
    },
    {
      title: 'Metrics & Observability (REQ-008)',
      vars: [
        { key: 'AIMEAT_METRICS_ENABLED', comment: 'Enable Prometheus metrics at GET /v1/metrics' },
        { key: 'AIMEAT_METRICS_ACCESS', comment: 'public | authenticated | operator' },
      ],
    },
    {
      title: 'CORS',
      vars: [
        { key: 'AIMEAT_CORS_ALLOWED_ORIGINS', comment: 'Comma-separated origins, or * for all' },
      ],
    },
    {
      title: 'TOTP / 2FA',
      vars: [
        { key: 'AIMEAT_TOTP_ENABLED', comment: 'Enable TOTP two-factor authentication' },
        { key: 'AIMEAT_TOTP_ISSUER', comment: 'Issuer name shown in authenticator apps' },
        { key: 'AIMEAT_TOTP_MAX_FAILED', comment: 'Max failed attempts before lockout' },
        { key: 'AIMEAT_TOTP_LOCKOUT_SECONDS', comment: 'Lockout duration (seconds)' },
      ],
    },
    {
      title: 'AI Matching',
      vars: [
        { key: 'AIMEAT_MATCHING_ENABLED', comment: 'Enable AI-powered interest matching' },
        { key: 'AIMEAT_MATCH_INTERVAL_HOURS', comment: 'Hours between matching runs' },
        { key: 'AIMEAT_MATCH_THRESHOLD', comment: 'Min similarity score (0-1)' },
        { key: 'AIMEAT_MATCH_MAX_SUGGESTIONS', comment: 'Max match suggestions per user' },
        { key: 'AIMEAT_MATCH_MAX_DISTANCE_KM', comment: 'Max distance for location matching (km)' },
      ],
    },
    {
      title: 'Marketplace',
      vars: [
        { key: 'AIMEAT_MARKETPLACE_ENABLED', comment: 'Enable marketplace features' },
        { key: 'AIMEAT_MARKETPLACE_LISTING_FEE', comment: 'Morsels charged to list an item' },
        { key: 'AIMEAT_MARKETPLACE_TX_FEE_PERCENT', comment: 'Transaction fee percentage' },
        { key: 'AIMEAT_MARKETPLACE_ESCROW', comment: 'Enable escrow for transactions' },
      ],
    },
    {
      title: 'Realtime P2P',
      vars: [
        { key: 'AIMEAT_REALTIME_ENABLED', comment: 'Enable realtime P2P signaling (WebRTC)' },
        { key: 'AIMEAT_REALTIME_MAX_ROOMS', comment: 'Max concurrent rooms' },
        { key: 'AIMEAT_REALTIME_MAX_PEERS_PER_ROOM', comment: 'Max peers per room' },
      ],
    },
    {
      title: 'Node Extensions (Sandboxed)',
      vars: [
        { key: 'AIMEAT_EXTENSIONS_ENABLED', comment: 'Enable sandboxed extension system' },
        { key: 'AIMEAT_EXT_MAX_MEMORY_MB', comment: 'Max memory per extension sandbox (MB)' },
        { key: 'AIMEAT_EXT_TIMEOUT_MS', comment: 'Extension execution timeout (ms)' },
      ],
    },
    {
      title: 'App Origin Isolation (H-2)',
      vars: [
        { key: 'AIMEAT_APP_ORIGIN_ENABLED', comment: 'Serve user apps from *.apps.<domain> to isolate them from your session. Requires DNS + wildcard TLS (see docs/internal/app-origin-deployment.md)' },
        { key: 'AIMEAT_APP_HOST', comment: 'App origin host, e.g. apps.example.com (required when AIMEAT_APP_ORIGIN_ENABLED=true)' },
        { key: 'AIMEAT_PORTFOLIO_ORIGIN_ENABLED', comment: 'Serve published portfolios standalone at <username>.portfolio.<domain>. Requires DNS + wildcard TLS' },
        { key: 'AIMEAT_PORTFOLIO_HOST', comment: 'Portfolio origin host, e.g. portfolio.example.com (required when AIMEAT_PORTFOLIO_ORIGIN_ENABLED=true)' },
      ],
    },
  ];

  for (const section of sections) {
    const hasValues = section.vars.some(v => v.key in settings);
    if (!hasValues) continue;

    lines.push(`# ${'─'.repeat(2)} ${section.title} ${'─'.repeat(Math.max(0, 55 - section.title.length))}`);

    for (const v of section.vars) {
      if (v.comment) lines.push(`# ${v.comment}`);
      if (v.key in settings) {
        const val = settings[v.key];
        const isNumOrBool = /^(\d+(\.\d+)?|true|false)$/.test(val);
        lines.push(`${v.key}=${isNumOrBool ? val : `"${val}"`}`);
      } else {
        lines.push(`# ${v.key}=`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function generateJsonContent(settings: Record<string, string>): string {
  const keyMap: Record<string, string> = {
    AIMEAT_NODE_ID: 'nodeId',
    AIMEAT_PORT: 'port',
    AIMEAT_NODE_TYPE: 'nodeType',
    AIMEAT_BASE_URL: 'baseUrl',
    AIMEAT_STORAGE: 'storageProvider',
    AIMEAT_SQLITE_PATH: 'sqlitePath',
    DATABASE_URL: 'db',
    AIMEAT_ADMIN_PASSWORD: 'adminPassword',
    AIMEAT_DEV_MODE: 'devMode',
    AIMEAT_ANONYMOUS: 'anonymousMode',
    AIMEAT_JWT_TTL: 'jwtTtlSeconds',
    AIMEAT_ACCESS_TTL: 'accessTtlSeconds',
    AIMEAT_REFRESH_IDLE_DAYS: 'refreshIdleDays',
    AIMEAT_REFRESH_ABSOLUTE_DAYS: 'refreshAbsoluteDays',
    AIMEAT_REFRESH_GRACE_MS: 'refreshGraceMs',
    AIMEAT_WELCOME_BONUS: 'welcomeBonus',
    AIMEAT_DAILY_ALLOWANCE: 'dailyAllowance',
    AIMEAT_DAILY_ALLOWANCE_CAP: 'dailyAllowanceCap',
    AIMEAT_BURN_RATE: 'burnRate',
    AIMEAT_MAX_OPERATOR_MINT_PER_DAY: 'maxOperatorMintPerDay',
    AIMEAT_BOARD_POST_BASE_COST: 'boardPostBaseCost',
    AIMEAT_BOARD_POST_COST_PER_KB: 'boardPostCostPerKb',
    AIMEAT_EXTENDED_FEATURES: 'extendedFeaturesEnabled',
    AIMEAT_MEMORY_QUOTA_MB: 'memoryQuotaMb',
    AIMEAT_MEMORY_MAX_VALUE_SIZE_KB: 'memoryMaxValueSizeKb',
    AIMEAT_MEMORY_MAX_KEYS: 'memoryMaxKeysPerAgent',
    AIMEAT_STORAGE_QUOTA_MB: 'storageQuotaMb',
    AIMEAT_STORAGE_MAX_FILE_SIZE_MB: 'storageMaxFileSizeMb',
    AIMEAT_MAX_ACTIONS_PER_AGENT: 'maxActionsPerAgent',
    AIMEAT_APP_MAX_SIZE_MB: 'appMaxSizeMb',
    AIMEAT_AGENT_PORTING_FEE: 'agentPortingFeeMorsels',
    AIMEAT_MAX_RELAY_HOPS: 'maxRelayHops',
    AIMEAT_FEDERATION_ROLE: 'federationRole',
    AIMEAT_GENESIS_URL: 'genesisUrl',
    AIMEAT_INDEXNOW_KEY: 'indexNowKey',
    AIMEAT_SITE_ENABLED: 'siteEnabled',
    AIMEAT_SITE_MAX_TEMPLATE_SIZE_KB: 'siteMaxTemplateSizeKb',
    AIMEAT_SITE_CACHE_TTL_SECONDS: 'siteCacheTtlSeconds',
  };

  const cfg: Record<string, unknown> = {};
  for (const [envKey, val] of Object.entries(settings)) {
    const jsonKey = keyMap[envKey] ?? envKey;
    if (/^\d+$/.test(val)) cfg[jsonKey] = parseInt(val, 10);
    else if (/^\d+\.\d+$/.test(val)) cfg[jsonKey] = parseFloat(val);
    else if (val === 'true') cfg[jsonKey] = true;
    else if (val === 'false') cfg[jsonKey] = false;
    else cfg[jsonKey] = val;
  }

  return JSON.stringify(cfg, null, 2) + '\n';
}

export function generateIniContent(settings: Record<string, string>): string {
  // Build INI structure using dot-path sections from ENV_TO_DOT_PATH
  const sections: Record<string, Record<string, string>> = {};
  for (const [envKey, val] of Object.entries(settings)) {
    const dotPath = ENV_TO_DOT_PATH[envKey];
    if (!dotPath) continue;
    const parts = dotPath.split('.');
    const section = parts.length > 1 ? parts.slice(0, -1).join('.') : 'node';
    const key = parts[parts.length - 1];
    if (!sections[section]) sections[section] = {};
    sections[section][key] = val;
  }
  // Add a comment header
  const header = '; AIMEAT Node Configuration (INI format)\n; Generated by aimeat init\n\n';
  return header + ini.stringify(sections);
}
