/**
 * @file src/services/ui-library/entries-operator.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Catalogue entries for the parts the admin pages and the small inner pages brought when
 *   they moved onto components: the operator's frame and menu, the readings of a status page, and
 *   the special views only those pages have. The purpose half only; facts.generated.ts carries what
 *   the files say.
 * @structure OPERATOR_ENTRIES
 * @usage import { OPERATOR_ENTRIES } from './entries-operator.js';
 * @version-history
 *   v1.1.0 — 2026-09-27 — The seventeen new parts of the admin pages and the inner pages: readings,
 *     operator-menu, operator-frame, ask-page, solo-window, quick-find, pick-field, status-page-preview,
 *     search-preview, save-bar, move-buttons, day-chart, trend-line, count-bars, print-page,
 *     settings-index and shots (the catalogue pass, operator family).
 *   v1.0.0 — 2026-09-27 — Initial (the admin dashboard on components, the catalogue pass).
 */
import type { UiEntryWritten } from './types.js';

export const OPERATOR_ENTRIES: UiEntryWritten[] = [
    {
        id: 'readings', name: 'Readings', kind: 'component', status: 'active',
        summary: 'The rows of a status page and the verdict that opens it. A reading is one row between hairlines: what is measured in bold with a grey line on why it matters under it, its state mark in the middle, and its value on the right in grey typewriter letters. The verdict is a column with the status word large in the poster face (coral when it is bad, the warning colour when it needs watching, grey when it is quiet), one line on what needs a look and a machine stamp under it, with the readings beside it.',
        module: '/components/Readings.js', sheet: '/css/components/readings.css',
        data: {
            shape: 'Reading({ name, why, mark, value, end, last, children }) · Readings({ rows }) · Verdict({ label, word, tone, line, stamp, doors, children })',
            fields: {
                name: 'the measured thing, in bold',
                why: 'the grey line under the name: why the reading matters',
                mark: 'the state mark (a Mark) in the middle column; passing the key at all gives the row that column',
                value: 'the reading on the right, in grey typewriter letters that may break anywhere',
                end: 'controls or words on the right in place of the value (an action, a switch), not typewriter',
                last: 'the last row of its section: no hairline under it',
                children: 'Reading: more content in the left cell after the name and the line. Verdict: the column beside it (the readings)',
                rows: 'Readings: the rows as data, [{ key, name, why, mark, value, end, last }]; a falsy row is left out',
                label: 'Verdict: the row label over the word',
                word: 'Verdict: the status word',
                tone: 'Verdict: danger | watch | quiet, the colour of the word',
                line: 'Verdict: the one line under the word',
                stamp: 'Verdict: the mono reading under the line (uptime, storage)',
                doors: 'Verdict: actions under the column',
            },
        },
        useFor: ['An operator page that reports how things stand: one row per measured thing, and the one-word verdict at the top of the overview.'],
        variants: [
            { name: 'three columns', prop: 'mark', when: 'a reading with a state mark between the name and the value' },
            { name: 'two columns', class: 'reading--two', prop: 'no mark', when: 'a reading with only a name and a value (or controls at the end)' },
            { name: 'last', class: 'reading--last', prop: 'last', when: 'the last reading of a section, where the section\'s own rule follows' },
            { name: 'danger', class: 'verdict-word--danger', prop: 'tone="danger"', when: 'the verdict says something is wrong now' },
            { name: 'watch', class: 'verdict-word--watch', prop: 'tone="watch"', when: 'the verdict says something needs watching' },
            { name: 'quiet', class: 'verdict-word--quiet', prop: 'tone="quiet"', when: 'the verdict has nothing to report' },
        ],
        example: { word: 'healthy', line: 'No alerts.', stamp: 'Uptime: 4d 2h · Storage: postgres-kysely', rows: [{ key: 'burn', name: 'Burn to mint ratio', why: 'How many morsels are used for each one made.', mark: 'OK', value: '0.42' }] },
        note: 'Replaced the operator pages\' metric row on main (shared.js Row and about fifteen hand-written copies: .adm-mrow, .adm-mrow--two, .adm-mrow--last, .adm-why, .adm-mval) and the overview\'s status column (.adm-ov-grid, .adm-ov-status, .adm-alert-line, .adm-ov-up), all in views/admin.css and drawn by about 27 admin pages. On a phone the name takes the left and the mark and the value stack on the right; the verdict stands over its readings under 860px.',
    },
    {
        id: 'operator-menu', name: 'OperatorMenu', kind: 'component', status: 'active',
        summary: 'The side menu of the admin pages: a dark ink ground in both modes, the heading "Operator menu" in small capitals, the node id in grey typewriter letters, the groups under a small capital word in the sun colour, each item in bold paper letters with its count in grey typewriter at the right, and the chosen item on the sun. On a phone the menu is not drawn, as on main.',
        module: '/components/OperatorMenu.js', sheet: '/css/components/operator-menu.css',
        data: {
            shape: 'OperatorMenu({ title, nodeId, groups, active, onPick, label })',
            fields: {
                title: 'the heading at the top ("Operator menu")',
                nodeId: 'the node\'s id under the heading',
                groups: '[{ key, title, items: [{ id, label, count }] }]; a count shows at the right when it is a number, 0 included',
                active: 'the chosen item\'s id; it sits on the sun and says aria-current',
                onPick: 'onPick(id): an item was chosen',
                label: 'the navigation\'s name for a screen reader (the title by default)',
            },
        },
        useFor: ['The left menu of the admin pages, the one place that tells at a glance that this is the operator\'s side.'],
        variants: [
            { name: 'chosen', class: 'operator-menu-item--active', prop: 'active', when: 'the item of the page that is open' },
        ],
        themeHooks: { selector: '.operator-menu', hooks: [
            { name: '--operator-menu-ground', kind: 'colour', default: '#1A1A2E', what: 'the menu\'s ground, the poster ink in both modes' },
            { name: '--operator-menu-ink', kind: 'colour', default: '#FAFAF8', what: 'the heading and the items, the poster paper' },
            { name: '--operator-menu-dim', kind: 'colour', default: '#9AA0B0', what: 'the node id and the counts' },
            { name: '--operator-menu-hover', kind: 'colour', default: 'rgba(250, 250, 248, 0.08)', what: 'an item under the pointer' },
        ] },
        example: { title: 'Operator menu', nodeId: 'aimeat-local-001-dev', active: 'overview', groups: [{ key: 'node', title: 'Node', items: [{ id: 'overview', label: 'Overview' }, { id: 'config', label: 'Configuration' }] }, { key: 'identity', title: 'Identity', items: [{ id: 'owners', label: 'Owners', count: 3 }, { id: 'agents', label: 'Agents', count: 0 }] }] },
        note: 'Keeps main\'s admin menu look exactly (Jouni, 2026-09-27: the dark menu is how the operator\'s side is known), moved out of views/admin.js and views/admin.css (.adm-sidebar, .adm-nav-group, .adm-nav-item, .cnt, .node-id) with every value unchanged. It has the heading "Operator menu" (t(\'dashboard.operatorMenu\')), which is new, at Jouni\'s request. Its ground and ink are pinned so the dark mode cannot flip them; a theme may set them through the hooks.',
    },
    {
        id: 'operator-frame', name: 'OperatorFrame', kind: 'component', status: 'active',
        summary: 'The frame of the admin pages: the operator menu on the left, and the page on the right under a bar that stays in sight, with the page\'s title in the poster face, the refresh as a small action link and the time of the last read in grey typewriter letters. The page inside gets the page kit with the operator\'s sizes (a 1.5rem section title, a section\'s number in mono coral). A visit that is not signed in, or not an operator\'s, gets one centred card under a heavy ink rule instead.',
        module: '/components/OperatorFrame.js', sheet: '/css/components/operator-frame.css',
        data: {
            shape: 'OperatorFrame({ menu, title, onRefresh, refreshing, refreshLabel, busyLabel, time, shut, children })',
            fields: {
                menu: 'the OperatorMenu',
                title: 'the page\'s title in the bar',
                onRefresh: 'reads everything again; without it the bar has no refresh',
                refreshing: 'it is reading: the refresh is off and says busyLabel',
                refreshLabel: 'the refresh\'s word',
                busyLabel: 'the refresh\'s word while it reads',
                time: 'when it was last read (a timestamp or a Date), drawn as the reader\'s clock',
                shut: '{ title, text, note }: the centred card in place of the menu and the page',
                children: 'the page',
            },
        },
        useFor: ['Every admin page: it carries the menu, the page\'s title and the way to read the data again.'],
        variants: [
            { name: 'open', prop: 'menu + children', when: 'an operator is signed in and a page is open' },
            { name: 'reading', prop: 'refreshing', when: 'the data is being read again' },
            { name: 'shut', class: 'operator-frame-shut', prop: 'shut', when: 'the visit is not signed in, or not an operator\'s' },
        ],
        example: { title: 'Overview', refreshLabel: 'Refresh', busyLabel: 'Loading…', time: 1790000000000 },
        note: 'Replaced views/admin.js\'s own frame and views/admin.css (.adm, .adm-main, .adm-topbar, .adm-page-title, .adm-refresh, .adm-time, .adm-login, .adm-card) under the component\'s own names; the refresh is the library\'s action link and the clock the time mark. The bar prints with a page that prints as a document (data-print-keep, see print-page). The frame is at least as tall as the window.',
    },
    {
        id: 'ask-page', name: 'AskPage', kind: 'component', status: 'active',
        summary: 'A page that asks the person one thing, in a narrow column in the middle of the window (it often opens as a small popup). The question stands in the Object box: who asks (a large picture or first letter, their bold name, their address in typewriter letters and a mark at the right), a tag over the question, the question as the headline, what the person needs to know, the ways to answer at the foot, and other ways in under a word such as "or". While there is nothing to ask yet, one quiet sentence stands in the box\'s place.',
        module: '/components/AskPage.js', sheet: '/css/components/ask-page.css',
        data: {
            shape: 'AskPage({ message, who, tag, title, doors, or, ways, children })',
            fields: {
                message: 'the quiet sentence shown while there is nothing to ask (loading, not found)',
                who: '{ name, meta, text, picture, label, mark }: who asks; picture an <img> or text one sign or first letter, meta the address line, mark at the right',
                tag: 'a mark over the headline',
                title: 'the question, as the page\'s headline',
                children: 'what the person needs to know before answering',
                doors: 'the ways to answer, at the right of the foot (under each other on a phone, the first one lowest)',
                or: 'the word over the other ways in',
                ways: 'other ways in, each on its own line',
            },
        },
        useFor: ['A consent or an invitation the person answers once: an app asking for access, an invitation to an organism.'],
        variants: [
            { name: 'asking', prop: 'who + title + doors', when: 'the question is ready to answer' },
            { name: 'other ways', prop: 'or + ways', when: 'the page offers other ways in under the answers' },
            { name: 'waiting', class: 'ask-page-message', prop: 'message', when: 'there is nothing to ask yet, or nothing to ask at all' },
        ],
        example: { title: 'Lumo Bakery wants to read your recipes', who: { name: 'Lumo Bakery', meta: 'lumo-bakery.apps.aimeat.io', text: 'L' } },
        note: 'Replaced the app-grant consent card (views/app-grant.js, .agr-*) and the invitation card (views/invite-accept.js, .inv-*), one component for both. The box is Box.js and the picture Avatar.js.',
    },
    {
        id: 'solo-window', name: 'SoloWindow', kind: 'component', status: 'active',
        summary: 'One thing popped out into a window of its own, so a person can set several side by side: the thing in a centred column up to 920px wide, or, while there is nothing to show, one quiet sentence that says why in the middle of the window.',
        module: '/components/SoloWindow.js', sheet: '/css/components/solo-window.css',
        data: {
            shape: 'SoloWindow({ message, children })',
            fields: {
                message: 'the sentence shown in the thing\'s place while there is nothing to show (sign in, loading, not found)',
                children: 'the thing: an agent\'s card, a document',
            },
        },
        useFor: ['A pop-out window of one agent or one document.'],
        variants: [
            { name: 'showing', prop: 'children', when: 'the thing is there' },
            { name: 'waiting', class: 'solo-window-message', prop: 'message', when: 'the thing is loading, not found, or needs a sign-in' },
        ],
        example: { message: 'Loading…' },
        note: 'Replaced the pop-out agent window (views/agent-solo.js, .pf-agd-solo) and the pop-out document window (views/doc-solo.js, .pj-doc-solo); the column is the document window\'s 920px (a unification).',
    },
    {
        id: 'quick-find', name: 'QuickFind', kind: 'component', status: 'active',
        summary: 'Find a place and jump to it: a search field, a grey line that says how the keys work, and the places found in groups under a row label, each place a row with its name, a grey line and a snippet, the chosen one lit. The field takes the focus when it appears, up and down move the choice, Enter takes it, and the pointer on a place chooses it.',
        module: '/components/QuickFind.js', sheet: '/css/components/quick-find.css',
        data: {
            shape: 'QuickFind({ value, onInput, placeholder, hint, groups, busy, busyLabel, emptyLabel, onPick })',
            fields: {
                value: 'what is typed', onInput: 'onInput(value, event) on every key', placeholder: 'the field\'s grey words',
                hint: 'the line under the field on how the keys work',
                groups: '[{ key, label, items: [{ key, mark, label, sub, snippet }] }]; a group with no items is not drawn',
                busy: 'it is searching: the loading line shows while nothing is found yet', busyLabel: 'the loading line\'s words',
                emptyLabel: 'the words when nothing was found (the page passes them only after a search)',
                onPick: 'onPick(item): the place was taken, with the item as the page gave it',
            },
        },
        useFor: ['The command palette: a keyboard way to any place in the site.'],
        variants: [
            { name: 'found', prop: 'groups', when: 'places were found, in their groups' },
            { name: 'searching', prop: 'busy', when: 'a search runs and nothing is found yet' },
            { name: 'nothing found', prop: 'emptyLabel', when: 'the search found nothing' },
        ],
        example: { value: 'ferr', hint: '↑ ↓ to move, Enter to open', groups: [{ key: 'orgs', label: 'Organisms', items: [{ key: 'nf', label: 'Nordic Ferries', sub: 'organism' }] }] },
        note: 'Replaced the command palette\'s list (views/command-palette.js, .cmdk*) with its keys and its choice. The field is SearchBar, a group\'s name the row label (Mark.js Label).',
    },
    {
        id: 'pick-field', name: 'PickField', kind: 'component', status: 'active',
        summary: 'A field that narrows a list as you type and picks one thing from it: the text field, and under it, while it has the focus, the matches, each with its bold name and a small grey line. The arrow keys move through the matches, Enter picks the lit one, Escape shuts the list, a press on a match picks it. A small drawn chevron at the field\'s end says it opens a list, unless it is a search.',
        module: '/components/PickField.js', sheet: '/css/components/pick-field.css',
        data: {
            shape: 'PickField({ items, onPick, onType, keep, search, match, max, placeholder, ariaLabel, emptyLabel, noMatchLabel, label, hint })',
            fields: {
                items: '[{ id, name, sub, disabled }]; a disabled one shows and cannot be picked',
                onPick: 'onPick(item): the pick',
                keep: 'the field shows the picked name after the pick; without it the field empties',
                onType: 'onType(text): typing again, so the page can let a kept pick go',
                search: 'the field is a search (the magnifier; Escape empties it) and has no chevron',
                match: 'match(item, q): whether an item matches the lower-case words; by default its name, sub and id',
                max: 'how many matches show at once (8)',
                emptyLabel: 'the line when there is nothing to pick at all', noMatchLabel: 'the line when nothing matches',
                placeholder: 'the field\'s grey words', ariaLabel: 'the field\'s name for a screen reader',
                label: 'the field\'s label', hint: 'the grey line under the field',
            },
        },
        useFor: ['Choosing one person, agent or part out of a list too long for a drop-down, and saving only a thing that was picked, never words that were typed.'],
        variants: [
            { name: 'pick', prop: 'default', when: 'a field that opens a list; the chevron says so' },
            { name: 'keep', prop: 'keep', when: 'the pick stays in the field (the CORS page\'s person or agent)' },
            { name: 'search', prop: 'search', when: 'the field is a search that adds what is picked (the Portal page\'s parts)' },
        ],
        example: { keep: true, placeholder: 'Pick an agent', items: [{ id: 'bot', name: 'bot', sub: 'sandbox' }, { id: 'invoice-drafter', name: 'invoice-drafter', sub: 'sandbox' }] },
        note: 'Replaced the CORS page\'s person and agent picker (.adm-cors-pick) and the Portal page\'s "add a part" picker (.adm-pt-pick), the same field twice on main, with the CORS picker\'s keyboard for both. The field is TextField (form-fields.css).',
    },
    {
        id: 'status-page-preview', name: 'StatusPagePreview', kind: 'component', status: 'active',
        summary: 'The page a node serves in its own place (the 503 of maintenance), drawn small as a visitor gets it: the status line and the content type in typewriter letters on top, then the node\'s name, the headline in the poster face, the line the operator wrote and the line under it. Over it its row label, or while the page is live the coral "live" mark with its square; a grey hint under it.',
        module: '/components/StatusPagePreview.js', sheet: '/css/components/status-page-preview.css',
        data: {
            shape: 'StatusPagePreview({ status, type, node, head, message, sub, label, live, hint })',
            fields: {
                status: 'the status line ("503 Service Unavailable")', type: 'the content type', node: 'the node\'s name',
                head: 'the headline', message: 'the line the operator wrote', sub: 'the line under it',
                label: 'the words over the preview', live: 'the page is being served now: the label is the coral live mark',
                hint: 'the grey line under the preview',
            },
        },
        useFor: ['Showing an operator what visitors and agents will get while the node is in maintenance, before and while it is on.'],
        variants: [
            { name: 'preview', class: 'status-page-preview-label', prop: 'default', when: 'the page is not served yet: what it would be' },
            { name: 'live', class: 'status-page-preview-live', prop: 'live', when: 'the page is being served now' },
        ],
        example: { status: '503 Service Unavailable', type: 'text/html', node: 'aimeat-local-001-dev', head: 'Down for work', message: 'Back at 14:00 UTC.', sub: 'Your data is untouched and you are still signed in.', label: 'What they see' },
        note: 'Replaced the Maintenance page\'s 503 preview (.adm-maint-prev*).',
    },
    {
        id: 'search-preview', name: 'SearchPreview', kind: 'component', status: 'active',
        summary: 'How a site shows up elsewhere, drawn from what it serves: a search engine\'s result (the address in typewriter letters, the name as the coral link line, the sentence in grey) and the card a shared link unfolds into (the picture, or a dark place that says there is none, then the name, the sentence and the host). Each has its row label over it.',
        module: '/components/SearchPreview.js', sheet: '/css/components/search-preview.css',
        data: {
            shape: 'SearchResult({ label, url, title, desc }) · ShareCard({ label, image, noImage, title, desc, host })',
            fields: {
                label: 'the row label over the preview',
                url: 'SearchResult: the address line', title: 'the site\'s name', desc: 'the site\'s sentence',
                image: 'ShareCard: the picture\'s address', noImage: 'ShareCard: the words in the dark place when there is no picture',
                host: 'ShareCard: the host under the words',
            },
        },
        useFor: ['The Discovery page: what a search engine and a shared link will show of this node, beside the fields that set it.'],
        variants: [
            { name: 'search result', prop: 'SearchResult', when: 'how a search engine lists the site' },
            { name: 'share card', class: 'search-preview--card', prop: 'ShareCard', when: 'how a shared link unfolds' },
            { name: 'no picture', class: 'search-preview-img--none', prop: 'ShareCard without image', when: 'the site serves no share picture' },
        ],
        example: { label: 'In a search', url: 'https://harbour.studio', title: 'Harbour Studio', desc: 'Sound design for ferries and harbours.' },
        note: 'Replaced the Discovery page\'s two previews (.adm-disc-frame, .adm-disc-serp-*, .adm-disc-card-*).',
    },
    {
        id: 'save-bar', name: 'SaveBar', kind: 'component', status: 'active',
        summary: 'The row that keeps unsaved work and the one button that saves it in sight wherever the page is scrolled: pinned under the top bar, on the surface ground with the coral edge at its left, its parts in one wrapping line.',
        module: '/components/SaveBar.js', sheet: '/css/components/save-bar.css',
        data: {
            shape: 'SaveBar({ label, children })',
            fields: {
                label: 'the row\'s name for a screen reader',
                children: 'what stands in it: the loud save, how many changes wait, the ways to see or undo them, a hint',
            },
        },
        useFor: ['A page where a person makes many changes and saves them together, such as the front page\'s layout.'],
        variants: [
            { name: 'unsaved', prop: 'children', when: 'changes wait: the count and the ways to see or undo them stand beside the save' },
            { name: 'nothing unsaved', prop: 'children', when: 'the save is off and a hint says there is nothing to save' },
        ],
        example: { label: 'Save the layout' },
        note: 'Replaced the Portal page\'s pinned save row (.adm-pt-pin).',
    },
    {
        id: 'move-buttons', name: 'MoveButtons', kind: 'component', status: 'active',
        summary: 'The two small buttons that move a thing one place up or down in its list: two drawn chevrons, each named in its tooltip and for a screen reader. The first thing cannot go up and the last cannot go down, so that button is off. Stacked by default, side by side when `across`.',
        module: '/components/MoveButtons.js', sheet: '/css/components/move-buttons.css',
        data: {
            shape: 'MoveButtons({ onUp, onDown, first, last, upLabel, downLabel, across })',
            fields: {
                onUp: 'moves the thing up', onDown: 'moves it down',
                first: 'the first thing: up is off', last: 'the last thing: down is off',
                upLabel: 'the up button\'s name and tooltip', downLabel: 'the down button\'s name and tooltip',
                across: 'side by side, at a row\'s end; stacked otherwise, at a row\'s start',
            },
        },
        useFor: ['Putting the parts of a list in order where dragging is too coarse or not at hand.'],
        variants: [
            { name: 'stacked', prop: 'default', when: 'at the start of a row (the front page\'s parts)' },
            { name: 'across', class: 'move-buttons--across', prop: 'across', when: 'at the end of a row (a menu\'s links)' },
        ],
        example: { first: true, last: false, upLabel: 'Move up', downLabel: 'Move down' },
        note: 'Replaced the Portal page\'s part and menu arrows (.adm-pt-move, .adm-pt-move--menu).',
    },
    {
        id: 'day-chart', name: 'DayChart', kind: 'component', status: 'active',
        summary: 'Numbers by day as bars, without a chart library. DayChart is one framed chart with its own axis: one or two series side by side each day, a legend, a line over the plot that says what the tallest bar is worth and, under the pointer, what that day read, the days under the plot and a note under them. DaySpark is one series as a row of thin bars, the newest day at the right edge, for a row of a list. Every bar says its day and value as its tooltip.',
        module: '/components/DayChart.js', sheet: '/css/components/day-chart.css',
        data: {
            shape: 'DayChart({ title, series, days, axis, readAt, format, note, label, peak }) · DaySpark({ values, days, tone, format }) · barHeight(value, peak)',
            fields: {
                title: 'the chart\'s name',
                series: '[{ label, values, tone }], one value per day, one or two series; a legend always',
                days: 'the days as YYYY-MM-DD; the axis writes MM-DD',
                axis: 'the line over the plot while the pointer is away ("tallest bar: 1 234")',
                readAt: 'readAt(i): the line while the pointer is on day i',
                format: 'format(v): a value as words (a number by default, money on a page of spend)',
                note: 'the grey line under the chart', label: 'the plot\'s name for a screen reader',
                peak: 'the value the full height stands for; the tallest bar by default',
                tone: 'first | second | critical | plain: the series colour, the same in both modes',
                values: 'DaySpark: the one series',
            },
        },
        useFor: ['Daily numbers on an operator page (reads and writes, refusals, spend): two charts, never one chart with two scales, when the numbers differ in size.'],
        variants: [
            { name: 'first', class: 'day-chart-bar--first', prop: 'tone="first"', when: 'the first named series (a blue)' },
            { name: 'second', class: 'day-chart-bar--second', prop: 'tone="second"', when: 'the second named series (an orange)' },
            { name: 'critical', class: 'day-chart-bar--critical', prop: 'tone="critical"', when: 'a number that is a refusal, in the status red' },
            { name: 'plain', class: 'day-chart-bar--plain', prop: 'tone="plain"', when: 'a single unnamed series, in the words\' grey' },
            { name: 'spark', class: 'day-spark', prop: 'DaySpark', when: 'a small series inside a row of a list' },
        ],
        example: { title: 'Memory', days: ['2026-09-25', '2026-09-26', '2026-09-27'], axis: 'tallest bar: 412', series: [{ label: 'reads', tone: 'first', values: [310, 412, 280] }, { label: 'writes', tone: 'second', values: [40, 55, 38] }] },
        note: 'Replaced the Statistics page\'s Plot and Spark (stats-tab.days.js, .adm-st-chart, .adm-st-spark) and the Usage page\'s ByDay chart (usage-tab.models.js, .adm-us-chart), with the series tones the two pages\' sheets carried.',
    },
    {
        id: 'trend-line', name: 'TrendLine', kind: 'component', status: 'active',
        summary: 'One number over time as a line in inline SVG: its name as a row label with small typewriter words at its right, the line in one hue, the newest reading marked with a coral tick, and while the pointer is on it a vertical cursor and the reading nearest it in a small box at the top right; the two ends written under it. A dashed midline and a sun ground under the line are options.',
        module: '/components/TrendLine.js', sheet: '/css/components/trend-line.css',
        data: {
            shape: 'TrendLine({ label, note, points, readAt, ends, mid, area, ariaLabel })',
            fields: {
                points: 'the readings, oldest first; with none it draws nothing',
                readAt: 'readAt(i): the words of reading i in the box',
                ends: '[left, right]: the words under the two ends',
                mid: 'the words of the dashed line across the middle; no line without',
                area: 'a sun ground under the line',
                label: 'the name over the line', note: 'the small words at its right',
                ariaLabel: 'the picture\'s name for a screen reader (the label by default)',
            },
        },
        useFor: ['How one measured number moved over the last days or hours, on an operator page.'],
        variants: [
            { name: 'line', prop: 'points', when: 'one number over time' },
            { name: 'midline', class: 'trend-line-mid', prop: 'mid', when: 'the value at the middle of the range is worth reading' },
            { name: 'ground', class: 'trend-line-area', prop: 'area', when: 'readings that sit in a narrow band read better as a surface' },
        ],
        example: { label: 'Database size', note: 'seven days', points: [120, 124, 123, 131, 138, 140, 146], ends: ['120 MB · oldest', '146 MB · now'] },
        note: 'Replaced the Database page\'s seven-day line (database-tab.js Line, .adm-db-chart) and the Metrics page\'s session line (metrics-tab.js Line, .adm-mx-chart); the midline and the sun ground are the two pages\' differences, kept as options.',
    },
    {
        id: 'count-bars', name: 'CountBars', kind: 'component', status: 'active',
        summary: 'Counts grouped by what they count: one line per key with an ink bar as long as its share of the biggest count and the count at the right. Length is the whole encoding, so a grouping reads the same with four keys or forty; only coral on a key the page names hot and the warning ink on a key the page cannot vouch for carry a meaning. The default look is a row label over mono rows with a short bar and hairlines between them; the wide look takes the section\'s width, its title and why line at the left and long bars on a track at the right.',
        module: '/components/CountBars.js', sheet: '/css/components/count-bars.css',
        data: {
            shape: 'CountBars({ label, title, why, rows, keyOf, hot, words, more, max, wide, last }) · CountBarsSet({ children })',
            fields: {
                label: 'the row label over the rows',
                title: 'what the grouping groups by, in bold', why: 'the grey line under the title',
                rows: '[{ key, name, count, note, tone, onPick, title }]: count is the bar and the figure; note a short warning word beside the name; tone "warn" the bar in the warning colour; onPick makes the name a button that narrows a list; title the name\'s tooltip',
                keyOf: 'keyOf(row): the words for a row\'s key when the rows carry no name',
                hot: 'the keys whose bar is coral',
                words: 'the keys are words, not machine readings, and there is no bar',
                more: '{ name, count }: the last line, in words ("12 more sources")',
                max: 'the longest bar in pixels in the default look (90)',
                wide: 'the wide look', last: 'the last grouping of its section: no rule under it',
                children: 'CountBarsSet: the groupings, side by side and one under the other on a narrow screen',
            },
        },
        useFor: ['Where the refusals or the packages come from: counts per door, per address, per author, read at a glance and pressed to narrow a list.'],
        variants: [
            { name: 'hot', class: 'count-bars-bar--hot', prop: 'hot', when: 'a key the page names hot (an address the tarpit walled)' },
            { name: 'warn', class: 'count-bars-bar--warn', prop: 'rows[].tone="warn"', when: 'a key the page cannot vouch for' },
            { name: 'words', class: 'count-bars-row--words', prop: 'words', when: 'the keys are words, and there is no bar' },
            { name: 'wide', class: 'count-bars--wide', prop: 'wide', when: 'a grouping that takes the section\'s width, with its title and why line' },
            { name: 'last', class: 'count-bars--last', prop: 'wide last', when: 'the last wide grouping of its section' },
            { name: 'set', class: 'count-bars-set', prop: 'CountBarsSet', when: 'several groupings side by side' },
        ],
        example: { label: 'By door', rows: [{ key: '/v1/memory', count: 412 }, { key: '/v1/auth/login', count: 96 }, { key: '/v1/apps', count: 12 }] },
        note: 'Replaced the Security page\'s three groupings of the refusal log (Grouping in views/admin/security-tab.refusals.js, .adm-sec-* in admin-security.css) and the Knowledge page\'s facets (FacetBars, .adm-kn-cut and .adm-kn-part in admin-knowledge.css), one kind of thing. The bar lengths are SVG widths, not styles.',
    },
    {
        id: 'print-page', name: 'PrintPage', kind: 'component', status: 'active',
        summary: 'A page that prints as a document: on screen the page is the work, on paper only the document part stands, without the site\'s frame around it. The document is always in the page and hidden on screen, so a Print button and the reader\'s own Ctrl+P print the same. Its parts on paper: a heading with a stamp line, part headings, register entries with their fields, answers in two columns and reasons, and a numbered list with grey help lines.',
        module: '/components/PrintPage.js', sheet: '/css/components/print-page.css',
        data: {
            shape: 'PrintPage({ children }) · ScreenOnly({ children }) · PrintOnly({ children }) · PrintHead({ title, line }) · PrintHeading({ children }) · PrintEntry({ title, tag, desc, fields, answers, reasons, reasonsLabel, emptyAnswer }) · PrintList({ items })',
            fields: {
                children: 'PrintPage: the page\'s root; ScreenOnly: what only the screen shows; PrintOnly: the document; PrintHeading: a part\'s heading',
                title: 'PrintHead: the document\'s heading; PrintEntry: the entry\'s title', line: 'PrintHead: the stamp line (where, when, which version)',
                tag: 'PrintEntry: a class beside the title', desc: 'PrintEntry: its description',
                fields: 'PrintEntry: [{ key, label, value }]; a list value joined with commas, an empty one left out',
                answers: 'PrintEntry: [{ key, question, answer, source }]; an empty answer says emptyAnswer in italics, a source stands in brackets',
                reasons: 'PrintEntry: the reasons, a bulleted list under reasonsLabel',
                items: 'PrintList: [{ key, text, help }], the help on its own line in grey',
            },
        },
        useFor: ['A register or a report an operator hands over on paper or as a PDF, printed from the page that edits it.'],
        variants: [
            { name: 'on screen', class: 'print-screen-only', prop: 'ScreenOnly', when: 'the working page, left out on paper' },
            { name: 'on paper', class: 'print-only', prop: 'PrintOnly', when: 'the document, hidden on screen' },
            { name: 'entry', class: 'print-entry', prop: 'PrintEntry', when: 'one entry of a register, kept on one sheet' },
            { name: 'list', class: 'print-list', prop: 'PrintList', when: 'a numbered list with help lines' },
        ],
        example: { title: 'Processing register', line: 'aimeat-local-001-dev · 2026-09-27 · version 3' },
        note: 'Replaced the Compliance page\'s printout (views/admin/compliance-tab.print.js markup, .adm-cmp-print-only, .adm-cmp-pr-* and the body.adm-compliance-active print block in views/admin.css). PrintPage marks the body (print-page-active) while it is on screen, and every print rule is scoped to that mark, so no print rule follows the reader to another page. A part marked data-print-keep prints too (the operator frame\'s bar).',
    },
    {
        id: 'settings-index', name: 'SettingsIndex', kind: 'component', status: 'active',
        summary: 'A long list of settings a person searches and edits: a row of tools pinned under the page\'s bar (the search with its magnifier, the filters, and while something is unsaved the words and actions that say so), the index of the groups beside the settings that stays in sight while they scroll, one line per setting, and the unsaved changes as old, struck through, then → and the new value.',
        module: '/components/SettingsIndex.js', sheet: '/css/components/settings-index.css',
        data: {
            shape: 'SettingsIndex({ search, filters, status, before, index, indexLabel, empty, children }) · SettingLine({ id, name, flag, flagTitle, code, desc, source, editor, end }) · ChangeList({ items })',
            fields: {
                search: '{ value, onInput(value), placeholder, label }: the pinned search field',
                filters: 'the filters beside it (a Tabs row)',
                status: 'what stands after them while something is unsaved (the count, save, cancel); a screen reader hears it as a status',
                before: 'what stands over the settings (the change list, a banner, the message after a save)',
                index: '[{ key, label, items: [{ key, label, count, onClick }] }]: the groups of the index (the contents rail); with none the settings are not drawn',
                indexLabel: 'the index\'s name for a screen reader', empty: 'the words when nothing matches',
                children: 'the settings, grouped by the page (Section, SubHeading)',
                name: 'SettingLine: the setting\'s name', flag: 'SettingLine: the mark that it is edited and not saved', flagTitle: 'SettingLine: the flag\'s tooltip',
                code: 'SettingLine: its key, in typewriter letters', desc: 'SettingLine: what it does',
                source: 'SettingLine: where its value comes from (a status mark)', editor: 'SettingLine: the field that edits it',
                end: 'SettingLine: what stands at the end (a reset)',
                items: 'ChangeList: [{ key, code, was, now }]',
            },
        },
        useFor: ['The node\'s configuration: hundreds of settings a person finds by searching or by the index, edits in place and saves together.'],
        variants: [
            { name: 'settings', prop: 'index + children', when: 'settings match' },
            { name: 'unsaved', class: 'settings-index-status', prop: 'status', when: 'something is edited and not saved' },
            { name: 'edited line', class: 'setting-line-flag', prop: 'SettingLine flag', when: 'a setting edited and not saved' },
            { name: 'changes', class: 'setting-changes', prop: 'ChangeList', when: 'the list of unsaved changes, old and new' },
            { name: 'nothing matches', prop: 'empty', when: 'the search or the filter leaves no setting' },
        ],
        example: { indexLabel: 'Sections', empty: 'No setting matches.', search: { value: '', placeholder: 'Search settings…' } },
        note: 'Replaced the admin Config page\'s pinned tools, left index, field rows and old → new list (views/admin/config-tab.js; .adm-cfg-tools, .adm-cfg-searchwrap, .adm-cfg-pending-mini, .adm-cfg-listbox, .adm-cfg-body, .adm-cfg-rail, .adm-cfg-frow and its cells in views/admin.css). The index is the library\'s contents rail (Rail.js, tab-page.css). On a phone a setting\'s cells stand under each other.',
    },
    {
        id: 'shots', name: 'Shots', kind: 'component', status: 'active',
        summary: 'Pictures of pages side by side, each with its caption: a page\'s screenshot in the Object box\'s frame, cut to its top, with a bold caption and a typewriter line under it; where a page has no picture, a grey place that says so. Two to a row, one on a narrow screen.',
        module: '/components/Shots.js', sheet: '/css/components/shots.css',
        data: {
            shape: 'Shots({ items })',
            fields: {
                items: '[{ key, src, alt, none, caption, sub }]; a falsy item is left out',
                src: 'the picture\'s address, loaded lazily', alt: 'the picture\'s words for a screen reader',
                none: 'the words in the grey place when there is no picture',
                caption: 'the words under the picture (what it is)', sub: 'the typewriter line under them (whose page it is)',
            },
        },
        useFor: ['Telling a copy from a coincidence by looking at two pages side by side: the original beside the suspected copy.'],
        variants: [
            { name: 'pictures', class: 'shot-picture', prop: 'items[].src', when: 'the page has a screenshot' },
            { name: 'no picture', class: 'shot-none', prop: 'items[].none', when: 'the page has no screenshot yet' },
        ],
        example: { items: [{ key: 'a', caption: 'The original', sub: 'charts · sandbox', none: 'No picture yet' }, { key: 'b', caption: 'The suspected copy', sub: 'charts-2 · bot', none: 'No picture yet' }] },
        note: 'Replaced the admin Applications page\'s picture pair (apps-tab.scan.js Shot, .adm-ap-pair and .adm-ap-shot* in admin-apps.css).',
    },
];
