/**
 * @file src/services/ui-library/entries-page.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Catalogue entries for the parts a page is built from: its frame and headline, the
 *   masthead, the bands and the rows inside them, the record of what happened, the settings dialog's
 *   insides, the task chooser and an operator's own passages. The purpose half only;
 *   facts.generated.ts carries what the files say.
 * @structure PAGE_ENTRIES
 * @usage import { PAGE_ENTRIES } from './entries-page.js';
 * @version-history
 *   v1.1.0 — 2026-09-23 — DiagonalBand deleted with ChatDoor (Jouni's decision); Specimen added.
 *   v1.0.0 — 2026-09-23 — Initial (UI consolidation phase 1).
 */
import type { UiEntrySource } from './types.js';

const one = (children: string) => ({ children });

export const PAGE_ENTRIES: UiEntrySource[] = [
    {
        id: 'page-frame', name: 'PageFrame', kind: 'component', status: 'active',
        summary: 'The page itself: a wide paper column, or a narrow one for reading, or a loading state.',
        module: '/components/PageFrame.js', sheet: '/css/components/page-frame.css',
        data: { shape: 'PageFrame({ width, loading, children })', fields: { width: "'wide' (default) or 'narrow'", loading: 'true while the page has nothing to show yet', children: 'the page' } },
        use: ['The outermost element of a page in the poster look.'],
        variants: [{ name: 'narrow', class: 'poster-page--narrow', prop: "width='narrow'", when: 'a page that is read rather than worked in' }],
        example: { width: 'wide', children: '…' },
    },
    {
        id: 'page-intro', name: 'PageIntro', kind: 'component', status: 'active',
        summary: 'A page\'s own headline and one line under it.',
        module: '/components/PageIntro.js', sheet: '/css/components/page-intro.css',
        data: { shape: 'PageIntro({ title, sub })', fields: { title: 'the page headline', sub: 'one line on what the page is for' } },
        use: ['The first thing on a page that has no masthead.'],
        variants: [],
        example: { title: 'What has happened', sub: 'Everything your agents and you did here, newest first.' },
    },
    {
        id: 'error-note', name: 'ErrorNote', kind: 'component', status: 'active',
        summary: 'What went wrong, in a danger frame, with a hint and a way forward.',
        module: '/components/ErrorNote.js', sheet: '/css/components/error-note.css',
        data: { shape: 'ErrorNote({ text, hint, children }) · ErrorNoteFallback({ onClick, children })', fields: { text: 'what went wrong, in words', hint: 'what to do about it', children: 'an optional way forward (ErrorNoteFallback)' } },
        use: ['A refusal a person can act on. Name what was missing rather than "try again".'],
        variants: [],
        example: { text: 'I could not find a page in what you pasted.', hint: 'Your text is still in the box.' },
    },
    {
        id: 'action-row', name: 'ActionRow', kind: 'component', status: 'active',
        summary: 'A row of actions that becomes one per line on a phone.',
        module: '/components/ActionRow.js', sheet: '/css/components/action-row.css',
        data: { shape: 'ActionRow({ children })', fields: { children: 'the buttons, the next move first' } },
        use: ['The actions at the foot of a step or a card.'],
        variants: [],
        example: one('<button class="btn-primary">Here is my welcome mat</button>'),
    },
    {
        id: 'hint', name: 'Hint', kind: 'component', status: 'active',
        summary: 'A quiet line of help under a control.',
        module: '/components/Hint.js', sheet: '/css/components/hint.css',
        data: { shape: 'Hint({ children })', fields: { children: 'the help sentence' } },
        use: ['One sentence that tells what a control does or what happens next.'],
        variants: [],
        example: one('You can change the name later.'),
    },
    {
        id: 'masthead', name: 'Masthead', kind: 'component', status: 'active',
        summary: 'The top of a person\'s page: the avatar in its frame, the name as a headline, the identity line, and the doors on the right.',
        module: '/components/Masthead.js', sheet: '/css/components/masthead.css',
        data: {
            shape: 'Masthead({ avatarSvg, name, identity, identityTitle, children }) · MastheadButton({ onClick, children }) · MastheadCog',
            fields: { avatarSvg: 'the avatar as an SVG string', name: 'the person\'s name', identity: 'their address on this node', identityTitle: 'the full identity on hover', children: 'the doors: links with poster-action, or a MastheadButton' },
        },
        use: ['The home and any page that belongs to one person.'],
        variants: [],
        example: { avatarSvg: '<svg…/>', name: 'Alice', identity: 'alice@aimeat.io', children: 'Settings' },
    },
    {
        id: 'link-line', name: 'LinkLine', kind: 'component', status: 'active',
        summary: 'One sentence with a coral link in it.',
        module: '/components/LinkLine.js', sheet: '/css/components/link-line.css',
        data: { shape: 'LinkLine({ label, href, text })', fields: { label: 'the words before the link', href: 'where it goes', text: 'the link words' } },
        use: ['An address a person may want to open or share, said in a sentence.'],
        variants: [],
        example: { label: 'Your welcome mat is at', href: 'https://alice.aimeat.io/mat', text: 'alice.aimeat.io/mat' },
    },
    {
        id: 'stat-line', name: 'StatLine', kind: 'component', status: 'active',
        summary: 'One line with its number set big, or a state dot, over a 3px ink rule (poster.css .poster-stat).',
        module: '/components/StatLine.js', sheet: '/css/components/stat-line.css',
        data: {
            shape: 'StatLine({ href, tone, icon, dot, children }) · statSentence(sentence, placeholder, value)',
            fields: { href: 'where the line leads', tone: "'alert', 'ok' or 'trouble'", icon: 'an optional inline SVG', dot: 'a state dot instead of a number', children: 'the sentence; statSentence sets its number big where the language puts it' },
        },
        use: ['A count or a state a person reads at a glance and can open.'],
        variants: [
            { name: 'alert', class: 'poster-stat--alert', prop: "tone='alert'", when: 'something waits for the person' },
            { name: 'ok', class: 'poster-stat--ok', prop: "tone='ok'", when: 'all is well' },
            { name: 'trouble', class: 'poster-stat--trouble', prop: "tone='trouble'", when: 'something is broken' },
        ],
        example: { href: '/v1/inbox', tone: 'alert', children: '3 messages wait for you' },
    },
    {
        id: 'band', name: 'Band', kind: 'component', status: 'active',
        summary: 'A section of a page: the ink headline slab (poster.css .poster-section-title--large) and the rows under it.',
        module: '/components/Band.js', sheet: '/css/components/band.css',
        data: { shape: 'Band({ title, tight, children }) · BandNote({ children })', fields: { title: 'the section headline', tight: 'less space above, for a band the layout engine places', children: 'the rows' } },
        use: ['Each section of the home, and each block the layout engine draws with a title.'],
        variants: [{ name: 'tight', class: 'poster-band--tight', prop: 'tight', when: 'a band inside a layout, where the engine sets the rhythm' }],
        example: { title: 'Your things', children: '…' },
    },
    {
        id: 'line-list', name: 'LineList', kind: 'component', status: 'active',
        summary: 'A list of one-line pointers: who, then what they said, cut to one line.',
        module: '/components/LineList.js', sheet: '/css/components/line-list.css',
        data: { shape: 'LineList({ rows, more })', fields: { rows: '[{ id, name, text, href }]', more: 'a sentence for the rows not shown, or null' } },
        use: ['Messages or posts where the person only needs to know who and roughly what.'],
        variants: [],
        example: { rows: [{ id: '1', name: 'Bob', text: 'The draft is ready for you to read', href: '/v1/inbox/1' }], more: 'and 4 more' },
    },
    {
        id: 'named-row', name: 'NamedRow', kind: 'component', status: 'active',
        summary: 'A row with its category word in a fixed left column and its content on the right, under a 3px ink rule.',
        module: '/components/NamedRow.js', sheet: '/css/components/named-row.css',
        data: { shape: 'NamedRow({ label, title, children })', fields: { label: 'the category word', title: 'the full category on hover', children: 'the row content' } },
        use: ['A band that lists several kinds of thing, one kind per row.'],
        variants: [],
        example: { label: 'Apps', children: 'ThingLink × n' },
    },
    {
        id: 'thing-link', name: 'ThingLink', kind: 'component', status: 'active',
        summary: 'A thing a person has, as a link: an optional coral count and its name.',
        module: '/components/ThingLink.js', sheet: '/css/components/thing-link.css',
        data: {
            shape: 'ThingLink({ href, n, label, named, newTab }) · ThingChip({ href, label, n, starred, starTitle, onStar })',
            fields: { href: 'where it opens', n: 'a count, or nothing', label: 'its name', named: 'a named thing rather than a count', newTab: 'opens in a new tab', starred: 'ThingChip: kept always visible', onStar: 'ThingChip: toggles the star' },
        },
        use: ['Inside a NamedRow: the apps, workspaces or records a person has.'],
        variants: [{ name: 'named', class: 'poster-thing--named', prop: 'named', when: 'one named thing rather than a count of a kind' }],
        example: { href: '/v1/apps', n: 12, label: 'apps' },
    },
    {
        id: 'star-toggle', name: 'StarToggle', kind: 'component', status: 'active',
        summary: 'A star that keeps one thing always visible.',
        module: '/components/StarToggle.js', sheet: '/css/components/star-toggle.css',
        data: { shape: 'StarToggle({ on, title, onClick })', fields: { on: 'starred', title: 'what the star does', onClick: 'toggle' } },
        use: ['Beside a thing in a list that shows only some of them.'],
        variants: [{ name: 'on', class: 'poster-star--on', prop: 'on', when: 'the thing is starred' }],
        example: { on: true, title: 'Keep this one visible' },
    },
    {
        id: 'fold-button', name: 'FoldButton', kind: 'component', status: 'active',
        summary: 'A mono coral underlined button: without `on` the action link\'s more tone, with `on` the tab\'s fold tone; the chosen one on the sun.',
        module: '/components/FoldButton.js', sheet: '/css/components/fold-button.css',
        data: { shape: 'FoldButton({ on, expanded, onClick, children })', fields: { on: 'given: one choice in a ModeSwitch, true for the chosen one', expanded: 'aria-expanded for a fold', onClick: 'handler', children: 'the words' } },
        use: ['"Show all" under a cut list, or one choice in a ModeSwitch.'],
        variants: [{ name: 'on', prop: 'on', when: 'the chosen one (poster.css .poster-tab--fold.is-on)' }],
        example: one('Show all'),
    },
    {
        id: 'mode-switch', name: 'ModeSwitch', kind: 'component', status: 'active',
        summary: 'A small group of fold buttons that chooses what a row shows.',
        module: '/components/ModeSwitch.js', sheet: '/css/components/mode-switch.css',
        data: { shape: 'ModeSwitch({ label, children })', fields: { label: 'what is being chosen, for a screen reader', children: 'FoldButtons' } },
        use: ['A row that can show one of two or three lists.'],
        variants: [],
        example: { label: 'Which apps', children: 'FoldButton on: Recent · FoldButton: Mine' },
    },
    {
        id: 'quiet-note', name: 'QuietNote', kind: 'component', status: 'active',
        summary: 'A quiet line where a list has nothing to show.',
        module: '/components/QuietNote.js', sheet: '/css/components/quiet-note.css',
        data: { shape: 'QuietNote({ children })', fields: { children: 'what is empty, and what fills it' } },
        use: ['An empty list, said in words.'],
        variants: [],
        example: one('You have not opened any apps yet.'),
    },
    {
        id: 'numbered-index', name: 'NumberedIndex', kind: 'component', status: 'active',
        summary: 'A numbered index: each row a name with its number and an arrow; the open one shows its steps in a record (poster.css .poster-record).',
        module: '/components/NumberedIndex.js', sheet: '/css/components/numbered-index.css',
        data: {
            shape: 'NumberedIndex({ lead, label, tour, children, panel }) · IndexPanel({ what, steps, proof, children })',
            fields: { lead: 'the line above the index', label: 'the list name, for a screen reader', tour: '{ href, label } for a guided tour', children: 'the rows (FoldButtons)', panel: 'the open row\'s IndexPanel', what: 'what the open one is', steps: 'its steps', proof: 'how a person knows it worked' },
        },
        use: ['A short set of things a person can learn to do, one opened at a time.'],
        variants: [],
        example: { lead: 'Things to try', rows: ['Make a page', 'Connect an agent'], panel: { what: 'A page with its own address', steps: ['Ask for it', 'Open it'], proof: 'It opens in a new tab.' } },
    },
    {
        id: 'ink-foot', name: 'InkFoot', kind: 'component', status: 'active',
        summary: 'The foot of a page: two facts in paper words on ink.',
        module: '/components/InkFoot.js', sheet: '/css/components/ink-foot.css',
        data: { shape: 'InkFoot({ children })', fields: { children: 'two paragraphs' } },
        use: ['The last thing on a person\'s own page.'],
        variants: [],
        example: one('<p>Everything here is yours.</p><p>Nothing is public until you publish it.</p>'),
    },
    {
        id: 'check-item', name: 'CheckItem', kind: 'component', status: 'active',
        summary: 'One thing tried or not yet tried: a ticked box on the sun, or a dashed empty one.',
        module: '/components/CheckItem.js', sheet: '/css/components/check-item.css',
        data: { shape: 'CheckItem({ done, href, external, onClick, children })', fields: { done: 'tried', href: 'where to try it', external: 'opens elsewhere', onClick: 'handler', children: 'the thing' } },
        use: ['A list of first things to try, which ticks itself as they happen.'],
        variants: [{ name: 'done', class: 'poster-check--done', prop: 'done', when: 'already tried' }],
        example: { done: true, href: '/v1/chat', children: 'Talk to your agent' },
    },
    {
        id: 'timeline', name: 'Timeline', kind: 'component', status: 'active',
        summary: 'What has happened: time first, a category dot, one line, one rule per row.',
        module: '/components/Timeline.js', sheet: '/css/components/timeline.css',
        data: {
            shape: 'Timeline({ title, band, quiet, more, children }) · TimelineList({ children }) · TimelineRow({ category, live, href, text, when })',
            fields: { title: 'the headline', band: 'drawn as a Band', quiet: '{ href, text } for a quiet period', more: '{ href, text } to the full record', category: 'made, agent, trouble, money, access or system', live: 'happening now (pulses)', text: 'what happened', when: 'the time' },
        },
        use: ['A record of events, on the home and on the full history page.'],
        variants: [
            { name: 'made', class: 'poster-timeline-item--made', prop: "category='made'", when: 'something was made' },
            { name: 'agent', class: 'poster-timeline-item--agent', prop: "category='agent'", when: 'an agent did it' },
            { name: 'trouble', class: 'poster-timeline-item--trouble', prop: "category='trouble'", when: 'something failed' },
            { name: 'money', class: 'poster-timeline-item--money', prop: "category='money'", when: 'money moved' },
            { name: 'access', class: 'poster-timeline-item--access', prop: "category='access'", when: 'access changed' },
            { name: 'system', class: 'poster-timeline-item--system', prop: "category='system'", when: 'the node did it' },
            { name: 'live', class: 'poster-timeline-item--live', prop: 'live', when: 'still happening' },
        ],
        example: { title: 'What has happened', rows: [{ category: 'made', text: 'You published a page', when: '10:42', href: '/v1/pages/mat' }] },
    },
    {
        id: 'back-link', name: 'BackLink', kind: 'component', status: 'active',
        summary: 'A mono coral link back to where a person came from.',
        module: '/components/BackLink.js', sheet: '/css/components/back-link.css',
        data: { shape: 'BackLink({ href, onClick, children })', fields: { href: 'where back is', onClick: 'the router\'s handler', children: '↩ and the words' } },
        use: ['The top of a page a person reached from another one.'],
        variants: [],
        example: { href: '/v1/home', children: '↩ Back to your home' },
    },
    {
        id: 'day-group', name: 'DayGroup', kind: 'component', status: 'active',
        summary: 'One day of a record: the day as a small coral heading over its rows.',
        module: '/components/DayGroup.js', sheet: '/css/components/day-group.css',
        data: { shape: 'DayGroup({ title, children }) · DayList({ children }) · DayEmpty({ children })', fields: { title: 'the day', children: 'TimelineRows; DayEmpty says a record has nothing' } },
        use: ['A long record, grouped by day.', 'The heading alone (.poster-day-title) over any list: the chat\'s side column, and quiet over its work log.'],
        variants: [{ name: 'quiet', class: 'poster-day-title--quiet', prop: 'class', when: 'a heading over a record rather than over the page\'s structure (the chat\'s work log)' }],
        example: { title: 'Today', children: 'TimelineRow × n' },
    },
    {
        id: 'archive', name: 'ArchiveSection', kind: 'component', status: 'active',
        summary: 'The older part of a record, under its own rule, opened on request.',
        module: '/components/ArchiveSection.js', sheet: '/css/components/archive.css',
        data: { shape: 'ArchiveSection({ title, note, children }) · ArchiveMore({ disabled, onClick, children }) · ArchiveError({ children })', fields: { title: 'the heading', note: 'why it is kept apart', children: 'the older rows and an ArchiveMore' } },
        use: ['Where a record keeps what is older than its first page.'],
        variants: [],
        example: { title: 'Older', note: 'Kept for a year, then removed.', more: 'Show older' },
    },
    {
        id: 'settings-stack', name: 'SettingsStack', kind: 'component', status: 'active',
        summary: 'The inside of a settings dialog: its sections in one column.',
        module: '/components/SettingsStack.js', sheet: '/css/components/settings-stack.css',
        data: { shape: 'SettingsStack({ children })', fields: { children: 'poster-section elements' } },
        use: ['Inside a Modal that holds a page\'s own settings.'],
        variants: [],
        example: one('<section class="poster-section">…</section>'),
    },
    {
        id: 'settings-switch', name: 'SettingsSwitch', kind: 'component', status: 'active',
        summary: 'A setting that is on or off: a checkbox and its words.',
        module: '/components/SettingsSwitch.js', sheet: '/css/components/settings-switch.css',
        data: { shape: 'SettingsSwitch({ checked, onChange, children })', fields: { checked: 'on', onChange: 'flip', children: 'what it turns on' } },
        use: ['One on-or-off choice in a settings dialog.'],
        variants: [],
        example: { checked: true, children: 'Show what I have tried' },
    },
    {
        id: 'swatch-picker', name: 'SwatchPicker', kind: 'component', status: 'active',
        summary: 'A choice among a few named looks: a preview strip and the choices, the chosen one on the sun.',
        module: '/components/SwatchPicker.js', sheet: '/css/components/swatch-picker.css',
        data: {
            shape: 'SwatchPicker({ title, hint, preview, emptyLabel, choices, onChoose })',
            fields: { title: 'what is chosen', hint: 'one line of help', preview: 'the current look, drawn', emptyLabel: 'the words when nothing is chosen', choices: '[{ value, label, active }]', onChoose: 'called with the value' },
        },
        use: ['A pattern or colour choice with a handful of options.'],
        variants: [],
        example: { title: 'Margin pattern', choices: [{ value: 'none', label: 'None', active: true }, { value: 'dots', label: 'Dots', active: false }] },
    },
    {
        id: 'settings-door', name: 'SettingsDoor', kind: 'component', status: 'active',
        summary: 'A way out of a dialog to the full settings, as a row under the 3px ink rule.',
        module: '/components/SettingsDoor.js', sheet: '/css/components/settings-door.css',
        data: { shape: 'SettingsDoor({ href, title, hint })', fields: { href: 'the full settings', title: 'the door words', hint: 'what is there' } },
        use: ['The last row of a small settings dialog.'],
        variants: [],
        example: { href: '/v1/profile', title: 'All settings →', hint: 'Your account, your agents and your keys.' },
    },
    {
        id: 'open-items', name: 'OpenItemsList', kind: 'component', status: 'active',
        summary: 'What a person is going to do here: the list, its one prompt at the top, and the header button with the count.',
        module: '/components/OpenItemsList.js', sheet: '/css/components/open-items.css',
        data: { shape: 'OpenItemsList({ maxAgeDays })', fields: { maxAgeDays: 'hide rows older than this many days' } },
        use: ['The open items band on the home. It reads its own rows from the node.'],
        variants: [],
        example: { maxAgeDays: 7 },
        note: 'The header button with the count is OpenItemsButton, which reads the same sheet.',
    },
    {
        id: 'chooser', name: 'Chooser', kind: 'component', status: 'active',
        summary: 'Pick a task and get what it needs: the choices row, the panel with the sun bar that the choice governs, the status row, a framed box, a fold, the result and the links.',
        module: '/components/Chooser.js', sheet: '/css/components/chooser.css',
        data: {
            shape: 'Chooser({ titleId, title, lead, children }) · ChooserChoices({ label, children }) · ChooserChoice({ on, onClick, children }) · ChooserPanel · ChooserStatus · ChooserBox · ChooserFold({ summary }) · ChooserLinks · ChooserResult',
            fields: { titleId: 'the heading id', title: 'the headline', lead: 'the line under it', label: 'the choices, for a screen reader', on: 'the chosen task', summary: 'the fold\'s words' },
        },
        use: ['A band where the person first picks what they want to do, then gets the prompt or the connection for it.'],
        variants: [{ name: 'chosen', prop: 'on', when: 'the chosen task, the chosen tab (poster.css .poster-tab.is-on)' }],
        example: { title: 'Connect your AI', choices: [{ on: true, children: 'Claude' }, { on: false, children: 'ChatGPT' }] },
    },
    {
        id: 'settings-account', name: 'SettingsAccount', kind: 'component', status: 'active',
        summary: 'The account actions in a settings dialog, one per line, full-width headline.',
        module: '/components/SettingsAccount.js', sheet: '/css/components/settings-account.css',
        data: { shape: 'SettingsAccount({ title, children })', fields: { title: 'the headline', children: 'poster-action buttons' } },
        use: ['Sign out and the other account actions, at the foot of a settings dialog.'],
        variants: [],
        example: { title: 'Account', children: 'Sign out' },
    },
    {
        id: 'free-text', name: 'FreeText', kind: 'component', status: 'active',
        summary: 'A passage an operator wrote into a layout (plain, card or band), and the front page\'s text and notice blocks.',
        module: '/components/FreeText.js', sheet: '/css/components/free-text.css',
        data: { shape: 'FreeText({ tone, title, children }) · TextBlock({ title, children }) · NoticeBlock({ title, children })', fields: { tone: "'plain', 'card' or 'band'", title: 'an optional heading', children: 'the passage, as rendered Markdown' } },
        use: ['The common.freeform block, and the portal text and notice blocks.'],
        variants: [
            { name: 'card', class: 'poster-free--card', prop: "tone='card'", when: 'a framed passage' },
            { name: 'band', class: 'poster-free--band', prop: "tone='band'", when: 'a passage on a band' },
        ],
        example: { tone: 'card', title: 'Opening hours', children: 'We answer on weekdays.' },
    },
    {
        id: 'specimen', name: 'Specimen', kind: 'component', status: 'active',
        summary: 'One live preview of an interface part in its own frame, with a caption; a row of them shows one part in several looks side by side.',
        module: '/components/Specimen.js', sheet: '/css/components/specimen.css',
        data: {
            shape: 'Specimens({ children }) · Specimen({ label, src, phone, note })',
            fields: { label: 'the caption', src: 'the preview page address (/v1/design-lab/frame?id=&v=&theme=)', phone: 'a 390-pixel frame', note: 'a line under the frame' },
        },
        use: ['The design lab: every part drawn live, light and dark side by side, and at a phone width.'],
        variants: [{ name: 'phone', class: 'poster-specimen--phone', prop: 'phone', when: 'the phone-width frame' }],
        example: { label: 'Light', src: '/v1/design-lab/frame?id=turn&v=0&theme=light' },
    },
];
