/**
 * @file src/services/ui-library/entries-shell.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description The catalogue's shell parts and the older shared components: the parts theme.css held
 *   as rules until 2026-09-24 (the page base, the top bar, the classic buttons, cards, badges, the
 *   segmented control, forms, the toast…), each in its own css/components/ sheet now, and every
 *   /components module that had no entry. A part whose look still sits in a page sheet says so in
 *   its note: that look is debt, to move into a sheet of its own when the part is next touched.
 * @structure SHELL_ENTRIES
 * @usage import { SHELL_ENTRIES } from './entries-shell.js';
 * @version-history
 *   v1.1.0 — 2026-09-24 — FormField is active: Themes & Styles draws it.
 *   v1.0.0 — 2026-09-24 — Initial (UI consolidation: theme.css to tokens only; every module catalogued).
 */
import type { UiEntryWritten } from './types.js';

const PAGE_SHEET_NOTE = 'Its look still sits in a page sheet (the sheet named here): debt, to move into a css/components/ sheet of its own.';

export const SHELL_ENTRIES: UiEntryWritten[] = [
    {
        id: 'page-base', name: 'Page base', kind: 'component', status: 'active',
        summary: 'The page itself: the document and its base elements, the app root and its one scroll region, the scrollbar, the page entrance, the agent-facing footer links, the visually-hidden helper.',
        module: null, sheet: '/css/components/page-base.css', classes: ['page-content', 'bg-canvas', 'agent-footer', 'visually-hidden'],
        data: { shape: '<div id="app"><div class="page-content">…</div></div>', fields: { children: 'the view' } },
        useFor: ['Drawn once by spa.html around every view; a view never restyles it.'],
        variants: [], example: {},
    },
    {
        id: 'top-bar', name: 'Top bar', kind: 'component', status: 'active',
        summary: 'The bar on every page of the shell: the wordmark, the links, the open items, the bell, the login pill, the language and theme buttons, and its phone menu.',
        module: null, sheet: '/css/components/top-bar.css', classes: ['topnav', 'topnav-brand', 'lang-btn'],
        data: { shape: 'Header in spa.html', fields: { links: 'the pages a person may open', auth: 'the login pill' } },
        useFor: ['Drawn by spa.html (Header) at the top of every page.'],
        variants: [{ name: 'compact', class: 'topnav--compact', when: 'a narrow screen: the links fold into the menu' }],
        example: {},
    },
    {
        id: 'button', name: 'Classic button', kind: 'component', status: 'active',
        summary: 'The classic buttons: primary (coral), outline, ghost, danger, success and small, with their copied and success states.',
        module: null, sheet: '/css/components/button.css', classes: ['btn-primary', 'btn-outline', 'btn-ghost', 'btn-danger', 'btn-sm'],
        data: { shape: '<button class="btn-primary">…</button>', fields: { children: 'the words' } },
        useFor: ['The classic shell (admin and the older views). The poster pages use the action link and the slab.'],
        variants: [
            { name: 'outline', class: 'btn-outline', when: 'a second action' },
            { name: 'ghost', class: 'btn-ghost', when: 'a quiet action' },
            { name: 'small', class: 'btn-sm', when: 'in a row or a table' },
        ],
        example: { children: 'Save' },
    },
    {
        id: 'copy-button', name: 'CopyButton', kind: 'component', status: 'active',
        summary: 'A button that copies a text and says so for a moment; it wears the class it is given (a classic button, an action link, a slab).',
        module: '/components/CopyButton.js', sheet: '/css/components/button.css', classes: ['copied'],
        data: { shape: 'CopyButton({ text, className, label, copiedLabel, title })', fields: { text: 'what is copied', className: 'the look to wear', label: 'the words', copiedLabel: 'the words after copying' } },
        useFor: ['Anywhere a person copies a text into their own AI or elsewhere.'],
        variants: [], example: { text: 'Hello', label: 'Copy', copiedLabel: 'Copied' },
    },
    {
        id: 'card', name: 'Card', kind: 'component', status: 'active',
        summary: 'The classic card and its kin: the glass card, the content group, the stat card, the category card, the card header and title.',
        module: '/components/Card.js', sheet: '/css/components/card.css',
        data: { shape: 'Card({ title, subtitle, onClick, hoverable, variant, children })', fields: { title: 'the heading', subtitle: 'the line under it', children: 'the content' } },
        useFor: ['The classic shell. The poster pages use the box and the row.'],
        variants: [], example: { title: 'Storage', subtitle: 'What this node keeps' },
    },
    {
        id: 'badge', name: 'Badge', kind: 'component', status: 'active',
        summary: 'The classic badge: a small rounded word in capitals, in a tint class.',
        module: null, sheet: '/css/components/badge.css', classes: ['badge'],
        data: { shape: '<span class="badge badge-success">…</span>', fields: { children: 'the word' } },
        useFor: ['A state in the classic shell and in the profile (the design lab\'s Status decision covers it).'],
        variants: [], example: { children: 'active' },
    },
    {
        id: 'pill', name: 'Pill', kind: 'component', status: 'active',
        summary: 'The rounded shape primitive of the classic shell.',
        module: null, sheet: '/css/components/pill.css', classes: ['pill'],
        data: { shape: '<span class="pill">…</span>', fields: { children: 'the word' } },
        useFor: ['A rounded chip in the classic shell.'],
        variants: [], example: { children: 'pill' },
    },
    {
        id: 'seg', name: 'Segmented control', kind: 'component', status: 'active',
        summary: 'A row of joined buttons, the chosen one filled.',
        module: null, sheet: '/css/components/seg.css', classes: ['seg', 'seg-btn'],
        data: { shape: '<div class="seg"><button class="seg-btn active">…</button>…</div>', fields: { children: 'the choices' } },
        useFor: ['Choosing one of a few settings (the design lab\'s Choice decision covers it).'],
        variants: [], example: {},
    },
    {
        id: 'start-page', name: 'StartPageSetting', kind: 'component', status: 'active',
        summary: 'The start page setting: where a person lands, in words and a segmented control.',
        module: '/components/StartPageSetting.js', sheet: '/css/components/start-page.css',
        data: { shape: 'StartPageSetting({ className })', fields: { className: 'the row\'s place' } },
        useFor: ['The home\'s settings dialog and the profile\'s settings.'],
        variants: [], example: {},
    },
    {
        id: 'status-dot', name: 'StatusDot', kind: 'component', status: 'active',
        summary: 'A small coloured dot that says a state.',
        module: '/components/StatusDot.js', sheet: '/css/components/status-dot.css',
        data: { shape: 'StatusDot({ status, title })', fields: { status: 'ok | warn | error | off', title: 'what the state is' } },
        useFor: ['Beside a name whose state matters at a glance.'],
        variants: [], example: { status: 'ok', title: 'Running' },
    },
    {
        id: 'presence-dot', name: 'PresenceDot', kind: 'component', status: 'active',
        summary: 'Whether someone is here now: a dot, and a word when asked.',
        module: '/components/PresenceDot.js', sheet: '/css/components/presence-dot.css',
        data: { shape: 'PresenceDot({ ghii, status, size, label, title })', fields: { status: 'online | away | offline', label: 'show the word' } },
        useFor: ['Beside a person or an agent in a list.'],
        variants: [], example: { status: 'online', label: true },
    },
    {
        id: 'key-value-row', name: 'KeyValueRow', kind: 'component', status: 'active',
        summary: 'One named fact on a line: its label, its value, and a badge when asked.',
        module: '/components/KeyValueRow.js', sheet: '/css/components/key-value-row.css',
        data: { shape: 'KeyValueRow({ label, value, badge, mono })', fields: { label: 'what it is', value: 'the fact', mono: 'set the value in typewriter letters' } },
        useFor: ['A detail list in the classic shell.'],
        variants: [], example: { label: 'Node', value: 'aimeat-local-001-dev', mono: true },
    },
    {
        id: 'pagination', name: 'Pagination', kind: 'component', status: 'unused',
        summary: 'The way to the next page of a list: previous and next with the page, or one load-more button.',
        module: '/components/Pagination.js', sheet: '/css/components/pagination.css',
        data: { shape: 'Pagination({ page, totalPages, onPage }) · LoadMore({ onMore, loading, label })', fields: { page: 'the page shown', totalPages: 'how many' } },
        useFor: ['Under a long list in the classic shell.'],
        variants: [], example: { page: 2, totalPages: 5 }, note: 'No page draws it today: the lists page themselves. Kept until Jouni says keep or delete.',
    },
    {
        id: 'collapsible', name: 'Collapsible', kind: 'component', status: 'active',
        summary: 'A section that opens and closes under its heading.',
        module: '/components/Collapsible.js', sheet: '/css/components/collapsible.css',
        data: { shape: 'Collapsible({ title, open, onToggle, children })', fields: { title: 'the heading', children: 'what opens' } },
        useFor: ['Content a person reads only when they ask for it.'],
        variants: [], example: { title: 'Details', open: true },
    },
    {
        id: 'data-table', name: 'DataTable', kind: 'component', status: 'active',
        summary: 'Rows and columns of records.',
        module: '/components/DataTable.js', sheet: '/css/components/data-table.css',
        data: { shape: 'DataTable({ headers, rows, scroll, className })', fields: { headers: 'the column names', rows: 'the records, one array each' } },
        useFor: ['Records compared column by column (admin).'],
        variants: [], example: { headers: ['Name', 'State'], rows: [['alpha', 'on'], ['beta', 'off']] },
    },
    {
        id: 'usage-chart', name: 'UsageChart', kind: 'component', status: 'active',
        summary: 'A bar or line chart of use over time.',
        module: '/components/UsageChart.js', sheet: '/css/components/usage-chart.css',
        data: { shape: 'UsageChart({ type, labels, datasets, stacked, height, legend, yFormat })', fields: { labels: 'the x axis', datasets: 'the series' } },
        useFor: ['Use over time in the admin and the profile.'],
        variants: [], example: {},
    },
    {
        id: 'divider', name: 'Section divider', kind: 'component', status: 'unused',
        summary: 'A quiet line with a word between two sections.',
        module: null, sheet: '/css/components/divider.css', classes: ['section-divider'],
        data: { shape: '<div class="section-divider">…</div>', fields: { children: 'the word' } },
        useFor: ['Between two sections of the classic shell.'],
        variants: [], example: { children: 'or' }, note: 'No page draws it today. Kept until Jouni says keep or delete.',
    },
    {
        id: 'form-field', name: 'FormField', kind: 'component', status: 'active',
        summary: 'Form fields of the classic shell: the input, the textarea and the select, the form group with its label and its hint.',
        module: '/components/FormField.js', sheet: '/css/components/form-field.css',
        data: { shape: 'FormField({ label, hint, children, className })', fields: { label: 'what to write', hint: 'a line of help', children: 'the input' } },
        useFor: ['A form in the classic shell. The poster pages use TextInput.'],
        variants: [], example: { label: 'Name', hint: 'Lower-case letters and dashes.' }, note: 'Themes & Styles draws it (2026-09-24): a label and a hint around a text field, a choice or the CSS editor. The classic forms still write .input-field and .form-group as markup in page code.',
    },
    {
        id: 'search-bar', name: 'SearchBar', kind: 'component', status: 'active',
        summary: 'A field with its icon and its clear button.',
        module: '/components/SearchBar.js', sheet: '/css/components/search-bar.css',
        data: { shape: 'SearchBar({ value, onInput, placeholder, onSubmit, ariaLabel })', fields: { value: 'what is searched', placeholder: 'the hint in the field' } },
        useFor: ['Above a list that can be searched.'],
        variants: [], example: { placeholder: 'Search' },
    },
    {
        id: 'spinner', name: 'Spinner', kind: 'component', status: 'active',
        summary: 'The spinner and the loading line beside it.',
        module: '/components/Spinner.js', sheet: '/css/components/spinner.css',
        data: { shape: 'Spinner({ text })', fields: { text: 'what is loading' } },
        useFor: ['While a list or a page is loading.'],
        variants: [], example: { text: 'Loading…' },
    },
    {
        id: 'empty-state', name: 'EmptyState', kind: 'component', status: 'active',
        summary: 'An icon, a line and an action when a list has nothing.',
        module: '/components/EmptyState.js', sheet: '/css/components/empty-state.css',
        data: { shape: 'EmptyState({ icon, title, text, action, children })', fields: { title: 'what is empty', text: 'what to do', action: 'a button' } },
        useFor: ['An empty list in the classic shell (the poster pages say it with QuietNote).'],
        variants: [], example: { title: 'Nothing here yet', text: 'Your records appear here.' },
    },
    {
        id: 'text-utility', name: 'Muted text', kind: 'component', status: 'active',
        summary: 'The muted and meta text utilities.',
        module: null, sheet: '/css/components/text-utility.css', classes: ['text-muted', 'meta'],
        data: { shape: '<span class="text-muted">…</span>', fields: { children: 'the quieter words' } },
        useFor: ['A quieter line in the classic shell.'],
        variants: [], example: { children: 'updated 2 hours ago' },
    },
    {
        id: 'toggle-switch', name: 'ToggleSwitch', kind: 'component', status: 'active',
        summary: 'A switch that is on or off.',
        module: '/components/ToggleSwitch.js', sheet: '/css/components/toggle-switch.css',
        data: { shape: 'ToggleSwitch({ checked, onChange, label })', fields: { checked: 'on or off', label: 'what it switches' } },
        useFor: ['A setting that is on or off.'],
        variants: [], example: { checked: true, label: 'Notifications' },
    },
    {
        id: 'site-footer', name: 'Site footer', kind: 'component', status: 'active',
        summary: 'The footer at the end of every view, and the older centred footer.',
        module: null, sheet: '/css/components/site-footer.css', classes: ['site-footer', 'site-footer-row'],
        data: { shape: 'SiteFooter in spa.html', fields: { links: 'the documents and the machine links' } },
        useFor: ['Drawn by spa.html at the end of every view.'],
        variants: [], example: {},
    },
    {
        id: 'alert', name: 'Alert', kind: 'component', status: 'active',
        summary: 'A line that says something went right or wrong, in its tone.',
        module: '/components/Alert.js', sheet: '/css/components/alert.css',
        data: { shape: 'Alert({ type, message, onDismiss })', fields: { type: 'info | success | warn | error', message: 'what happened' } },
        useFor: ['The result of an action in the classic shell.'],
        variants: [], example: { type: 'success', message: 'Saved.' },
    },
    {
        id: 'toast', name: 'Toast', kind: 'component', status: 'active',
        summary: 'A passing word in a box at the edge of the screen.',
        module: '/components/Toast.js', sheet: '/css/components/toast.css',
        data: { shape: 'const toast = useToast(); toast.show(message, kind)', fields: { message: 'what happened', kind: 'info | success | error' } },
        useFor: ['A result that does not need a place on the page.'],
        variants: [], example: {},
    },
    {
        id: 'section-header', name: 'Section header (classic)', kind: 'component', status: 'active',
        summary: 'The classic section and page headers: a title with its supporting line.',
        module: null, sheet: '/css/components/section-header.css', classes: ['section-title', 'section-desc', 'page-title', 'page-subtitle'],
        data: { shape: '<h2 class="section-title">…</h2><p class="section-desc">…</p>', fields: { title: 'the heading', desc: 'the line under it' } },
        useFor: ['The classic shell. The poster pages use PageIntro and the section slab.'],
        variants: [], example: {},
    },
    {
        id: 'dialog', name: 'Modal (dialog)', kind: 'component', status: 'active',
        summary: 'The one dialog of the site: a header slab with the title and the close square, a body that scrolls, a footer for the actions; a sheet at the bottom on a phone.',
        module: '/components/Modal.js', sheet: '/css/components/dialog.css',
        data: { shape: 'Modal({ open, onClose, title, children, footer, footerStart, showClose, size }) · ConfirmDialog({ … })', fields: { title: 'the header', children: 'the body', footer: 'the actions' } },
        useFor: ['A question or a form over the page.'],
        variants: [{ name: 'medium', class: 'dlg--md', when: 'a wider dialog' }], example: { title: 'Settings' },
    },
    {
        id: 'margin-pattern', name: 'Margin pattern', kind: 'component', status: 'active',
        summary: 'The personal pattern in the page margins of the home, the chat and the settings pages.',
        module: '/js/margin-pattern.js', sheet: '/css/components/margin-pattern.css',
        data: { shape: '<html data-margin-pattern="a".."h">', fields: { pattern: 'the person\'s choice' } },
        useFor: ['Set by the person in the home\'s settings; drawn in the margins.'],
        variants: [], example: {},
    },
    {
        id: 'notification-bell', name: 'NotificationBell', kind: 'component', status: 'active',
        summary: 'The bell in the top bar, its count and its list with inline actions.',
        module: '/components/NotificationBell.js', sheet: '/css/components/top-bar.css', classes: ['notif-bell', 'notif-bell-btn', 'notif-item'],
        data: { shape: 'NotificationBell({ t, onNavigate })', fields: { t: 'the translator', onNavigate: 'how a link opens' } },
        useFor: ['In the top bar of every signed-in page.'],
        variants: [], example: {},
    },
    {
        id: 'open-items-button', name: 'OpenItemsButton', kind: 'component', status: 'active',
        summary: 'The open items mark and count in the top bar.',
        module: '/components/OpenItemsButton.js', sheet: '/css/components/open-items.css', classes: ['open-items-btn'],
        data: { shape: 'OpenItemsButton({ t, onNavigate })', fields: { t: 'the translator', onNavigate: 'how the list opens' } },
        useFor: ['In the top bar of every signed-in page.'],
        variants: [], example: {},
    },
    {
        id: 'agent-consent', name: 'AgentConsent', kind: 'component', status: 'active',
        summary: 'An agent asking to connect: who it is, what it may do, and approve or deny.',
        module: '/components/AgentConsent.js', sheet: '/css/views/profile.css', classes: ['agc-card'],
        data: { shape: 'AgentConsent({ requests, onApprove, onDeny, busyCode, variant })', fields: { requests: 'the pending device requests' } },
        useFor: ['Where a person approves an agent (the home and the profile).'],
        variants: [], example: {}, note: PAGE_SHEET_NOTE,
    },
    {
        id: 'contact-card', name: 'ContactCard', kind: 'component', status: 'active',
        summary: 'The node\'s own people, as a card in the dashed aside.',
        module: '/components/ContactCard.js', sheet: '/css/views/landing.css', classes: ['ld-contact'],
        data: { shape: 'ContactCard()', fields: {} },
        useFor: ['The front page and the help page.'],
        variants: [], example: {}, note: PAGE_SHEET_NOTE,
    },
    {
        id: 'display-prefs-fields', name: 'DisplayPrefsFields', kind: 'component', status: 'active',
        summary: 'The region and time zone fields.',
        module: '/components/DisplayPrefsFields.js', sheet: '/css/views/profile.css', classes: ['pf-edit-select'],
        data: { shape: 'DisplayPrefsFields({ region, timezone, onChange })', fields: { region: 'the region', timezone: 'the time zone' } },
        useFor: ['The profile\'s settings.'],
        variants: [], example: {}, note: PAGE_SHEET_NOTE,
    },
    {
        id: 'inbox-link', name: 'InboxLink', kind: 'component', status: 'active',
        summary: 'A link that opens the inbox with a message addressed.',
        module: '/components/InboxLink.js', sheet: '/css/components/page-base.css',
        data: { shape: 'InboxLink({ to, subject, title, className, children })', fields: { to: 'the address', subject: 'the subject', className: 'the look the caller gives it' } },
        useFor: ['Wherever a person is invited to write to someone.'],
        variants: [], example: {}, note: 'It draws no look of its own: it is a link that wears the caller\'s class.',
    },
    {
        id: 'json-view', name: 'JsonView', kind: 'component', status: 'active',
        summary: 'A stored value shown as readable, coloured JSON.',
        module: '/components/JsonView.js', sheet: '/css/views/agents-detail.css', classes: ['pf-agd-json-block'],
        data: { shape: 'JsonValue({ value }) · JsonNode({ value })', fields: { value: 'any stored value' } },
        useFor: ['A record\'s raw value in the profile.'],
        variants: [], example: {}, note: PAGE_SHEET_NOTE,
    },
    {
        id: 'link-preview', name: 'LinkPreview', kind: 'component', status: 'active',
        summary: 'A card for a link in a message: its site, title and picture.',
        module: '/components/LinkPreview.js', sheet: '/css/views/inbox.css', classes: ['inbox-linkcard'],
        data: { shape: 'LinkPreview({ url, onDismiss }) · MessageLinkPreviews({ msg })', fields: { url: 'the link' } },
        useFor: ['Under a message that carries a link.'],
        variants: [], example: {}, note: PAGE_SHEET_NOTE,
    },
    {
        id: 'memory-embed', name: 'MemoryEmbed', kind: 'component', status: 'active',
        summary: 'A stored record shown inside a text.',
        module: '/components/MemoryEmbed.js', sheet: '/css/components/markdown.css', classes: ['md-mem-value'],
        data: { shape: 'MemoryEmbed({ spec })', fields: { spec: 'which record, and how' } },
        useFor: ['Inside a Markdown text that names a record.'],
        variants: [], example: {},
    },
    {
        id: 'mermaid', name: 'Mermaid', kind: 'component', status: 'active',
        summary: 'A diagram drawn from its text.',
        module: '/components/Mermaid.js', sheet: '/css/views/profile.css', classes: ['mmd'],
        data: { shape: 'Mermaid({ chart })', fields: { chart: 'the diagram\'s text' } },
        useFor: ['A diagram inside a text.'],
        variants: [], example: {}, note: PAGE_SHEET_NOTE,
    },
    {
        id: 'offer-card-view', name: 'Offer card parts', kind: 'component', status: 'unused',
        summary: 'An offer\'s badges, example and requirements.',
        module: '/components/offer-card-view.js', sheet: '/css/views/offers.css', classes: ['of-badges'],
        data: { shape: 'OfferBadges({ offer }) · OfferExample({ offer }) · OfferRequirements({ offer })', fields: { offer: 'the offer' } },
        useFor: ['The offers page and an offer\'s own page.'],
        variants: [], example: {}, note: "No routed page imports it today (the offers view draws its own). Kept until Jouni says keep or delete." 
    },
];
