/**
 * @file src/services/ui-library/entries-fields.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Catalogue entries for the field family of Settings & Controls: the field (Field), the text field (TextField) and the choice (Choice), and the family's older parts (the Form fields, the Select, the
 *   File drop, the Tag input, the Model picker). The Check line and the Field row sit in
 *   entries-settings-org.ts. The purpose half only; facts.generated.ts carries what the files say.
 * @structure FIELD_ENTRIES
 * @usage import { FIELD_ENTRIES } from './entries-fields.js';
 * @version-history
 *   v1.3.0 — 2026-09-27 — The options appcat added: Fields plain, beside, chapter, ruled, spaced, column,
 *     narrow (field, form-fields with their classes); TextField size glyph and mark, TextArea prompt,
 *     page, source, script (text-field); Select line; FileDrop ink, mark, browseLabel, chosen.
 *   v1.2.0 — 2026-09-27 — TextArea's indent and onSave, which the admin pages added (the script editor).
 *   v1.1.0 — 2026-09-27 — The entries field, text-field and choice, written from the headers of
 *     components/Field.js, TextField.js and Choice.js (the catalogue pass); form-fields, select-field,
 *     file-drop, tag-input and model-picker moved here unchanged from entries-settings.ts, with their ids.
 *   v1.0.0 — 2026-09-27 — Initial (Settings & Controls on components, the catalogue pass).
 */
import type { UiEntryWritten } from './types.js';

const FIELD_WORDS = 'label, hint, message, error, wide';
const FIELD_WORDS_MEANING = 'the field words: given a label, a hint or a message, the control stands in a Field (the row label over it, the grey hint and the message under it)';

export const FIELD_ENTRIES: UiEntryWritten[] = [
    {
        id: 'field', name: 'Field', kind: 'component', status: 'active',
        summary: 'The frame a form field stands in: the coral row label on top, the control, a grey hint under it, and the line the form says after it acted (green when done, coral when refused). Fields lays the fields of a form in one column, or two, three or four side by side; FormActions is the row of actions at the foot of the form. A control of the family given a label stands in a Field by itself. Fields also draws the app catalogue\'s forms: labels as plain bold ink words over underlined fields, labels at the left of their fields with a thin rule under each row, and the spacing of a form inside a chapter of an app\'s page.',
        module: '/components/Field.js', sheet: '/css/components/field.css',
        data: {
            shape: 'Field({ label, labelNote, hint, message, error, wide, invalid, group, named, id, labelId, hintId, children }) · Fields({ cols, plain, beside, chapter, ruled, spaced, column, narrow, children }) · FormActions({ end, apart, children }) · useFieldIds(id) · messageOf(message, error) · hasFieldWords(props) · inField(props, ids, control, named)',
            fields: {
                label: 'the row label: what the field holds',
                labelNote: 'a small typewriter word beside the label, outside its capitals: a count of characters',
                hint: 'a grey line under the control',
                message: 'what the form said after it acted: words, or the { text, error } the Settings pages keep',
                error: 'the message is a refusal: coral instead of green',
                wide: 'the field spans both columns of a two-column Fields',
                invalid: 'a required field left empty: the label in the danger colour',
                group: 'what is inside is a set (several Checks, a row of buttons): the frame is a group that the label names',
                named: 'for the family\'s controls: the set inside names itself by the label\'s id',
                id: 'the control\'s id, for the label to point at; pass it only when code reaches the element',
                'labelId, hintId': 'the ids of the label and the hint, when a control made them (useFieldIds)',
                children: 'the control, or the set of controls',
                cols: 'Fields: 2, 3 or 4 fields side by side (two or one on a narrow screen); one column without it',
                plain: 'Fields: the labels are plain bold words in ink, in their own case, over underlined bold fields with an italic grey placeholder (a dialog form of the app catalogue)',
                beside: 'Fields: each label 130px wide at the left of its field, a thin rule under each row (the app catalogue\'s Settings dialog)',
                chapter: 'Fields, with plain: a form inside a chapter of an app\'s page, its labels and fields spaced as that page spaces them; cols={2} stays two columns down to 900px, cols={3} is two wide fields and a short third',
                ruled: 'Fields, with plain chapter: a form opened in place under the heavy ink rule, its hints in the lighter grey (a tool\'s editor)',
                spaced: 'Fields, with plain chapter: each one-line field carries its own air above and under it (an app\'s About editor)',
                column: 'Fields, with plain: one column, every part 10px under the one above, a hint as the grey line under its field, a choice 260px wide at most',
                narrow: 'Fields: 520px wide at most, with air above and under it (a reviewer\'s name)',
                end: 'FormActions: the row stands at the right',
                apart: 'FormActions: the first thing at the left, the rest at the right (a hint beside the send action)',
                'useFieldIds, messageOf, hasFieldWords, inField': 'for a component author: the ids a field\'s parts share, a message in one shape, whether a control has field words, and standing a control in a Field when it has them',
            },
        },
        useFor: [
            'Around any field of a form on a Settings page. Give a control of the family its `label` instead; write Field by hand only around something that is not one of the family\'s controls (with `group` when what is inside is a set).',
            'Fields around the fields of a form, FormActions under them for the send action and a message about the whole form.',
        ],
        variants: [
            { name: 'wide', class: 'field--wide', prop: 'wide', when: 'a long field in a two-column form: it takes the whole row' },
            { name: 'invalid', class: 'field--invalid', prop: 'invalid', when: 'a required field the person left empty' },
            { name: 'label note', class: 'field-label-note', prop: 'labelNote', when: 'a count or a short word that belongs beside the label, such as how many characters a prompt has' },
            { name: 'with its buttons', class: 'field-line', prop: 'actions (on TextField)', when: 'a field and the buttons that act on it in one row: the field takes the room, the row wraps on a phone' },
            { name: 'group', prop: 'group', when: 'a set of controls under one label: several Checks, two tab rows' },
            { name: 'two columns', prop: 'cols={2} (Fields)', when: 'short fields side by side, one column under 1100px' },
            { name: 'three columns', prop: 'cols={3} (Fields)', when: 'three short fields in a row (an agent\'s crew), one column under 1100px' },
            { name: 'four columns', prop: 'cols={4} (Fields)', when: 'four short fields with their feet level (an offer\'s price), two under 1100px' },
            { name: 'plain labels', prop: 'plain (Fields)', when: 'a dialog form in the app catalogue: bold ink labels in their own case over underlined fields' },
            { name: 'labels beside', prop: 'plain beside (Fields)', when: 'settings rows: each label at the left of its field, a thin rule under the row' },
            { name: 'in a chapter', prop: 'plain chapter (Fields)', when: 'a form inside a chapter of an app\'s page: its Search wording, its ODPS defaults, its manage fields' },
            { name: 'opened under a rule', prop: 'plain chapter ruled (Fields)', when: 'a form opened in place under the heavy ink rule: the editor of a tool for sale' },
            { name: 'spaced', prop: 'plain chapter spaced (Fields)', when: 'one-line fields that each carry their own air: an app\'s About and Promote texts' },
            { name: 'one column', prop: 'plain column (Fields)', when: 'a short form in one column, parts 10px apart: a legal page\'s editor' },
            { name: 'narrow', prop: 'plain column narrow (Fields)', when: 'a form of one short field, 520px wide at most: a reviewer\'s name' },
            { name: 'actions at the right', prop: 'end (FormActions)', when: 'the send action stands at the right of the form' },
            { name: 'actions apart', prop: 'apart (FormActions)', when: 'a hint at the left and the send action at the right' },
        ],
        example: { label: 'Name', hint: 'Shown to the people you invite.', children: 'TextField value="Harbour Studio"' },
        note: 'It also wears css/components/form-fields.css: the column a field stands in (.og-field), Fields (.og-fields and its --2, --3, --4) and FormActions (.og-actions, --end, --apart) are the Form fields\' classes, kept because the admin writes them by hand (entry form-fields). Fields\' plain, beside, chapter, ruled, spaced, column and narrow came with appcat on 2026-09-27 and draw .og-fields--plain, --beside, --chapter, --ruled, --spaced, --column and --narrow in that sheet (their classes are named on the form-fields entry); they replace the old app catalogue\'s .modal-label and .modal-input, .settings-row, label.dtl-stat-label, .mz-form, .mk-author-form and .lg-editor. The message is the Note\'s message kind. It replaces the per-page wrappers of the Settings forms (ap-field, cp-field, ex-field, mc-field, pj-field, pf-dr-field, pf-or-field, sch-form-row, inbox-form-row, form-row, op-field, pf-edit-label and kin) and their containers and action rows (create-form, sch-form, agp-form, form-actions, pf-agd-form-actions, cp-form-doors and kin).',
    },
    {
        id: 'text-field', name: 'TextField', kind: 'component', status: 'active',
        summary: 'Where a person types: TextField is one line on an underline that turns coral on focus, TextArea several lines in a thin frame. Its options: an identifier in the typewriter face, a secret typed hidden with an eye at the right end that shows it, a search, a short or medium width, one mark centred (an app\'s icon), buttons in one row after it (in a thin dashed frame with `box`), and the underline in the danger colour when the form refused it. TextArea also draws a request to the person\'s AI with its send button beside it, a page\'s text in a framed typewriter box, a whole file\'s source in the heavy ink frame, and an extension\'s file in the thin ink frame.',
        module: '/components/TextField.js', sheet: '/css/components/text-field.css',
        data: {
            shape: `TextField({ value, onInput, onChange, onEnter, onEscape, onBlur, onFocus, onKeyDown, onPaste, onClick, placeholder, type, code, secret, showLabel, hideLabel, unmanaged, noManager, search, note, size, actions, box, invalid, min, max, step, maxLength, inputMode, autoComplete, spellCheck, name, list, required, disabled, readOnly, autoFocus, ariaLabel, title, id, inputRef, ${FIELD_WORDS} }) · TextArea({ value, onInput, onChange, onSend, onSave, onEscape, onBlur, onFocus, onKeyDown, onPaste, placeholder, rows, code, grow, indent, prompt, actions, page, source, script, invalid, maxLength, spellCheck, name, required, disabled, readOnly, autoFocus, ariaLabel, title, id, inputRef, ${FIELD_WORDS} })`,
            fields: {
                value: 'what the field holds',
                onInput: '(value, event) on every key',
                onChange: '(value, event) when the field is left changed',
                onEnter: 'TextField: (value, event) on Enter, not while an input method is composing',
                onEscape: '(event) on Escape; a search without it empties itself',
                onSend: 'TextArea: (value, event) on Ctrl+Enter or Cmd+Enter',
                onSave: 'TextArea: (value, event) on Ctrl+S or Cmd+S; the browser\'s own save of the page does not open',
                indent: 'TextArea: a script editor, where Tab puts two spaces in at the caret instead of leaving the field',
                onPaste: '(text, event) with the pasted words',
                'onBlur, onFocus, onClick': 'the value first, then the event (onBlur); the browser\'s event (the others)',
                onKeyDown: 'any other key; it runs first, and a preventDefault() in it stops Enter and Escape',
                type: 'text | number | url | email | time | date | password …',
                code: 'an identifier (a cron line, a key, an id): the typewriter face, no spelling check',
                secret: 'typed hidden, with the eye inside the right end that shows it; password managers keep out unless `autoComplete` says it is a real password',
                'showLabel, hideLabel': 'the eye\'s name while hidden and while shown',
                unmanaged: 'a key typed hidden without the eye; password managers keep out',
                noManager: 'shown as typed, and password managers keep out (a payout address)',
                search: 'a search field; `note` is the small count beside it (the Search line)',
                size: '\'short\' (at most 8rem: a number, a time) | \'medium\' (at most 16rem: a name, a tag) | \'glyph\' (one big mark centred in a small square: an app\'s icon; ready marks in `actions` stand beside it and wrap) | \'mark\' (one mark centred, a step larger, the field\'s whole width)',
                actions: 'buttons after the field in one row, which wraps on a phone; on TextArea, beside the field on its line',
                prompt: 'TextArea: a request to the person\'s AI, underlined and bold on the page\'s ground, its send button (in `actions`) beside it at the top',
                page: 'TextArea: a page\'s text written by hand (a legal page): the typewriter face in a framed box on the grey ground, 280px high at least',
                source: 'TextArea: a whole file\'s source to read and edit: the typewriter face in the heavy ink frame, 400px high at least and 60% of the window at most',
                script: 'TextArea: an extension\'s file: small typewriter letters in the thin ink frame, 160px high at least; \'long\' makes it 280px (a manifest)',
                box: 'that row inside the thin dashed frame (the Field row)',
                invalid: 'the underline or frame in the danger colour, and aria-invalid',
                rows: 'TextArea: its height in lines',
                grow: 'TextArea: grows with what is typed; a number caps it in pixels, true at 60% of the window',
                autoFocus: 'takes the focus when it appears',
                inputRef: 'a ref to the element, for a page that must reach it',
                'min, max, step, maxLength, inputMode, autoComplete, spellCheck, name, list, required, disabled, readOnly, placeholder, title': 'the browser\'s own attributes',
                ariaLabel: 'the field\'s name when it has no label',
                [FIELD_WORDS]: FIELD_WORDS_MEANING,
            },
        },
        useFor: [
            'Any typed value in a form: a name, an address, a number, a time, a key, a prompt.',
            'A search over a list (`search`, with `note` for how many it found), and a key or an address typed in place with the one action it takes (`box` and `actions`).',
        ],
        variants: [
            { name: 'short', class: 'text-field--short', prop: 'size="short"', when: 'a number or a time' },
            { name: 'medium', class: 'text-field--medium', prop: 'size="medium"', when: 'a name or a tag' },
            { name: 'secret', class: 'text-field-secret', prop: 'secret', when: 'a code or a password the person may want to see while typing' },
            { name: 'growing', class: 'text-area--grow', prop: 'grow (TextArea)', when: 'a message whose length is not known: the box follows what is typed up to its cap' },
            { name: 'code', prop: 'code', when: 'an identifier: a cron line, a memory key, a step id, JSON' },
            { name: 'key', prop: 'unmanaged', when: 'a key typed hidden that shows no eye, as the AI settings draw one' },
            { name: 'search', prop: 'search', when: 'a search over a list; with `note`, the count at its end' },
            { name: 'dashed box', prop: 'box', when: 'a key or a name typed in place with its one action, in the thin dashed frame' },
            { name: 'refused', prop: 'invalid', when: 'the form refused what is in it' },
            { name: 'script editor', prop: 'TextArea code indent onSave', when: 'a script a person writes and saves in place: Tab indents, Ctrl+S saves (the operator\'s Extensions page)' },
            { name: 'glyph', class: 'text-field--glyph', prop: 'size="glyph"', when: 'an app\'s icon: one mark in a small square, with ready marks beside it' },
            { name: 'mark', class: 'text-field--mark', prop: 'size="mark"', when: 'an app\'s icon in a form of full-width fields: one mark centred, a step larger' },
            { name: 'prompt', class: 'text-area--prompt', prop: 'TextArea prompt actions', when: 'a request a person writes to their AI, with the button that sends it beside the field' },
            { name: 'page', prop: 'TextArea page', when: 'a page\'s text written by hand, such as an app\'s privacy page' },
            { name: 'source', class: 'text-area--source', prop: 'TextArea source', when: 'a whole file\'s source to read or edit, such as an app\'s HTML' },
            { name: 'script', class: 'text-area--script', prop: 'TextArea script', when: 'one file of an extension or a library' },
            { name: 'long script', class: 'text-area--script-long', prop: 'TextArea script="long"', when: 'a longer file of the same kind: a manifest' },
        ],
        example: { label: 'Name', value: 'Harbour Studio', hint: 'Shown to the people you invite.' },
        note: 'The fields themselves are the Form fields\' classes in form-fields.css: .og-input (the underline), .og-textarea (the frame), the code cuts (.og-input--code, .og-textarea--code) and the refused ones (.og-input--invalid, .og-textarea--invalid). `search` with a `note` draws the Search line (search-line.css), `box` the Field row (field-row.css), `actions` the field line (field.css). The secret\'s eye moved in from the apps form (.ap-secret, .ap-secret-eye); the short width is the middle of the page copies it replaces (wp-num, pf-or-input-sm, bp-field--narrow, pf-agd-tag-add-input), the medium width is ct-in--short\'s. With appcat on 2026-09-27 came size \'glyph\' and \'mark\' (the old app catalogue\'s #app-icon and #detail-icon-input) and TextArea\'s prompt with actions (its #detail-ai-input in .dtl-ai-row), page (.lg-textarea; its class .og-textarea--page is in form-fields.css), source (#source-code) and script (the extension editor\'s .cx-code).',
    },
    {
        id: 'choice', name: 'Choice', kind: 'component', status: 'active',
        summary: 'Picking one of a few settings, or several: by default a row of tabs (underlined capitals, the chosen one on the sun), in the tile, filter or fold tone where a page had that look; or boxed answers, each a name with a line under it, in a grid of two, three or four columns, with a radio dot in each box if asked. A press on the chosen answer can take it back.',
        module: '/components/Choice.js', sheet: '/css/components/choice.css',
        data: {
            shape: `Choice({ options, value, onChange, multi, clearable, tone, boxed, cols, dot, name, disabled, ariaLabel, id, ${FIELD_WORDS}, children })`,
            fields: {
                options: '[{ value, label, hint, title, disabled, count, attention }] or [value, label] pairs; a value may be null',
                value: 'the chosen value; with `multi`, the array of the chosen ones',
                onChange: '(value, event); with `multi`, (values, event)',
                multi: 'several can be on at once (each answer says aria-pressed)',
                clearable: 'a press on the chosen answer takes it back: onChange with \'\'',
                tone: '\'tile\' | \'filter\' | \'fold\': the Tabs\' tones, for the tab row',
                boxed: 'the answers are boxes, each a name with a line under it (the option\'s hint)',
                cols: 'with `boxed`: 2 | 3 | 4 boxes side by side (fewer under 1100px, one under 700px); without it they fill 12rem columns',
                dot: 'with `boxed`: a radio dot in each box, keeping the browser\'s keys; `name` groups the dots',
                'option.attention': 'the risky answer in the tab\'s attention tone (tab row only)',
                'option.count': 'a small tally inside the tab',
                disabled: 'nothing can be picked now',
                ariaLabel: 'the row\'s name when it has no label',
                children: 'stand after the answers in the same row: a field for an answer of one\'s own',
                [FIELD_WORDS]: `${FIELD_WORDS_MEANING}; the label names the group of answers`,
            },
        },
        useFor: [
            'A setting with a few fixed answers that are all worth seeing at once: how long a key lives, who may join, how often.',
            'Boxed, when each answer needs a line that explains it: the shape of a new agent, the kind of a schedule. A row that switches what a page or a list shows is the Tabs, not a Choice.',
        ],
        variants: [
            { name: 'tabs', prop: 'no tone, no boxed', when: 'one of a few short answers: underlined capitals, the chosen one on the sun (the Tabs\' look)' },
            { name: 'tile', prop: 'tone="tile"', when: 'answers that are framed tiles: a background pattern, an access level' },
            { name: 'filter', prop: 'tone="filter"', when: 'small framed words: presets such as a schedule\'s cron lines' },
            { name: 'fold', prop: 'tone="fold"', when: 'coral typewriter words' },
            { name: 'several', prop: 'multi', when: 'more than one answer can be on: the groups a notice breaks through, the scopes of a key' },
            { name: 'boxed', class: 'choice--boxed', prop: 'boxed', when: 'each answer is a name with a line under it' },
            { name: 'two columns', class: 'choice--cols-2', prop: 'boxed cols={2}', when: 'two boxes side by side' },
            { name: 'three columns', class: 'choice--cols-3', prop: 'boxed cols={3}', when: 'three boxes side by side (a schedule\'s kinds), two under 1100px' },
            { name: 'four columns', class: 'choice--cols-4', prop: 'boxed cols={4}', when: 'four boxes side by side (a new agent\'s shape), two under 1100px' },
            { name: 'with a dot', class: 'choice-dot', prop: 'boxed dot', when: 'a boxed answer that shows its radio dot, as a calibration\'s options do' },
        ],
        example: { label: 'Lifetime', value: '168', options: [['72', '3 days'], ['168', '7 days'], ['720', '30 days']] },
        note: 'Its tab rows are the page family\'s Tabs (components/Tabs.js, kind choice or toggle; their look is tab-row.css and poster.css .poster-tab), so a row of answers has one keyboard and one look wherever it stands. Its boxed answers wear the Choice tile shape of poster.css (.poster-choice, entry choice-shape), which stays as it is; choice.css holds only their grid and the dot\'s layout. It replaces the .pf-tabs rows used as a setting, the og-choice group, and the agp-choices, sc-choices and cal-opts grids (Jouni\'s decisions "Choice" and "Question box").',
    },
    // The family's older entries, moved here unchanged from entries-settings.ts (which passed its
    // length limit), with their ids: the Form fields, the Select, the File drop, the Tag input and the
    // Model picker. The Check line and the Field row stay in entries-settings-org.ts.
    {
        id: 'form-fields', name: 'Form fields', kind: 'component', status: 'active',
        summary: 'The fields of a settings page: one column, or two, three or four side by side, each a coral label over an underlined input or a framed text area, and the row of actions under them. In Settings & Controls the Field family draws these classes: Fields and Field (.og-fields, .og-field), FormActions (.og-actions), TextField (.og-input) and TextArea (.og-textarea). The admin still writes them by hand, which is why they keep their names and this entry has no module. The sheet also holds the app catalogue\'s form faces, which Fields draws: plain bold ink labels over underlined bold fields, labels beside their fields in ruled rows, and the spacing of a form inside a chapter of an app\'s page.',
        module: null, sheet: '/css/components/form-fields.css', classes: ['og-fields', 'og-field', 'og-label', 'og-input', 'og-input--code', 'og-textarea', 'og-actions'],
        data: { shape: '<div class="og-fields"><label class="og-field"><span class="og-label">Name</span><input class="og-input"></label></div><div class="og-actions">…</div> (by hand, in the admin) · Fields({ cols, plain, beside, chapter, ruled, spaced, column, narrow }) · Field({ label }) · TextField({ label }) · TextArea({ label, page }) · FormActions({ end, apart }) (in Settings & Controls and the app catalogue)', fields: { label: 'what the field holds', input: 'one line', textarea: 'several lines', actions: 'the row under the fields: the send action, the quieter ones, a message', 'plain, beside, chapter, ruled, spaced, column, narrow': 'Fields\' app catalogue faces (entry field says what each one does)', page: 'TextArea: a page\'s text in the framed typewriter box on the grey ground' } },
        useFor: ['A form on a tab page. In Settings & Controls, through the Field family (entries field and text-field); by hand only in the admin.'],
        variants: [
            { name: 'two columns', class: 'og-fields--2', prop: 'Fields cols={2}', when: 'short fields side by side (one column on a phone)' },
            { name: 'three columns', class: 'og-fields--3', prop: 'Fields cols={3}', when: 'three short fields in a row (an agent\'s crew), one column under 1100px' },
            { name: 'four columns', class: 'og-fields--4', prop: 'Fields cols={4}', when: 'four short fields with their feet level (an offer\'s price), two under 1100px' },
            { name: 'code', class: 'og-input--code', prop: 'TextField code', when: 'a field that holds an identifier (a cron line, a key, an id): the typewriter face' },
            { name: 'code, many lines', class: 'og-textarea--code', prop: 'TextArea code', when: 'a JSON editor or a prompt in the typewriter face' },
            { name: 'refused', class: 'og-input--invalid', prop: 'TextField invalid', when: 'the form refused what is in the field: the underline in the danger colour' },
            { name: 'actions at the right', class: 'og-actions--end', prop: 'FormActions end', when: 'the send action stands at the right' },
            { name: 'actions apart', class: 'og-actions--apart', prop: 'FormActions apart', when: 'a hint at the left, the send action at the right' },
            { name: 'plain labels', class: 'og-fields--plain', prop: 'Fields plain', when: 'a dialog form of the app catalogue: bold ink labels in their own case, underlined bold fields, an italic grey placeholder' },
            { name: 'labels beside', class: 'og-fields--beside', prop: 'Fields plain beside', when: 'settings rows: each label 130px wide at the left of its field, a thin rule under the row' },
            { name: 'in a chapter', class: 'og-fields--chapter', prop: 'Fields plain chapter', when: 'a form inside a chapter of an app\'s page, spaced as that page spaces its fields' },
            { name: 'opened under a rule', class: 'og-fields--ruled', prop: 'Fields plain chapter ruled', when: 'a form opened in place under the heavy ink rule, its hints in the lighter grey' },
            { name: 'spaced', class: 'og-fields--spaced', prop: 'Fields plain chapter spaced', when: 'one-line fields that each carry their own air above and under them' },
            { name: 'one column', class: 'og-fields--column', prop: 'Fields plain column', when: 'a short form in one column, every part 10px under the one above' },
            { name: 'narrow', class: 'og-fields--narrow', prop: 'Fields narrow', when: 'a form of one short field, 520px wide at most' },
            { name: 'a page\'s text', class: 'og-textarea--page', prop: 'TextArea page', when: 'a page written by hand: the typewriter face in a framed box on the grey ground, 280px high at least' },
        ],
        example: { fields: ['Name', 'Description'] },
        note: 'Moved out of views/organism.css on 2026-09-25. Since 2026-09-26 the Field family (components/Field.js, TextField.js) writes these classes for every Settings form, with its own options in field.css and text-field.css; the og-label here is the admin\'s, the Field\'s label is the row label (.poster-label). On 2026-09-27 appcat added .og-fields--plain, --beside, --chapter, --ruled, --spaced, --column and --narrow (Fields plain, beside, chapter, ruled, spaced, column, narrow) and .og-textarea--page (TextArea page); they replace the old app catalogue\'s .modal-label and .modal-input, .settings-row, label.dtl-stat-label, .mz-form, .od-form, .mk-author-form, .lg-editor and .lg-textarea, and only appcat draws them.',
    },
    {
        id: 'select-field', name: 'Select', kind: 'component', status: 'active',
        summary: 'A drop-down: the browser\'s select in an ink frame on the page ground, its words in the showroom face, as wide as its place; the frame turns coral while it has the focus. With `line` it has no frame: the ink line under it, bold words and a small grey arrow at its right end. The options are data; given a label it stands in a Field.',
        module: '/components/Select.js', sheet: '/css/components/select-field.css',
        data: {
            shape: 'Select({ value, onChange, options, placeholder, placeholderDisabled, fit, line, invalid, attention, disabled, required, name, ariaLabel, title, onFocus, onBlur, id, label, hint, message, error, wide })',
            fields: {
                value: 'the chosen value (\'\' for none)', onChange: '(value, event) on a pick',
                options: '[value, label] pairs, { value, label, disabled, title } objects or plain words; a { group, options } entry draws a named group',
                placeholder: 'a first option with the value \'\' ("–", "Choose…")', placeholderDisabled: 'that first option cannot be picked again once something is chosen',
                fit: 'as wide as its words (at least 9rem), not its column', invalid: 'the frame in the danger colour, and aria-invalid',
                line: 'no frame: the ink line under it, bold words, a small grey arrow at the right end, at most 340px wide; with `fit` as wide as its words and at least 150px',
                attention: 'coral on the pale coral ground while something is chosen: a choice that widens what an act reaches',
                'disabled, required, name, title, onFocus, onBlur': 'the browser\'s own', ariaLabel: 'its name when it has no label',
                'label, hint, message, error, wide': 'the field words: given one, it stands in a Field with the row label over it',
            },
        },
        useFor: ['One choice out of a short fixed list: a role, an order, a provider, how often.'],
        variants: [
            { name: 'fit', class: 'select-field--fit', prop: 'fit', when: 'in a line or beside a label, as wide as its words' },
            { name: 'refused', class: 'select-field--invalid', prop: 'invalid', when: 'the form refused the choice, or a required one is empty' },
            { name: 'attention', class: 'select-field--attention', prop: 'attention', when: 'a choice that widens what an act reaches, while it is set: a broadcast\'s audience' },
            { name: 'line', class: 'select-field--line', prop: 'line', when: 'a choice on an app\'s page in the app catalogue: the skill to attach, where the visitors come from (with `fit`)' },
        ],
        example: { label: 'Role', value: 'member', options: [['member', 'Member'], ['editor', 'Editor'], ['owner', 'Owner']] },
        note: 'Built on 2026-09-25 with the look most Settings tabs drew for a drop-down (the og-input selects of twelve tabs); every Settings select wears it. Since 2026-09-26 it is components/Select.js, with the options as data, the fit, refused and attention cuts, and optgroups; it replaces select-field written by hand, mem-vis-select, pf-or-select--sm and pf-edit-select. `line` came with appcat on 2026-09-27 and replaces the old app catalogue\'s select.modal-input on an app\'s page (and .vis-geo-select with `fit`); inside Fields `plain` a Select takes the same look from form-fields.css without it.',
    },
    {
        id: 'file-drop', name: 'FileDrop', kind: 'component', status: 'active',
        summary: 'Choosing files to upload: a dashed area with a big arrow and two lines (drop here, or click), coral while a file is over it or chosen, and under it one row per chosen file with its mark, the name it is stored under, its size and the mark that takes it off. Its other cuts: the browser\'s file field in the Text field look, an action link that opens the file window, or only the hidden field. The app catalogue\'s face (`ink`) is a heavy dashed ink frame on the card ground, coral while a file is over it, its words in ink one under another, a framed "Browse files" part and the chosen file\'s name under them.',
        module: '/components/FileDrop.js', sheet: '/css/components/file-drop.css',
        data: {
            shape: 'FileDrop({ onFiles, onChange, items, onRename, onRemove, multiple, accept, disabled, iconOf, dropLabel, orLabel, removeLabel, plain, button, soft, hidden, ink, mark, browseLabel, chosen, inputRef, ariaLabel, id, label, hint, message, error, wide })',
            fields: {
                onFiles: '(files) with the File objects dropped or chosen; the same file can be chosen again after',
                onChange: '(event) instead of onFiles, for a page that reads the pick itself',
                items: 'the chosen files as [{ file, key }]: the rows under the area',
                onRename: '(index, key): the stored name becomes a field', onRemove: '(index): adds the mark that takes a file off',
                'multiple, accept': 'the browser\'s own: several files, which kinds', disabled: 'no file can be taken now',
                iconOf: '(file) → the mark before a row', dropLabel: 'the first line (default "Drop files here")',
                orLabel: 'the second line (default "or click to browse"); null hides it', removeLabel: 'the remove mark\'s name',
                plain: 'no area: the browser\'s file field in the Text field look, in a form of other fields',
                button: 'words: an action link that opens the file window; `soft` for its lower-case tone',
                hidden: 'only the hidden file field; the page\'s own button opens it through `inputRef`',
                ink: 'the app catalogue\'s face: the heavy dashed ink frame on the card ground, coral while a file is dragged over it, the words in ink one under another',
                mark: 'the mark in place of the big arrow (a page mark for an HTML file)',
                browseLabel: 'the words of the framed "Browse files" part inside the area; the whole area stays the one button',
                chosen: 'the chosen file\'s name, a line under the words; with `ink`, \'\' keeps that line\'s room while nothing is chosen',
                inputRef: 'a ref to the file field', ariaLabel: 'the area\'s name',
                'label, hint, message, error, wide': 'the field words: given one, it stands in a Field with the row label over it',
            },
        },
        useFor: ['Before an upload, when a person picks one file or several and names where each is stored.', 'One file among the other fields of a form (plain), or an import that starts from one press (button, hidden).'],
        variants: [
            { name: 'dragover', class: 'dragover', when: 'a file is dragged over the area' },
            { name: 'has-file', class: 'has-file', prop: 'items', when: 'at least one file is chosen' },
            { name: 'closed', class: 'is-off', prop: 'disabled', when: 'the area cannot take a file now' },
            { name: 'plain', prop: 'plain', when: 'one file in a form with other fields' },
            { name: 'button', prop: 'button', when: 'an import that starts with a press on an action link' },
            { name: 'hidden', prop: 'hidden', when: 'the page\'s own button, elsewhere, opens the file window' },
            { name: 'ink', class: 'file-dropzone--ink', prop: 'ink', when: 'a drop area outside Settings & Controls, in the app catalogue\'s face: the Add dialog\'s HTML file' },
            { name: 'with a browse part', class: 'file-drop-browse', prop: 'browseLabel', when: 'a drop area that also shows a framed "Browse files" part, for a person who does not drag' },
            { name: 'chosen', class: 'file-drop-chosen', prop: 'chosen', when: 'one file is taken and its name stands under the words instead of a row' },
        ],
        example: { multiple: true, items: [{ file: 'notes.txt', key: 'docs/notes.txt' }, { file: 'plan.md', key: 'docs/plan.md' }] },
        note: 'Moved unchanged out of views/profile.css on 2026-09-25 (the memory tab\'s FileUploadForm). Since 2026-09-26 it is components/FileDrop.js, which also took the apps form\'s file field (ap-file) and the hidden inputs pages opened with their own buttons (pf-hidden, pj-hidden-input, pf-agd-hidden-input, pk-file). The sheet still holds the old names .pf-upload-icon and .pf-file-icon, which the component no longer writes (it writes .file-drop-arrow and .file-drop-mark). `ink`, `mark`, `browseLabel` and `chosen` came with appcat on 2026-09-27 and replace the old app catalogue\'s #drop-zone, its browse button and .drop-zone-selected; the ink face\'s rules are not scoped to the Settings root (.pf), because the catalogue is not in it.',
    },
    {
        id: 'tag-input', name: 'TagInput', kind: 'component', status: 'active',
        summary: 'A field that holds a list of words as tags: the tags so far, each a Tag with its remove mark, and the underlined Text field after them in one row that wraps. Enter or a comma adds the word, Backspace in an empty field takes the last one off, leaving the field adds what is in it, Escape empties it.',
        module: '/components/TagInput.js', sheet: '/css/components/tag-input.css',
        data: {
            shape: 'TagInput({ tags, onChange, onAdd, onRemove, placeholder, lowercase, adder, addLabel, whole, removeLabel, disabled, ariaLabel, id, label, hint, message, error, wide })',
            fields: {
                tags: 'the words so far', onChange: '(tags) with the new list',
                'onAdd, onRemove': '(tag): instead of onChange, when each change is a save of its own',
                placeholder: 'the empty field’s words (default "Add…")', lowercase: 'a tag is kept in small letters',
                adder: 'a + button after the field, for a person who does not know Enter adds',
                addLabel: 'the field stays closed behind a "+ {addLabel}" action beside the tags until pressed; Escape closes it again',
                whole: 'a press anywhere on a tag takes it off', removeLabel: 'the remove mark’s name and tooltip',
                disabled: 'no tag can be added or taken off', ariaLabel: 'the set’s name when it has no label',
                'label, hint, message, error, wide': 'the field words: given one, it stands in a Field whose label names the set',
            },
        },
        useFor: ['A short list of free words a person types: an organism’s interests, a contact’s tags, a file’s tags, an agent’s tags.'],
        variants: [
            { name: 'lowercase', prop: 'lowercase', when: 'tags that are keys, such as a file’s tags' },
            { name: 'with a + button', prop: 'adder', when: 'a form where Enter is not the known way to add' },
            { name: 'closed', prop: 'addLabel', when: 'a strip of tags where adding is the rarer act: an agent’s card' },
            { name: 'whole tag removes', prop: 'whole', when: 'small tags where the x alone is too small a target' },
        ],
        example: { label: 'Interests', tags: ['design', 'ferries'] },
        note: 'Moved out of views/profile.css on 2026-09-25 (the organisms’ framed tag box). Since 2026-09-26 it is components/TagInput.js (views/profile/shared.js re-exports it), with the tag fields of Contacts, the memory file form and an agent’s card as its options. The sheet still holds the old framed box (.pj-taginput, .pj-tag, .pj-taginput-field), which no page draws any more.',
    },
    {
        id: 'model-picker', name: 'ModelList, ModelPicker', kind: 'component', status: 'active',
        summary: 'A framed catalogue of AI models: a search field across the top, the recommended group, one row per model (name and id, a trait or a note, the price, the context), the chosen one on the sun, a taken one dimmed, and a line with "show all". ModelPicker is the classic AI settings\' whole control: a short chat list is a drop-down, a long or audio one this list with the chosen model above it, a way to clear it and a field for a model id the catalogue does not list.',
        module: '/components/ModelPicker.js', sheet: '/css/components/model-picker.css',
        data: {
            shape: 'ModelList({ models, recommended, value, taken, onPick, describe, match, query, onQuery, showAll, onShowAll, disabled, off, searchLabel, recommendedLabel, noMatchLabel, showAllLabel, facts, head, foot, id, label, hint, message, error, wide }) · ModelPicker({ value, onChange, models, modality, allowNone, allowCustom, isOpenRouter, disabled, noneLabel, id, label, hint, message, error, wide }) · SELECT_THRESHOLD',
            fields: {
                models: 'the pool of models', recommended: 'what shows before a search (the first 8 when not given)',
                value: 'the chosen id', taken: 'ids that cannot be picked again', onPick: '(model) on a press on a row',
                describe: '(model) → { name, trait, note, price, context, href, hrefLabel }: what a row says; the trait column (words) or the note column (typewriter) stands only when its key is there; href adds the ↗ to the model\'s page',
                match: '(model, query) → whether a row matches the search',
                'query, onQuery, showAll, onShowAll': 'the search and "show all", when the page keeps them; otherwise the list keeps its own',
                disabled: 'the rows cannot be pressed', off: 'dimmed, the search closed: nothing to pick yet',
                'searchLabel, recommendedLabel, noMatchLabel': 'the words of the search, the group heading and the empty line',
                showAllLabel: 'words, or (n) → words, for "show all"', facts: 'the line beside "show all"',
                'head, foot': 'what stands inside the frame above the search and under the list',
                onChange: 'ModelPicker: (id) on a pick, a clear (\'\') or a typed id',
                modality: 'ModelPicker: \'chat\' | \'vision\' | \'transcription\' | \'speech\'',
                'allowNone, allowCustom, isOpenRouter, noneLabel': 'ModelPicker: a way to clear the choice, a field for an unlisted id, rows that link to openrouter.ai, the words for no model',
                SELECT_THRESHOLD: 'at or below this many chat models (25) ModelPicker draws the Select',
                'label, hint, message, error, wide': 'the field words: given one, it stands in a Field with the row label over it',
            },
        },
        useFor: ['Choosing the AI model for a role or a test, under the row that names it.'],
        variants: [
            { name: 'on', class: 'is-on', prop: 'value', when: 'the chosen model' },
            { name: 'taken', class: 'is-taken', prop: 'taken', when: 'a model that is already in the list' },
            { name: 'off', class: 'model-picker--off', prop: 'off', when: 'nothing can be picked yet (no key): dimmed' },
            { name: 'with a link', class: 'model-picker-row--link', prop: 'describe → href', when: 'each row links to the model\'s own page' },
            { name: 'short list', prop: 'ModelPicker with 25 chat models or fewer', when: 'the Select, which a short list reads best in' },
        ],
        example: { value: 'anthropic/claude-sonnet-4.5', models: [{ id: 'anthropic/claude-sonnet-4.5', name: 'Claude Sonnet 4.5' }, { id: 'mistralai/mistral-small-3.2', name: 'Mistral Small 3.2' }] },
        note: 'Moved on 2026-09-25 from the AI page (ai-pick) and the calibrator (cal-pick), which drew it one way. On 2026-09-26 the three pickers of Settings became components/ModelPicker.js with the rows as data: ModelList for the AI page\'s roles and a calibration\'s models, ModelPicker for the classic AI settings (it replaces views/profile/openrouter/model-picker.js, deleted), whose chosen-value line, link column and own-id row keep their layout in this sheet.',
    },
];
