/**
 * @file src/services/ui-library/entries-kit.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Catalogue entries for the kit's core parts of Settings & Controls: the action link and its slab (Action), the tag and the row label (Mark), the note (Note), the object box (Box), the avatar (Avatar), the roads (Roads) and the figure (Figure). The purpose half only; facts.generated.ts carries what the
 *   files say.
 * @structure KIT_ENTRIES
 * @usage import { KIT_ENTRIES } from './entries-kit.js';
 * @version-history
 *   v1.1.0 — 2026-09-27 — The seven kit components: action-component, mark, note, box, avatar, roads, figure;
 *     figure-strip, facts, setting-box, code-block, form-message and loading-mark moved in from
 *     entries-settings.ts, rewritten to the kit calls that draw them.
 *   v1.0.0 — 2026-09-27 — Initial (Settings & Controls on components, the catalogue pass).
 */
import type { UiEntryWritten } from './types.js';

export const KIT_ENTRIES: UiEntryWritten[] = [
    {
        id: 'action-component', name: 'Action', kind: 'component', status: 'active',
        summary: 'Every way on a page offers, as one component: the action link (ink-underlined words), the loud action (the dark slab with the sun shadow), the square icon button, a copy that says "Copied" for two seconds, and the row the actions of a place stand in.',
        module: '/components/Action.js', sheet: '/css/poster.css',
        // It has no sheet of its own: it wears the action, slab and icon shapes of poster.css (entries 'action', 'slab', 'icon').
        classes: ['poster-action', 'poster-action--small', 'poster-action--lower', 'poster-action--row', 'poster-action--more', 'poster-action--quiet',
            'poster-action--back', 'poster-action--text', 'poster-action--danger', 'poster-action--notice', 'poster-action--jump',
            'poster-slab', 'poster-slab--large', 'poster-slab--control', 'poster-slab--danger', 'poster-icon', 'poster-icon--small'],
        data: {
            shape: 'Action({ small, soft, row, tone, href, newTab, noReferrer, download, copy, copiedLabel, copiedTitle, onCopied, onClick, disabled, title, ariaLabel, pressed, expanded, busy, type, form, id, role, onMouseEnter, onFocus, children }) · Loud({ control, large, danger, …the same press props }) · Icon({ small, pressed, label, title, copy, copiedLabel, onClick, …the same press props, children }) · Actions({ under, end, children })',
            fields: {
                small: 'the Settings size: smaller, with a thinner line', soft: 'a softer way on: lower-case words ("Show 13 more", "Copy ref")',
                row: 'at the end of a dense row: smaller still',
                tone: 'danger (it removes or revokes) | more (show more of a list, open a thing by its name) | text (a plain grey word) | quiet (a small action in a side column) | back (the way back) | notice (small coral typewriter words) | jump (the jump to the latest message) | link (a coral word inside a sentence or a fact\'s value, in the words\' own letters)',
                href: 'the action is a link; newTab opens it beside, noReferrer tells that address nothing, download makes it a file link',
                copy: 'the text a press copies; the action says copiedLabel (else "Copied") for two seconds, copiedTitle as its tooltip',
                onClick: 'what a press does', disabled: 'it cannot be pressed now', pressed: 'it stays pressed (aria-pressed; an Action on the pale coral ground)',
                expanded: 'it opens something under it (aria-expanded)', busy: 'it is working (aria-busy)',
                form: 'a submit that stands outside its form names the form (a dialog footer)', onMouseEnter: 'prepares the work while the pointer comes to it (with onFocus for the keyboard)',
                control: 'Loud: a 44px block in a row of controls', large: 'Loud: the home\'s large door', danger: 'Loud: an act that cannot be undone, coral with an ink shadow',
                label: 'Icon: the name a screen reader says and the tooltip', children: 'the words, or the Icon\'s mark',
                under: 'Actions: the row at the foot of an opened panel, with space above it', end: 'Actions: the row stands at the right',
            },
        },
        useFor: ['Every button and link on a Settings & Controls page: the page passes the words, what happens and named options, and never writes a class.',
            'Loud for the one action a place is for; Action for the other ways on; Icon for a mark without words; Actions for the row that holds them.'],
        variants: [
            { name: 'action', prop: 'Action', class: 'poster-action', when: 'a way on: ink-underlined words in capitals' },
            { name: 'small', prop: 'small', class: 'poster-action--small', when: 'a way on in a Settings page head, section or row' },
            { name: 'soft', prop: 'soft', class: 'poster-action--lower', when: 'with small: lower-case words for a softer way on' },
            { name: 'row', prop: 'row', class: 'poster-action--row', when: 'with small: at the end of a dense row' },
            { name: 'danger', prop: 'tone="danger"', class: 'poster-action--danger', when: 'it removes or revokes: coral words and line' },
            { name: 'more', prop: 'tone="more"', class: 'poster-action--more', when: 'more of a list: coral typewriter letters' },
            { name: 'text', prop: 'tone="text"', class: 'poster-action--text', when: 'a plain grey word (Listen, Not now)' },
            { name: 'quiet', prop: 'tone="quiet"', class: 'poster-action--quiet', when: 'a small action in a side column' },
            { name: 'back', prop: 'tone="back"', class: 'poster-action--back', when: 'the way back to where a person came from' },
            { name: 'notice', prop: 'tone="notice"', class: 'poster-action--notice', when: 'a question under a notice, small coral typewriter words' },
            { name: 'jump', prop: 'tone="jump"', class: 'poster-action--jump', when: 'the jump to the latest message: a small ink block with a sun shadow' },
            { name: 'link', prop: 'tone="link"', when: 'a coral word inside a sentence or a value (the crumb link, .og-crumb-link in crumb-trail.css)' },
            { name: 'pressed', prop: 'pressed', class: 'is-on', when: 'it stays pressed while what it does is on' },
            { name: 'copy', prop: 'copy', class: 'copied', when: 'it copies a text and says so for two seconds, in the success colour' },
            { name: 'loud', prop: 'Loud', class: 'poster-slab', when: 'the one action a place is for: the dark slab with the sun shadow' },
            { name: 'loud control', prop: 'Loud control', class: 'poster-slab--control', when: 'a 44px slab in a row of controls (Send, a dialog\'s Save)' },
            { name: 'loud large', prop: 'Loud large', class: 'poster-slab--large', when: 'the home\'s large door' },
            { name: 'loud danger', prop: 'Loud danger', class: 'poster-slab--danger', when: 'an act that cannot be undone: coral with an ink shadow' },
            { name: 'icon', prop: 'Icon', class: 'poster-icon', when: 'a mark without words in a square thin ink frame' },
            { name: 'icon small', prop: 'Icon small', class: 'poster-icon--small', when: 'the 28px square everywhere but the composer' },
            { name: 'row of actions', prop: 'Actions', when: 'the actions of a place in one line, wrapping on a phone (.og-doors); under at the foot of an opened panel, end at the right' },
        ],
        example: { small: true, soft: true, copy: 'aimeat_skill_get aimeat-writing', copiedLabel: 'Copied', children: 'Copy the request' },
        note: 'It has no sheet of its own: its look is the action, slab and icon shapes of css/poster.css (entries \'action\', \'slab\' and \'icon\'), which the whole site and the app catalogue draw from, so a theme reaches all of them. Its classes here narrow poster.css to those three shapes. The link tone wears .og-crumb-link (crumb-trail.css) and Actions wears .og-doors.',
    },
    {
        id: 'mark', name: 'Mark', kind: 'component', status: 'active',
        summary: 'The small marks a page puts beside a thing: a tag in a thin ink frame in the typewriter face, a status, a count, a time, the row label in small coral capitals, and code in a line or a block.',
        module: '/components/Mark.js', sheet: '/css/components/mark.css',
        data: {
            shape: 'Mark({ kind, tone, small, title, onRemove, removeLabel, removeGlyph, whole, onClick, expanded, presence, away, explains, live, children }) · Marks({ children }) · Label({ htmlFor, block, children }) · Code({ block, scroll, tall, blurred, change, children })',
            fields: {
                kind: 'tag (the default: a kind, a version, a role, a relation) | status (a state) | count (a small number) | time (when it happened)',
                tone: 'tag: sun (the chosen one) | coral (the one to notice) | ink (yours) | dim (it counts nothing yet) | fine (the success colour); status: fine | attention | danger | off; count: waiting (something waits for the person) | tally (only how many)',
                small: 'count: the small one that sits on an icon', title: 'the tooltip',
                onRemove: 'adds the remove mark after the name (removeGlyph, ✗ by default; removeLabel for a screen reader); whole makes the whole tag the button',
                onClick: 'the tag is a button (the visibility tag); expanded says it opens a list under it',
                presence: 'online | idle …: an agent\'s tag with its status dot after the name; away is the coral word while it is away',
                explains: 'its tooltip says why: the help pointer', live: 'a small green square before the words: a connection that works',
                children: 'the words',
                Marks: 'a row of tags', Label: 'the row label over a field, a column or a box; block stands it on its own line, htmlFor ties it to a field',
                Code: 'an identifier in a line; block for lines of code or a prompt to copy (scroll after 200px, or "medium" 300px, "large" 400px, "page" 32rem; tall after 24rem; change = added | removed for a draft\'s diff); blurred for a secret until it is shown',
            },
        },
        useFor: ['A word or a number beside a name that says what kind it is, what state it is in, how many or when.', 'The label over a value, and a line or a block of code a person reads exactly.'],
        variants: [
            { name: 'tag', prop: 'kind="tag"', when: 'a kind, a version, a role (.poster-chip); tone sun, coral, ink or dim' },
            { name: 'fine tag', prop: 'tone="fine"', class: 'poster-chip--fine', when: 'a tag in the success colour: a knowledge hit, a step for an agent' },
            { name: 'status', prop: 'kind="status"', when: 'a state: fine, attention, danger or off (.poster-status)' },
            { name: 'count', prop: 'kind="count"', when: 'a small number: waiting (something waits) or tally (only how many)' },
            { name: 'time', prop: 'kind="time"', when: 'when a thing happened' },
            { name: 'removable', prop: 'onRemove', when: 'a tag a person can take away: the remove mark after its name' },
            { name: 'button', prop: 'onClick', class: 'mark-button', when: 'a tag that is a button: press it to change who may see' },
            { name: 'presence', prop: 'presence', class: 'mark-presence', when: 'an agent\'s tag with its status dot, and the coral "away"' },
            { name: 'explains', prop: 'explains', class: 'mark-explains', when: 'a mark whose tooltip says why: the help pointer' },
            { name: 'live', prop: 'live', class: 'mark-live', when: 'a connection that works: a small green square before the words' },
            { name: 'label', prop: 'Label', when: 'the row label in small coral capitals (.poster-label); block on its own line' },
            { name: 'code', prop: 'Code', when: 'code in a line; block for a code block (css/components/code-block.css)' },
        ],
        example: { kind: 'tag', tone: 'sun', children: 'v1.4.0' },
        note: 'The tag, status, count, time and label are the shapes of css/poster.css (entries \'chip\', \'status\', \'count\', \'time\', \'label\'); Code is css/components/code-block.css (entry \'code-block\'). mark.css holds only what the shapes lack: the fine tone, the button, presence, explains and live cuts.',
    },
    {
        id: 'note', name: 'Note', kind: 'component', status: 'active',
        summary: 'The sentences a page says about itself, as one component: the lead that opens a section, the grey hint that explains (the default), the quiet line that says a list is empty, the loading line with its blinking coral square, the message after a save, the small grey meta words, and the aside in a dashed frame that asks the person to look.',
        module: '/components/Note.js', sheet: '/css/components/hint.css',
        data: {
            shape: 'Note({ kind, slab, inline, error, pre, size, tone, title, role, mono, children })',
            fields: {
                kind: 'hint (the default) | lead | quiet | loading | message | meta | aside',
                slab: 'hint: the small typewriter line beside a loud action', inline: 'hint, quiet, loading, meta: one inside a line of words',
                error: 'message: a refusal (in coral, said as an alert), otherwise a success', pre: 'message: a refusal that names several problems, one per line',
                size: 'aside: small | large', tone: 'aside: irreversible (an act that cannot be undone) | waiting (the next move is in another window) | suggestion (a line the person can wave away)',
                mono: 'meta: in the typewriter face (a record\'s facts)', title: 'the tooltip', role: 'what a screen reader is told (a failure as an alert)',
                children: 'the words; a loading line without words says "Loading…"',
            },
        },
        useFor: ['Any sentence a Settings page says about itself: what a section is for, what a control does, that a list is empty or loading, what a save did, what cannot be undone.'],
        variants: [
            { name: 'hint', prop: 'kind="hint"', class: 'poster-hint', when: 'a grey sentence that explains a control or a section' },
            { name: 'slab hint', prop: 'slab', class: 'poster-hint--slab', when: 'beside a loud action: what it does, or why it cannot be pressed yet' },
            { name: 'lead', prop: 'kind="lead"', when: 'the sentence that opens a section (.og-lead, page-section.css)' },
            { name: 'quiet', prop: 'kind="quiet"', when: 'a list is empty, or a thing is not there (.poster-quiet, quiet-note.css)' },
            { name: 'loading', prop: 'kind="loading"', when: 'something is loading: the quiet line with the blinking mark (loading-mark.css)' },
            { name: 'message', prop: 'kind="message"', when: 'what a form did: done in green, refused in coral with error (form-message.css)' },
            { name: 'meta', prop: 'kind="meta"', when: 'the small grey words of a classic Settings page (.text-meta-sm, text-utility.css)' },
            { name: 'aside', prop: 'kind="aside"', when: 'a note in a dashed coral frame beside the flow (.poster-aside, poster.css)' },
        ],
        example: { kind: 'hint', children: 'Your agents read this once a session.' },
        note: 'Each kind wears the sheet of the look it draws: hint.css (hint, the default kind, named here as its sheet), page-section.css (lead), quiet-note.css (quiet), loading-mark.css (loading), form-message.css (message), text-utility.css (meta) and poster.css (aside). The Hint component (entry \'hint\') owns hint.css and draws only the plain hint.',
    },
    {
        id: 'box', name: 'Box', kind: 'component', status: 'active',
        summary: 'The frame around one thing: a 2px ink frame on the card ground (the Object box), with an optional head (a name in bold, its tags, a mark at the right end) and a row of actions at its foot; its tones say what the thing is for. Also the settings box, and a stack of small boxes one thing each.',
        module: '/components/Box.js', sheet: '/css/components/box.css',
        data: {
            shape: 'Box({ tone, flush, packed, scroll, folded, unfoldLabel, onUnfold, document, beside, as, name, marks, end, doors, id, role, ariaLabel, children }) · SettingBox({ label, irreversible, children }) · SettingRow({ children }) · SettingConfirm({ children }) · BoxList({ apart, children }) · BoxLine({ name, meta, time, end, column, doors, after, children }) · boxClass(tone) (for Card and Road only)',
            fields: {
                tone: 'none (one thing) | raised (the thing that stands out: an opened row, the way to take first) | copy (a text to copy, on the grey ground) | row (one result in a list, small padding) | attention (coral frame: needs a look) | waiting (sun frame: waits for an answer) | current (coral frame: the one you are on) | off (dashed, grey: switched off) | edge (no frame, the sun edge at the left: what a thing needs from elsewhere) | field (the thin dashed frame around a field to fill in) | dim (the grey ground: details a person need not touch)',
                flush: 'the parts pad themselves (a chart, a picture): no padding', packed: 'it stands in a grid or a row that spaces it: no margin',
                scroll: 'a long text scrolls inside after 24rem; "page" after 32rem',
                folded: 'a long text shows its first 22rem under a fade; onUnfold and unfoldLabel put "show all" at the fade\'s foot',
                document: 'it holds a rendered document whose words keep .75rem 1rem from the frame', beside: 'the doors stand at the right of the words, under them on a phone',
                as: 'the element: div (default) | li | label | section | article',
                name: 'the head\'s name in bold', marks: 'tags beside the name', end: 'what stands at the right end of the head (the mark that hides the box)',
                doors: 'the row of actions at the foot', children: 'what the box holds',
                SettingBox: 'a box on a settings page: its label on its own line over the words; irreversible for an act that cannot be undone',
                SettingRow: 'the settings box\'s line of words with its button at the right', SettingConfirm: 'the line that asks for a word before the act',
                BoxList: 'a stack of small boxes, one thing each; apart puts .3rem above it',
                BoxLine: 'one small box: name, meta (grey typewriter lines; { text, keep: true } is not translated), time, end (a grey word at the far end), column (the parts under each other), doors, after (what the doors caused)',
            },
        },
        useFor: ['Around one thing that needs its own frame on a Settings page: a result, a preview, a text to copy, a field to test, a verdict.', 'SettingBox for a setting with its own frame (leaving, deleting); BoxList for a short stack of entries each in a small box.'],
        variants: [
            { name: 'raised', prop: 'tone="raised"', when: 'the thing that stands out: the heavier frame with the raised shadow (.poster-box--raised)' },
            { name: 'copy', prop: 'tone="copy"', when: 'a text a person copies, on the grey ground (.poster-box--copy)' },
            { name: 'row', prop: 'tone="row"', when: 'one result in a list, small padding (.poster-box--row)' },
            { name: 'attention', prop: 'tone="attention"', class: 'box--attention', when: 'a result that needs a look: coral frame' },
            { name: 'waiting', prop: 'tone="waiting"', class: 'box--waiting', when: 'a thing that waits for an answer: sun frame' },
            { name: 'current', prop: 'tone="current"', class: 'box--current', when: 'the one you are on (this device): coral frame' },
            { name: 'off', prop: 'tone="off"', class: 'box--off', when: 'switched off: dashed frame, grey words' },
            { name: 'edge', prop: 'tone="edge"', class: 'box--edge', when: 'what a thing needs from elsewhere: the sun edge at the left, no frame' },
            { name: 'field', prop: 'tone="field"', class: 'box--field', when: 'a field to fill in for one action: the thin dashed frame (Jouni\'s decision "Dashed field box")' },
            { name: 'dim', prop: 'tone="dim"', class: 'box--dim', when: 'details a person need not touch: the grey ground' },
            { name: 'flush', prop: 'flush', class: 'box--flush', when: 'a chart or a picture that pads itself' },
            { name: 'packed', prop: 'packed', class: 'box--packed', when: 'a box in a grid or row that spaces it' },
            { name: 'scroll', prop: 'scroll', class: 'box--scroll', when: 'a long text that scrolls inside after 24rem' },
            { name: 'scroll page', prop: 'scroll="page"', class: 'box--scroll-page', when: 'a map of a whole structure: scrolls after 32rem' },
            { name: 'folded', prop: 'folded', class: 'box--folded', when: 'a long text under a fade, with "show all"' },
            { name: 'document', prop: 'document', class: 'box--document', when: 'a rendered document that keeps its words off the frame' },
            { name: 'beside', prop: 'beside', class: 'box-beside', when: 'a verdict and its one way on at the right' },
            { name: 'head', prop: 'name, marks, end', class: 'box-head', when: 'a box that names its thing: the name in bold, its tags, a mark at the right' },
            { name: 'box list', prop: 'BoxList, BoxLine', class: 'box-line', when: 'a stack of small boxes, one entry in each' },
            { name: 'setting box', prop: 'SettingBox', when: 'a setting in its own frame (setting-box.css); irreversible for a solid frame' },
        ],
        example: { name: 'Recovery key', children: 'Keep it where you keep passwords.', doors: 'Copy' },
        note: 'The frame and its raised, copy and row tones are the shapes of css/poster.css (entry \'box-shape\'); box.css holds only what the shapes do not: the head and foot, padding and margin by meaning, and the tones that colour a frame. The settings box keeps the library classes og-box, og-box-row and og-box-confirm (entry \'setting-box\', shared with the admin). The meter is Figure\'s Meter.',
    },
    {
        id: 'avatar', name: 'Avatar', kind: 'component', status: 'active',
        summary: 'The square mark at the start of a row that says who or what the row is about: initials or one sign in the Object box\'s avatar square, an identicon drawn from a seed, or a picture; dashed and grey for a sender that is not a person.',
        module: '/components/Avatar.js', sheet: '/css/components/avatar.css',
        data: {
            shape: 'Avatar({ text, seed, agent, size, label, children })',
            fields: {
                text: 'the initials or one sign; one sign stands at the body size, two or more at the note size (the component decides)',
                seed: 'draws the identicon of that seed in place of text', children: 'a picture in place of text',
                agent: 'not a person (an agent, an app, a mail service not yet connected, a tool that is gone): a dashed frame and grey letters',
                size: 'none (2.2rem, a row) | small (24px, beside a group\'s heading) | large (2.4rem, a file\'s picture)',
                label: 'what a screen reader hears (role img); without it the mark is hidden from a screen reader',
            },
        },
        useFor: ['At the start of a row of people, companies, agents, apps or files, so the eye finds the row by its mark.'],
        variants: [
            { name: 'row', prop: 'text', class: 'avatar', when: 'initials at the start of a row: 2.2rem' },
            { name: 'small', prop: 'size="small"', class: 'avatar--small', when: 'beside a group\'s heading: 24px' },
            { name: 'large', prop: 'size="large"', class: 'avatar--large', when: 'a file\'s picture: 2.4rem' },
            { name: 'agent', prop: 'agent', when: 'a sender that is not a person: dashed frame, grey letters (.poster-box--agent)' },
            { name: 'identicon', prop: 'seed', when: 'a person in Messages, drawn from their address' },
        ],
        example: { text: 'HS' },
        note: 'The square and its agent tone are the Object box\'s avatar cut in css/poster.css (entry \'box-shape\'); avatar.css holds the named sizes. The List (components/List.js) and the conversation list have their own avatar cells.',
    },
    {
        id: 'roads', name: 'Roads', kind: 'component', status: 'active',
        summary: 'The ways to do one thing, side by side (ask your AI, do it here, paste a result): each road a framed tile with a small coral typewriter line, the name in bold, a grey sentence, and a request to copy or its actions at the foot; the way to take first raised; one column on a phone.',
        module: '/components/Roads.js', sheet: '/css/components/roads.css',
        data: {
            shape: 'Roads({ cols, wide, children }) · Road({ lead, chosen, onPick, kicker, name, sub, text, code, meta, codeLine, doors, children })',
            fields: {
                cols: 'two (two equal columns, the default) | three', wide: 'the first column has more room (the lead road with its request to copy)',
                lead: 'the way to take first: the raised box (Jouni\'s decision "Box")',
                chosen: 'the road is one of a few to choose: true draws it on the sun (Jouni\'s decision "Choice"), false choosable',
                onPick: 'a press on the tile outside its doors chooses it; without it only its door chooses',
                kicker: 'the small coral line over the name: the road\'s key', name: 'the road\'s name in bold', sub: 'the same small line under the name: what it takes',
                text: 'the grey sentence', code: 'a request to copy, as a code block', children: 'a form or a field',
                meta: 'the grey typewriter line: the tools an agent calls', codeLine: 'a line of code at the foot', doors: 'the row of actions at the foot',
            },
        },
        useFor: ['Where a person can do one thing in two or three ways and should see them side by side before choosing.'],
        variants: [
            { name: 'two', prop: 'cols="two"', class: 'roads', when: 'two roads in two equal columns' },
            { name: 'three', prop: 'cols="three"', class: 'roads--three', when: 'three roads side by side' },
            { name: 'wide', prop: 'wide', class: 'roads--wide', when: 'the first road has more room for its request' },
            { name: 'lead', prop: 'lead', when: 'the way to take first: the raised box' },
            { name: 'chosen', prop: 'chosen', class: 'on', when: 'one of a few to choose; the chosen one on the sun' },
            { name: 'door chooses', prop: 'chosen without onPick', class: 'road--still', when: 'only the road\'s door chooses it; the tile keeps the plain pointer' },
        ],
        example: { cols: 'two', wide: true, roads: [{ lead: true, name: 'Ask your AI', text: 'Copy the request into your own chat.', code: 'aimeat_skill_get aimeat-writing' }, { name: 'Your agent does it', text: 'An agent with the skill scope calls the tools itself.', meta: 'aimeat_skill_publish · aimeat_skill_link' }] },
        note: 'Each Road is the framed tile of the Card (components/Card.js, card.css .card-tile--framed) in the Object box; roads.css holds the columns and the chosen road\'s words.',
    },
    {
        id: 'figure', name: 'Figure', kind: 'component', status: 'active',
        summary: 'A figure, read only: one number in the poster face with a small typewriter line under it, the sun sticker that carries the one fact to see first, the meter that fills to a share (coral for a limit, red from 90 %), and words or a number in a state colour inside other words.',
        module: '/components/Figure.js', sheet: '/css/components/figure.css',
        data: {
            shape: 'Figure({ n, sub, small, large, step, band, tone, end, title }) · Sticker({ figure, children }) · Meter({ pct, quota, early, figure, beside, fill, thin }) · Tinted({ tone, strong, whole, children })',
            fields: {
                n: 'the figure', sub: 'the small typewriter line under it ("morsels", "Tue")',
                small: 'the cut a row of a list uses', large: 'the hero cut', step: 'a step\'s number in coral', band: 'the figure on the coral band',
                tone: 'Figure: fine (came in, fine) | notice (went out, needs a look) | dim (not there yet); Tinted: fine | notice | warn | danger | dim | faint (a word that says nothing is there)',
                end: 'the figure stands at the end of its cell, on one line', title: 'the tooltip',
                figure: 'Sticker: the short figure over its one action; Meter: the words written on the bar',
                pct: 'Meter: the share, 0 to 100 (clamped)', quota: 'Meter: a meter of a limit, coral, red from 90 %', early: 'with quota: it warns from 60 %',
                beside: 'Meter: in a line of words, 15rem (the whole width on a phone)', fill: 'Meter: takes the rest of its line beside a field', thin: 'Meter: the thin cut of a progress through steps',
                strong: 'Tinted: in bold', whole: 'Tinted: kept on one line, never broken inside', children: 'Sticker: its one action; Tinted: the words',
            },
        },
        useFor: ['A number a person reads in a row or a cell: an amount, a time, a score, a count.', 'How much of a limit is used (Meter), and a word inside a sentence that says a state (Tinted).'],
        variants: [
            { name: 'figure', prop: 'Figure', class: 'figure', when: 'one number in the poster face in a cell' },
            { name: 'end', prop: 'end', class: 'figure--end', when: 'right-aligned on one line (an amount in a table)' },
            { name: 'fine', prop: 'tone="fine"', class: 'figure--fine', when: 'came in, or fine' },
            { name: 'notice', prop: 'tone="notice"', class: 'figure--notice', when: 'went out, or needs a look' },
            { name: 'dim', prop: 'tone="dim"', class: 'figure--dim', when: 'not there yet' },
            { name: 'sticker', prop: 'Sticker', when: 'the one fact to see first, on the sun, with one action (.poster-sticker)' },
            { name: 'meter', prop: 'Meter', class: 'meter', when: 'a bar of sun that fills to a share' },
            { name: 'quota', prop: 'Meter quota', class: 'poster-box--quota', when: 'a meter of a limit: coral, red from 90 %' },
            { name: 'early', prop: 'Meter quota early', class: 'is-warn', when: 'a quota that warns from 60 %' },
            { name: 'meter figure', prop: 'Meter figure', class: 'meter--figure', when: 'the words written on the bar' },
            { name: 'beside', prop: 'Meter beside', class: 'meter--beside', when: 'a meter in a line of words' },
            { name: 'fill', prop: 'Meter fill', class: 'meter--fill', when: 'a meter that takes the rest of its line' },
            { name: 'thin', prop: 'Meter thin', class: 'meter--thin', when: 'the progress through steps' },
            { name: 'tinted', prop: 'Tinted tone', class: 'tinted--notice', when: 'a word in a state colour inside other words' },
            { name: 'faint', prop: 'Tinted tone="faint"', class: 'tinted--faint', when: 'a word that says nothing is there ("never")' },
            { name: 'whole', prop: 'Tinted whole', class: 'tinted--whole', when: 'words kept on one line (a host name)' },
        ],
        example: { small: true, end: true, tone: 'fine', n: '+120', sub: 'morsels' },
        note: 'The numeral, the sticker and the meter are the shapes of css/poster.css (entries \'stat\', \'sticker\', \'box-shape\'); figure.css holds the cell place, the tones, the meter sizes and Tinted. The strip of figures under a page head is FigureStrip (entry \'figure-strip\').',
    },
    // The older Settings entries the kit draws now, moved here unchanged from entries-settings.ts
    // (which had passed its length limit): two with a kit module of their own (Facts, FigureStrip),
    // and four whose classes the admin pages share, so module stays null and the summary names the call.
    {
        id: 'figure-strip', name: 'Figure strip', kind: 'component', status: 'active',
        summary: 'A few figures between two heavy ink rules: the number in the poster face, its word, a small typewriter line under it; two to a row on a phone. A page passes the figures as data to FigureStrip.',
        module: '/components/FigureStrip.js', sheet: '/css/components/figure-strip.css',
        data: {
            shape: 'FigureStrip({ items: [{ n, of, label, sub, tone, key }], loading, wrap, flush, lead })',
            fields: {
                n: 'the figure: a number, a word or a time; "…" while it loads, "·" when there is none', of: 'the "of how many" after it ("/4"), smaller and grey',
                label: 'the word beside the figure (always drawn, empty or not)', sub: 'the typewriter line under it; "" still draws the empty line, undefined draws none',
                tone: 'coral (a word in coral capitals: a state, a time) | word (a word in capitals where a number would stand) | notice (a number in coral) | fine | warn | danger (the Status colours) | dim (not there yet) | long (a long word such as an address, smaller); two join with a space: "word fine"',
                loading: 'how many cells hold the place with "…" while the data loads', wrap: 'the lines under the figures wrap instead of ending in "…"',
                flush: 'the strip opens its box: no air above', lead: 'the strip opens a tab\'s content: no air above, air under it',
            },
        },
        useFor: ['Under a page head, the few numbers that say how big a thing is.'],
        variants: [
            { name: 'coral', prop: 'tone: "coral"', class: 'og-strip-coral', when: 'a word instead of a number, in coral capitals' },
            { name: 'word', prop: 'tone: "word"', class: 'og-strip-word', when: 'a word in capitals where a number would stand' },
            { name: 'notice', prop: 'tone: "notice"', class: 'og-strip-notice', when: 'a number to look at, in coral' },
            { name: 'fine', prop: 'tone: "fine"', class: 'og-strip-fine', when: 'a state that is fine' },
            { name: 'warn', prop: 'tone: "warn"', class: 'og-strip-warn', when: 'a state that needs a look' },
            { name: 'danger', prop: 'tone: "danger"', class: 'og-strip-danger', when: 'a state that is wrong' },
            { name: 'dim', prop: 'tone: "dim"', class: 'og-strip-dim', when: 'a figure that is not there yet' },
            { name: 'long', prop: 'tone: "long"', class: 'og-strip-long', when: 'a long word such as an address, smaller and breaking where it must' },
            { name: 'of', prop: 'of', class: 'og-strip-of', when: 'the part after the slash in "3/4": smaller, in grey' },
            { name: 'wrap', prop: 'wrap', class: 'og-strip--wrap', when: 'the lines under the figures are read whole' },
            { name: 'flush', prop: 'flush', class: 'og-strip--flush', when: 'the strip opens its box' },
            { name: 'lead', prop: 'lead', class: 'og-strip--lead', when: 'the strip opens a tab\'s content' },
        ],
        example: { items: [{ n: 12, label: 'spaces', sub: '3 shared with you' }, { n: 4, of: '/6', label: 'people', sub: '2 admins' }] },
        note: 'The class names (.og-strip, .og-strip-*) are shared with the admin pages, which still write the strip by hand. The node stats StatCard and the pages\' own figure colours (.is-coral, .is-low, .is-good, .is-dim, .op-st-*, .sc-res--*) became items and tones.',
    },
    {
        id: 'facts', name: 'Facts', kind: 'component', status: 'active',
        summary: 'Named values in two columns: the name as the row label on the left, the value on the right with an optional grey line under it; one column on a phone. A page passes the rows as data to Facts.',
        module: '/components/Facts.js', sheet: '/css/components/facts.css',
        data: {
            shape: 'Facts({ rows: [{ k, v, sub, subTone, key, mono, warn, missing, pre, controls, action, actions, state }], wide, flush }) · FactLine({ sub, subTone, children })',
            fields: {
                k: 'the name (the row label)', state: 'fine | attention | danger | off: the name is a state and draws as a Status in that tone',
                v: 'the value: words, a number, or kit parts (Mark, Code, Action, Tinted, FactLine, Meter…)', mono: 'the value is an identifier, drawn as code',
                sub: 'the grey line under the value ("" still draws it)', subTone: 'notice: the grey line in coral',
                warn: 'the value needs a look: the attention colour', missing: 'the value is not known or not set: grey', pre: 'the value keeps its own line breaks',
                controls: 'the value is controls in a row (a picker and its action)', action: 'one action after the value, on the same line', actions: 'a row of actions under the value',
                key: 'the list key (default: k)', wide: 'longer names, more air above', flush: 'the facts at the very top of their box',
                FactLine: 'one line of a value made of several lines, each with its own grey line',
            },
        },
        useFor: ['The facts of one thing: its version, who owns it, where it is used.'],
        variants: [
            { name: 'wide', prop: 'wide', class: 'facts--wide', when: 'longer names, more air above' },
            { name: 'flush', prop: 'flush', class: 'facts--flush', when: 'the facts open their box, no air above' },
            { name: 'warn', prop: 'warn', class: 'facts-v--warn', when: 'a value that needs a look: the attention colour' },
            { name: 'missing', prop: 'missing', class: 'facts-v--missing', when: 'a value that is not known or not set: grey' },
            { name: 'pre', prop: 'pre', class: 'facts-v--pre', when: 'a value that keeps its own line breaks' },
            { name: 'controls', prop: 'controls', class: 'facts-v--controls', when: 'a picker and its action in a row' },
            { name: 'action', prop: 'action', class: 'facts-after', when: 'one action beside the value (copy an address)' },
            { name: 'notice sub', prop: 'subTone: "notice"', class: 'facts-sub--notice', when: 'the grey line in coral: something is missing' },
            { name: 'state', prop: 'state', when: 'a name that is itself a state, as a Status' },
        ],
        example: { rows: [{ k: 'Version', v: '1.4.0', sub: 'published today' }, { k: 'Owner', v: 'sandbox@aimeat-local-001-dev', mono: true }] },
        note: 'Built on 2026-09-25 with the look five Settings tabs draw as identical copies; the Settings facts moved onto it the same day, and on 2026-09-26 the pages stopped writing its classes and pass rows to Facts. KeyValueRow\'s one Settings caller draws Facts now.',
    },
    {
        id: 'setting-box', name: 'Setting box', kind: 'component', status: 'active',
        summary: 'A box on a settings page in the small aside\'s dashed coral frame: its label on a line of its own, a row of words with its button at the right, and a confirmation line with its field. A Settings page draws it with SettingBox, SettingRow and SettingConfirm (components/Box.js); the admin pages write its classes.',
        module: null, sheet: '/css/components/setting-box.css', classes: ['og-box', 'og-box-label', 'og-box-row', 'og-box-confirm'],
        data: {
            shape: 'SettingBox({ label, irreversible, children }) · SettingRow({ children }) · SettingConfirm({ children }) · <div class="og-box poster-aside poster-aside--small"><span class="og-box-label">…</span><div class="og-box-row"><p>…</p><button>…</button></div></div> (admin)',
            fields: { label: 'what the box is about', irreversible: 'the act cannot be undone: the solid frame', row: 'the sentence and its button', confirm: 'the field that asks for the name before an act that cannot be undone' },
        },
        useFor: ['A setting that needs its own frame, such as leaving or deleting.'],
        variants: [
            { name: 'row', prop: 'SettingRow', class: 'og-box-row', when: 'the sentence with its button at the right' },
            { name: 'confirm', prop: 'SettingConfirm', class: 'og-box-confirm', when: 'the line that asks for a word before the act' },
            { name: 'label (admin)', class: 'og-box-label', when: 'the admin pages\' label in the poster face; SettingBox draws the row label (.poster-label) on its own line' },
            { name: 'irreversible', prop: 'irreversible', when: 'an act that cannot be undone: the solid frame (.poster-aside--irreversible)' },
        ],
        example: { label: 'Leave', row: 'You can come back when invited.' },
        note: 'module is null because its classes are shared with the admin pages, which write them as markup; in Settings & Controls it is SettingBox, SettingRow and SettingConfirm in components/Box.js (entry \'box\').',
    },
    {
        id: 'code-block', name: 'Code block', kind: 'component', status: 'active',
        summary: 'Code, a prompt or a path in the typewriter face on the grey ground: a block that wraps its long lines, or a small patch inside a sentence. A Settings page draws it with Code (components/Mark.js): Code block for the block, Code for the patch.',
        module: null, sheet: '/css/components/code-block.css', classes: ['code-block', 'code-inline'],
        data: {
            shape: 'Code({ block, scroll, tall, blurred, change, children }) · <pre class="code-block">…</pre> · <code class="code-inline">…</code>',
            fields: {
                children: 'the code', block: 'lines of code or a prompt to copy; without it a patch inside a sentence',
                scroll: 'block: scrolls inside after 200px; "medium" 300px, "large" 400px, "page" 32rem', tall: 'block: a prompt to copy that scrolls after 24rem',
                change: 'block: added | removed, the heavy green or coral edge of a draft\'s diff', blurred: 'inline: a secret shown blurred until the person asks to see it',
            },
        },
        useFor: ['Something a person reads exactly or copies: an address, a command, a prompt.'],
        variants: [
            { name: 'block', prop: 'Code block', class: 'code-block', when: 'lines of code or a prompt, wrapping' },
            { name: 'inline', prop: 'Code', class: 'code-inline', when: 'inside a sentence' },
            { name: 'scroll', prop: 'Code block scroll', class: 'code-block--scroll', when: 'a long block (a schema) that scrolls after 200px' },
            { name: 'tall', prop: 'Code block tall', class: 'code-block--tall', when: 'a prompt to copy that scrolls after 24rem' },
            { name: 'added', prop: 'Code block change="added"', class: 'code-block--added', when: 'the lines a draft adds: a heavy green edge' },
            { name: 'removed', prop: 'Code block change="removed"', class: 'code-block--removed', when: 'the lines a draft removes: a heavy coral edge' },
            { name: 'blurred', prop: 'Code blurred', class: 'code-inline--blurred', when: 'a recovery key, blurred until shown' },
        ],
        example: { children: 'aimeat_skill_get aimeat-writing' },
        note: 'module is null because its classes are shared with the admin pages, which write them as markup; in Settings & Controls it is Code in components/Mark.js (entry \'mark\'), and Card and Road draw a tile\'s code with the same classes.',
    },
    {
        id: 'form-message', name: 'Form message', kind: 'component', status: 'active',
        summary: 'The line a form says after it acted: done in green, refused in coral. A Settings page draws it with Note kind="message" (components/Note.js); `error` for a refusal.',
        module: null, sheet: '/css/components/form-message.css', classes: ['form-message'],
        data: {
            shape: 'Note({ kind: "message", error, pre, role, children }) · <span class="form-message">Saved.</span>',
            fields: { children: 'what happened', error: 'the form was refused (said to a screen reader as an alert; otherwise as a status)', pre: 'a refusal that names several problems keeps one per line' },
        },
        useFor: ['Under a form\'s actions, after Save or Send.'],
        variants: [
            { name: 'done', prop: 'kind="message"', class: 'form-message', when: 'the form did what was asked' },
            { name: 'error', prop: 'error', class: 'form-message--error', when: 'the form was refused' },
            { name: 'several problems', prop: 'error pre', class: 'form-message--pre', when: 'a refusal that names several problems, one per line' },
        ],
        example: { kind: 'message', children: 'Saved.' },
        note: 'module is null because its classes are shared with the admin pages, which write them as markup; in Settings & Controls it is the message kind of Note (entry \'note\').',
    },
    {
        id: 'loading-mark', name: 'Loading mark', kind: 'component', status: 'active',
        summary: 'A small coral square that blinks before the quiet sentence that says something is loading. A Settings page draws it with Note kind="loading" (components/Note.js); without words it says "Loading…".',
        module: null, sheet: '/css/components/loading-mark.css', classes: ['loading-mark', 'ct-loading'],
        data: {
            shape: 'Note({ kind: "loading", inline, children }) · <p class="poster-quiet loading-mark">Loading…</p>',
            fields: { children: 'the loading words; none says "Loading…"', inline: 'the loading line inside a line of words' },
        },
        useFor: ['While a list, a page or a part of a Settings tab loads: the one loading line of Settings & Controls.'],
        variants: [
            { name: 'line', prop: 'kind="loading"', class: 'loading-mark', when: 'a list, a page or a part that loads' },
            { name: 'inline', prop: 'kind="loading" inline', when: 'the same inside a line of words' },
        ],
        example: { kind: 'loading', children: 'Loading…' },
        note: 'Moved on 2026-09-25 out of the Contacts sheet (ct-loading, its rules keep the page\'s scope .og-ct) and out of five identical copies in Discover, Knowledge, Boards, Workflows and Notifications, under one name (.og .loading-mark); nothing changed on screen. On 2026-09-26 every loading line of Settings & Controls took it (the quiet sentence with the mark, the look most tabs used; the Spinner and the plain grey lines went), so it also applies inside the classic tabs (.pf) and a dialog (.dlg); it is the loading kind of Note (entry \'note\'), and LoadingLine in views/profile/shared.js calls it. module is null because the admin pages write its class. No page writes ct-loading any more: its two rules in loading-mark.css are dead.',
    },
];
