/**
 * @file src/services/ui-library/entries-shell.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description The catalogue's shell parts and the older shared components: the parts theme.css held
 *   as rules until 2026-09-24 (the page base, the top bar, the classic buttons, cards, badges, the
 *   segmented control, forms, the toast…), each in its own css/components/ sheet now, and every
 *   /components module that had no entry. A part whose look still sits in a page sheet says so in
 *   its note: that look is debt, to move into a sheet of its own when the part is next touched.
 * @structure SHELL_ENTRIES
 * @usage import { SHELL_ENTRIES } from './entries-shell.js';
 * @version-history
 *   v1.6.0 — 2026-09-27 — StartPageSetting's dialog (and its footer, named) and ToastBox's hold and role: the
 *     home and the pop-out windows pass meanings, not classes.
 *   v1.5.1 — 2026-09-27 — AgentConsent and DisplayPrefsFields draw their own names from sheets of their
 *     own (agent-consent.css, display-prefs-fields.css; a move); the page-sheet debt note had no
 *     entry left and goes.
 *   v1.5.0 — 2026-09-27 — Card: the tile and its grid (ruled, framed, section, panel, figure; CardGrid), the classic card one variant.
 *   v1.5.0 — 2026-09-27 — LinkPreview, Mermaid, ContactCard and the offer card parts draw their own
 *     names, from sheets of their own (link-preview.css, mermaid.css, contact-card.css, offer-card-view.css; a move).
 *   v1.4.0 — 2026-09-27 — KeyValueRow is unused: its one caller draws the Facts now.
 *   v1.3.0 — 2026-09-26 — JsonView is every stored value opened under its row in Settings & Controls (a unification).
 *   v1.2.0 — 2026-09-25 — JsonView's look is its own sheet, css/components/json-view.css (UI consolidation phase 5, a move).
 *   v1.1.0 — 2026-09-24 — FormField is active: Themes & Styles draws it.
 *   v1.0.0 — 2026-09-24 — Initial (UI consolidation: theme.css to tokens only; every module catalogued).
 */
import type { UiEntryWritten } from './types.js';

export const SHELL_ENTRIES: UiEntryWritten[] = [
    {
        id: 'page-base', name: 'Page base', kind: 'component', status: 'active',
        summary: 'The page itself: the document and its base elements, the app root and its one scroll region, the scrollbar, the page entrance, the agent-facing footer links, the visually-hidden helper.',
        module: null, sheet: '/css/components/page-base.css', classes: ['page-content', 'bg-canvas', 'agent-footer', 'visually-hidden'],
        data: { shape: '<div id="app"><div class="page-content">…</div></div>', fields: { children: 'the view' } },
        useFor: ['Drawn once by spa.html around every view; a view never restyles it.'],
        variants: [], example: {},
    },
    {
        id: 'top-bar', name: 'Top bar', kind: 'component', status: 'active',
        summary: 'The bar on every page of the shell: the wordmark, the links, the open items, the bell, the login pill, the language and theme buttons, and its phone menu.',
        module: null, sheet: '/css/components/top-bar.css', classes: ['topnav', 'topnav-brand', 'lang-btn'],
        data: { shape: 'Header in spa.html', fields: { links: 'the pages a person may open', auth: 'the login pill' } },
        useFor: ['Drawn by spa.html (Header) at the top of every page.'],
        variants: [{ name: 'compact', class: 'topnav--compact', when: 'a narrow screen: the links fold into the menu' }],
        example: {},
    },
    {
        id: 'button', name: 'Classic button', kind: 'component', status: 'active',
        summary: 'The classic buttons: primary (coral), outline, ghost, danger, success and small, with their copied and success states.',
        module: null, sheet: '/css/components/button.css', classes: ['btn-primary', 'btn-outline', 'btn-ghost', 'btn-danger', 'btn-sm'],
        data: { shape: '<button class="btn-primary">…</button>', fields: { children: 'the words' } },
        useFor: ['The classic shell (admin and the older views). The poster pages use the action link and the slab.'],
        variants: [
            { name: 'outline', class: 'btn-outline', when: 'a second action' },
            { name: 'ghost', class: 'btn-ghost', when: 'a quiet action' },
            { name: 'small', class: 'btn-sm', when: 'in a row or a table' },
        ],
        example: { children: 'Save' },
    },
    {
        id: 'copy-button', name: 'CopyButton', kind: 'component', status: 'active',
        summary: 'A button that copies a text and says so for a moment; it wears the class it is given (a classic button, an action link, a slab).',
        module: '/components/CopyButton.js', sheet: '/css/components/button.css', classes: ['copied'],
        data: { shape: 'CopyButton({ text, className, label, copiedLabel, title })', fields: { text: 'what is copied', className: 'the look to wear', label: 'the words', copiedLabel: 'the words after copying' } },
        useFor: ['Anywhere a person copies a text into their own AI or elsewhere.'],
        variants: [], example: { text: 'Hello', label: 'Copy', copiedLabel: 'Copied' },
    },
    {
        id: 'card', name: 'Card', kind: 'component', status: 'active',
        summary: 'One thing as a tile, and the grid the tiles stand in: the ruled tile (the name in bold over its words and a grey typewriter line, a thin rule under it), the framed tile in the Object box, a section under the thick rule, a part of the overview, and a figure that opens its tab. Without a tone and a name it is still the classic card of the classic shell (title, subtitle, hover, glass).',
        module: '/components/Card.js', sheet: '/css/components/card.css',
        data: {
            shape: 'Card({ tone, state, mark, kicker, name, sub, text, clamp, code, meta, lines, codeLine, doors, onOpen, openLabel, title, aside, note, rule, wide, inRow, figure, id, children }) · Card({ title, subtitle, onClick, hoverable, variant, className, children }) (the classic card) · CardGrid({ cols, children }) · tileParts(props) (for Road only)',
            fields: {
                tone: 'none (the ruled tile) | framed (the tile in the Object box) | section (an older Settings group under the thick rule) | panel (one part of the overview) | figure (a number that is a door to its tab)',
                state: 'framed: current (the one you are on, a coral frame) | off (switched off: dashed, grey) | raised (the one that stands out)',
                mark: 'an Avatar or a sign before the name', kicker: 'a small coral typewriter line over the name', name: 'the tile\'s name in bold',
                sub: 'the same small line under the name', text: 'the sentence; clamp cuts it after two lines', code: 'a code block to copy',
                meta: 'the grey typewriter line', lines: '[{ key, label, count, dim }]: named counts under the meta line, a hairline over each, the count at the right',
                codeLine: 'a line of code at the foot', doors: 'the row of actions at the foot (never with onOpen)',
                onOpen: 'the whole tile (or a panel\'s headline, or a figure) is the door: a press, Enter or Space opens it; openLabel is its tooltip',
                title: 'section and panel: the headline', aside: 'section: what stands at the right of the title', note: 'panel: a grey typewriter line after the headline',
                rule: 'panel: the thick rule on top', wide: 'section and panel: spans every column of its grid', inRow: 'section: stands inside a list row, row air and no margin',
                figure: 'figure: the number; name is its word', children: 'a field or a form inside a tile; the content of a section or a panel',
                cols: 'CardGrid: three (the default) | two | fill (as many 180px tiles as fit) | one | sections (340px or wider) | panels (the overview\'s two columns) | figures (figure doors in a line) | strip (the tiles in one line that scrolls sideways, each at least 160px wide); three and two fold to one column under 860px',
                subtitle: 'classic card: the line under the title', variant: 'classic card: "glass" for the glass ground',
            },
        },
        useFor: ['A set of things of one kind, each a tile a person scans or opens: a device, an extension, an app, a place.',
            'A section tone for an older Settings group, a panel tone for a part of the overview, a figure tone for a number that opens its tab.',
            'The classic card is for the classic shell only; a Settings page always passes a tone or a name.'],
        variants: [
            { name: 'ruled tile', prop: 'name (no tone)', class: 'card-tile--ruled', when: 'one thing among many: name, words, meta line, a thin rule under it' },
            { name: 'framed tile', prop: 'tone="framed"', class: 'card-tile--framed', when: 'a thing with its own actions, in the Object box' },
            { name: 'door tile', prop: 'onOpen', class: 'card-tile--door', when: 'the whole tile opens the thing: coral name and frame on hover and focus' },
            { name: 'clamp', prop: 'clamp', class: 'card-tile-text--clamp', when: 'a description cut after two lines' },
            { name: 'lines', prop: 'lines', class: 'card-tile-lines', when: 'named counts under the meta line (a place and its workspaces)' },
            { name: 'section', prop: 'tone="section"', class: 'card-section', when: 'an older Settings group under the thick rule, no frame (Jouni\'s decision "Classic cards")' },
            { name: 'wide section', prop: 'tone="section" wide', class: 'card-section--wide', when: 'a section that spans the grid' },
            { name: 'section in a row', prop: 'tone="section" inRow', class: 'card-section--in-row', when: 'a section inside a list row' },
            { name: 'panel', prop: 'tone="panel"', class: 'card-panel', when: 'one part of the overview: its headline over its content' },
            { name: 'panel door', prop: 'tone="panel" onOpen', class: 'card-panel-title--door', when: 'the headline opens its tab' },
            { name: 'figure', prop: 'tone="figure"', class: 'card-figure', when: 'a number that opens its tab, a small grey word beside it' },
            { name: 'grid', prop: 'CardGrid cols', class: 'card-grid', when: 'the tiles in three, two or one columns, as many as fit, sections, panels or figures' },
            { name: 'strip', prop: 'CardGrid cols="strip"', class: 'card-grid--strip', when: 'a few tiles in one line that scrolls sideways; a framed tile in it is small and soft: a hairline frame with the small corner on the card ground, its name in semibold, its meta line small and grey in the body face, the surface ground under the pointer (the app catalogue\'s active extensions)' },
            { name: 'classic', prop: 'title, subtitle (no tone, no name)', class: 'card', when: 'the classic shell\'s card' },
            { name: 'glass', prop: 'variant="glass"', class: 'card-glass', when: 'the classic card on the glass ground' },
        ],
        example: { tone: 'framed', name: 'Firefox on this laptop', meta: 'push · since 2026-09-02', doors: 'Send a test' },
        note: 'card.css holds the classic card and its kin (the content group, the stat card, the category card, moved from theme.css) and, at its end, the tile, grid, section, panel and figure of the Card component. Replaced the Item grid (item-grid.css), the Figure door (figure-door.css), the App cards (app-cards.css), the Notifications device card and the overview\'s .pf-home-card. CardGrid cols "strip" came with appcat (2026-09-27): it draws the old app catalogue\'s active extensions bar (#cortex-bar-grid and its .cortex-mini-card tiles).',
    },
    {
        id: 'badge', name: 'Badge', kind: 'component', status: 'active',
        summary: 'The classic badge: a small rounded word in capitals, in a tint class.',
        module: null, sheet: '/css/components/badge.css', classes: ['badge'],
        data: { shape: '<span class="badge badge-success">…</span>', fields: { children: 'the word' } },
        useFor: ['A state in the classic shell and in the profile (the design lab\'s Status decision covers it).'],
        variants: [], example: { children: 'active' },
    },
    {
        id: 'pill', name: 'Pill', kind: 'component', status: 'active',
        summary: 'The rounded shape primitive of the classic shell.',
        module: null, sheet: '/css/components/pill.css', classes: ['pill'],
        data: { shape: '<span class="pill">…</span>', fields: { children: 'the word' } },
        useFor: ['A rounded chip in the classic shell.'],
        variants: [], example: { children: 'pill' },
    },
    {
        id: 'seg', name: 'Segmented control', kind: 'component', status: 'active',
        summary: 'A row of joined buttons, the chosen one filled.',
        module: null, sheet: '/css/components/seg.css', classes: ['seg', 'seg-btn'],
        data: { shape: '<div class="seg"><button class="seg-btn active">…</button>…</div>', fields: { children: 'the choices' } },
        useFor: ['Choosing one of a few settings (the design lab\'s Choice decision covers it).'],
        variants: [], example: {},
    },
    {
        id: 'start-page', name: 'StartPageSetting', kind: 'component', status: 'active',
        summary: 'The start page setting: where a person lands after signing in (the home, the chat, or settings and controls), in words and a row of tabs, the chosen one on the sun. It reads and stores the choice on the account itself.',
        module: '/components/StartPageSetting.js', sheet: '/css/components/start-page.css',
        data: { shape: 'StartPageSetting({ dialog, footer, className })', fields: { dialog: 'inside a settings dialog, spaced as the dialog spaces it', footer: 'at the foot of a page under the heavy rule, words and tabs on one line (the Settings overview)', className: 'a class of the caller\'s own, kept for older callers; a page passes dialog or footer instead' } },
        useFor: ['The home\'s settings dialog and the profile\'s settings.'],
        variants: [
            { name: 'dialog', prop: 'dialog', when: 'the home\'s settings dialog (.poster-settings-startpage, settings-stack.css)' },
            { name: 'footer', class: 'start-page--footer', prop: 'footer', when: 'the foot of the Settings overview' },
        ], example: {},
    },
    {
        id: 'status-dot', name: 'StatusDot', kind: 'component', status: 'active',
        summary: 'A small coloured dot that says a state.',
        module: '/components/StatusDot.js', sheet: '/css/components/status-dot.css',
        data: { shape: 'StatusDot({ status, title })', fields: { status: 'ok | warn | error | off', title: 'what the state is' } },
        useFor: ['Beside a name whose state matters at a glance.'],
        variants: [], example: { status: 'ok', title: 'Running' },
    },
    {
        id: 'presence-dot', name: 'PresenceDot', kind: 'component', status: 'active',
        summary: 'Whether someone is here now: a dot, and a word when asked.',
        module: '/components/PresenceDot.js', sheet: '/css/components/presence-dot.css',
        data: { shape: 'PresenceDot({ ghii, status, size, label, title })', fields: { status: 'online | away | offline', label: 'show the word' } },
        useFor: ['Beside a person or an agent in a list.'],
        variants: [], example: { status: 'online', label: true },
    },
    {
        id: 'key-value-row', name: 'KeyValueRow', kind: 'component', status: 'unused',
        summary: 'One named fact on a line: its label, its value, and a badge when asked.',
        module: '/components/KeyValueRow.js', sheet: '/css/components/key-value-row.css',
        data: { shape: 'KeyValueRow({ label, value, badge, mono })', fields: { label: 'what it is', value: 'the fact', mono: 'set the value in typewriter letters' } },
        useFor: ['A detail list in the classic shell.'],
        variants: [], example: { label: 'Node', value: 'aimeat-local-001-dev', mono: true },
        note: 'No page draws it since 2026-09-27: its one caller, an organism document\'s dates, draws the Facts (components/Facts.js). The module and its sheet stay, and components/index.js still re-exports it, until Jouni says keep or delete.',
    },
    {
        id: 'pagination', name: 'Pagination', kind: 'component', status: 'unused',
        summary: 'The way to the next page of a list: previous and next with the page, or one load-more button.',
        module: '/components/Pagination.js', sheet: '/css/components/pagination.css',
        data: { shape: 'Pagination({ page, totalPages, onPage }) · LoadMore({ onMore, loading, label })', fields: { page: 'the page shown', totalPages: 'how many' } },
        useFor: ['Under a long list in the classic shell.'],
        variants: [], example: { page: 2, totalPages: 5 }, note: 'No page draws it today: the lists page themselves. Kept until Jouni says keep or delete.',
    },
    {
        id: 'collapsible', name: 'Collapsible', kind: 'component', status: 'active',
        summary: 'A section that opens and closes under its heading.',
        module: '/components/Collapsible.js', sheet: '/css/components/collapsible.css',
        data: { shape: 'Collapsible({ title, open, onToggle, children })', fields: { title: 'the heading', children: 'what opens' } },
        useFor: ['Content a person reads only when they ask for it.'],
        variants: [], example: { title: 'Details', open: true },
    },
    {
        id: 'data-table', name: 'DataTable', kind: 'component', status: 'active',
        summary: 'Rows and columns of records: grey capitals over the columns, a hairline under each row, a soft ground under the pointer. The compact table is closer and quieter, for choosing rows inside a dialog.',
        module: '/components/DataTable.js', sheet: '/css/components/data-table.css',
        data: {
            shape: 'DataTable({ headers, rows, scroll, compact, className })',
            fields: {
                headers: 'the column names', rows: 'the records, one array each; a cell is a value, or { text, mono, title }',
                scroll: 'the table in a box that scrolls after 600px',
                compact: 'a table to choose from inside a dialog: ink words at .85rem in close cells, no ground under the pointer, a check box flush in its cell, a status word and a choice drawn small',
                className: 'a class of the caller\'s own, kept for older callers',
            },
        },
        useFor: ['Records compared column by column (admin).', 'Rows a person ticks and chooses from inside a dialog (compact).'],
        variants: [
            { name: 'compact', prop: 'compact', class: 'data-table--compact', when: 'a table to choose from inside a dialog, such as the app catalogue\'s backup restore' },
        ],
        example: { headers: ['Name', 'State'], rows: [['alpha', 'on'], ['beta', 'off']] },
        note: 'compact came with appcat (2026-09-27): it draws the old app catalogue\'s backup import table (.backup-table).',
    },
    {
        id: 'usage-chart', name: 'UsageChart', kind: 'component', status: 'active',
        summary: 'A bar or line chart of use over time.',
        module: '/components/UsageChart.js', sheet: '/css/components/usage-chart.css',
        data: { shape: 'UsageChart({ type, labels, datasets, stacked, height, legend, yFormat })', fields: { labels: 'the x axis', datasets: 'the series' } },
        useFor: ['Use over time in the admin and the profile.'],
        variants: [], example: {},
    },
    {
        id: 'divider', name: 'Section divider', kind: 'component', status: 'unused',
        summary: 'A quiet line with a word between two sections.',
        module: null, sheet: '/css/components/divider.css', classes: ['section-divider'],
        data: { shape: '<div class="section-divider">…</div>', fields: { children: 'the word' } },
        useFor: ['Between two sections of the classic shell.'],
        variants: [], example: { children: 'or' }, note: 'No page draws it today. Kept until Jouni says keep or delete.',
    },
    {
        id: 'form-field', name: 'FormField', kind: 'component', status: 'active',
        summary: 'Form fields of the classic shell: the input, the textarea and the select, the form group with its label and its hint.',
        module: '/components/FormField.js', sheet: '/css/components/form-field.css',
        data: { shape: 'FormField({ label, hint, children, className })', fields: { label: 'what to write', hint: 'a line of help', children: 'the input' } },
        useFor: ['A form in the classic shell. The poster pages use TextInput.'],
        variants: [], example: { label: 'Name', hint: 'Lower-case letters and dashes.' }, note: 'Themes & Styles draws it (2026-09-24): a label and a hint around a text field, a choice or the CSS editor. The classic forms still write .input-field and .form-group as markup in page code.',
    },
    {
        id: 'search-bar', name: 'SearchBar', kind: 'component', status: 'active',
        summary: 'A field with its icon and its clear button.',
        module: '/components/SearchBar.js', sheet: '/css/components/search-bar.css',
        data: { shape: 'SearchBar({ value, onInput, placeholder, onSubmit, ariaLabel })', fields: { value: 'what is searched', placeholder: 'the hint in the field' } },
        useFor: ['Above a list that can be searched.'],
        variants: [], example: { placeholder: 'Search' },
    },
    {
        id: 'spinner', name: 'Spinner', kind: 'component', status: 'active',
        summary: 'The spinner and the loading line beside it.',
        module: '/components/Spinner.js', sheet: '/css/components/spinner.css',
        data: { shape: 'Spinner({ text })', fields: { text: 'what is loading' } },
        useFor: ['While a list or a page is loading.'],
        variants: [], example: { text: 'Loading…' },
    },
    {
        id: 'empty-state', name: 'EmptyState', kind: 'component', status: 'active',
        summary: 'What stands where a list has nothing, or has not arrived yet: by default a faint icon, a bold title, a grey italic line and an action, centred. The start tone sets it at the list\'s left edge with a large faint icon and the title in the poster face; the line tone is one semibold line in ink with a grey hint under it; a spinning ring stands in the icon\'s place while the list loads.',
        module: '/components/EmptyState.js', sheet: '/css/components/empty-state.css',
        data: {
            shape: 'EmptyState({ icon, title, text, action, children, start, loading, ruled, line, hint, aside })',
            fields: {
                icon: 'a large faint sign over the words', title: 'what is empty', text: 'what to do', action: 'a button or a link under the words',
                children: 'any body instead of text, kept for older callers',
                start: 'the empty state of a poster list, at the list\'s start: left aligned, the icon large with a faint coral glow, the title in the poster face',
                loading: 'the list is still being fetched: a ring spins in the icon\'s place (still for a person who asks for less motion), said to a screen reader as a status',
                ruled: 'a heavy rule over it',
                line: 'the empty state that stands in for a list under its headline: the words in ink and semibold, no icon, the ring centred while it waits',
                hint: 'with line: the grey line under the words, held to 460px',
                aside: 'with start: a small faint line under the words (which files a list takes)',
            },
        },
        useFor: ['An empty list in the classic shell (the poster pages say it with QuietNote).', 'An empty or loading list in the app catalogue (start, line, loading).'],
        variants: [
            { name: 'start', prop: 'start', class: 'empty--start', when: 'a poster list with nothing in it yet: left aligned, a large faint icon, the title in the poster face' },
            { name: 'loading', prop: 'loading', class: 'empty-ring', when: 'the list is still being fetched: a coral ring spins where the icon was' },
            { name: 'ruled', prop: 'ruled', class: 'empty--ruled', when: 'the empty state stands under a heavy rule, as a list would' },
            { name: 'line', prop: 'line', class: 'empty--line', when: 'one semibold line in ink where a list under its headline would be' },
            { name: 'hint', prop: 'line hint', class: 'empty-hint', when: 'a grey line under the words of the line tone that says what fills the list' },
            { name: 'aside', prop: 'start aside', class: 'empty-aside', when: 'a small faint line under the words of the start tone' },
        ],
        example: { title: 'Nothing here yet', text: 'Your records appear here.' },
        note: 'start, loading, ruled, line, hint and aside came with appcat (2026-09-27): they draw the old app catalogue\'s empty and loading blocks (.empty-state, .cat-spinner, .view-empty, .view-empty-hint and the list\'s .empty-formats line). hint takes its look only with line, aside only with start.',
    },
    {
        id: 'text-utility', name: 'Muted text', kind: 'component', status: 'active',
        summary: 'The muted and meta text utilities.',
        module: null, sheet: '/css/components/text-utility.css', classes: ['text-muted', 'meta'],
        data: { shape: '<span class="text-muted">…</span>', fields: { children: 'the quieter words' } },
        useFor: ['A quieter line in the classic shell.'],
        variants: [], example: { children: 'updated 2 hours ago' },
    },
    {
        id: 'toggle-switch', name: 'ToggleSwitch', kind: 'component', status: 'active',
        summary: 'A switch that is on or off.',
        module: '/components/ToggleSwitch.js', sheet: '/css/components/toggle-switch.css',
        data: { shape: 'ToggleSwitch({ checked, onChange, label })', fields: { checked: 'on or off', label: 'what it switches' } },
        useFor: ['A setting that is on or off.'],
        variants: [], example: { checked: true, label: 'Notifications' },
    },
    {
        id: 'site-footer', name: 'Site footer', kind: 'component', status: 'active',
        summary: 'The footer at the end of every view, and the older centred footer.',
        module: null, sheet: '/css/components/site-footer.css', classes: ['site-footer', 'site-footer-row'],
        data: { shape: 'SiteFooter in spa.html', fields: { links: 'the documents and the machine links' } },
        useFor: ['Drawn by spa.html at the end of every view.'],
        variants: [], example: {},
    },
    {
        id: 'alert', name: 'Alert', kind: 'component', status: 'active',
        summary: 'A line that says something went right or wrong, in its tone.',
        module: '/components/Alert.js', sheet: '/css/components/alert.css',
        data: { shape: 'Alert({ type, message, onDismiss })', fields: { type: 'info | success | warn | error', message: 'what happened' } },
        useFor: ['The result of an action in the classic shell.'],
        variants: [], example: { type: 'success', message: 'Saved.' },
    },
    {
        id: 'toast', name: 'Toast', kind: 'component', status: 'active',
        summary: 'A passing word in a box at the foot of the screen, drawn in the poster face, above an open dialog too.',
        module: '/components/Toast.js', sheet: '/css/components/toast.css',
        data: {
            shape: 'const { showToast, ToastContainer } = useToast(); showToast(message, kind) · ToastBox({ toast, hold, role }) · normalizeToastType(kind)',
            fields: {
                message: 'what happened', kind: 'success | error | info | warning (true means error)',
                toast: 'ToastBox: { msg, type }, for a view that keeps its own toast state', hold: 'ToastBox: the pill that stays six seconds (the home and the pop-out windows)',
                role: 'ToastBox: what a screen reader is told (status, or alert for a failure)',
            },
        },
        useFor: ['A result that does not need a place on the page.'],
        variants: [
            { name: 'success', class: 'toast-success', prop: 'showToast(msg) | toast.type="success"', when: 'it worked' },
            { name: 'error', class: 'toast-error', prop: 'showToast(msg, "error")', when: 'it did not work' },
            { name: 'warn', class: 'toast-warn', prop: 'showToast(msg, "warning")', when: 'it worked, with something to look at' },
            { name: 'hold', class: 'toast-hold', prop: 'ToastBox hold', when: 'the pill that stays six seconds' },
        ], example: {},
    },
    {
        id: 'section-header', name: 'Section header (classic)', kind: 'component', status: 'active',
        summary: 'The classic section and page headers: a title with its supporting line.',
        module: null, sheet: '/css/components/section-header.css', classes: ['section-title', 'section-desc', 'page-title', 'page-subtitle'],
        data: { shape: '<h2 class="section-title">…</h2><p class="section-desc">…</p>', fields: { title: 'the heading', desc: 'the line under it' } },
        useFor: ['The classic shell. The poster pages use PageIntro and the section slab.'],
        variants: [], example: {},
    },
    {
        id: 'dialog', name: 'Modal (dialog)', kind: 'component', status: 'active',
        summary: 'The one dialog of the site: a header slab with the title and the close square, a body that scrolls, a footer for the actions; a sheet at the bottom on a phone.',
        module: '/components/Modal.js', sheet: '/css/components/dialog.css',
        data: {
            shape: 'Modal({ open, onClose, title, titleRef, children, footer, footerStart, showClose, size, guard, className, bodyClass, leading }) · ConfirmDialog({ open, onClose, onConfirm, title, message, confirmLabel, cancelLabel, danger, className, leading }) · useConfirm()',
            fields: {
                title: 'the header', titleRef: 'the thing the dialog is about (a filename), after the title in the typewriter face',
                children: 'the body', footer: 'the actions', footerStart: 'a side door at the footer\'s other end',
                showClose: 'the X (true by default)', size: 'sm 440 | md 560 | lg 840 | xl 1080',
                guard: 'Escape and the page behind do not close it once something has been typed (true by default)',
                leading: '"normal": the dialog reads at the browser\'s own line spacing, as the app catalogue\'s dialogs do',
            },
        },
        useFor: ['A question or a form over the page.'],
        variants: [
            { name: 'medium', class: 'dlg--md', when: 'a wider dialog' },
            { name: 'normal leading', prop: 'leading="normal"', when: 'the dialog at the browser\'s own line spacing; its rules are in modal.css (the modal entry)' },
            { name: 'title reference', prop: 'titleRef', when: 'a filename after the title; its rule is in modal.css (the modal entry)' },
        ],
        example: { title: 'Settings' },
        note: 'On 2026-09-27 appcat added `leading` and `titleRef` (the old app catalogue\'s dialog reading and its .aga-app-ref). Their rules are in css/components/modal.css, not in dialog.css, because dialog.css is also copied into the old catalogue\'s page at build time; the modal entry shows them.',
    },
    {
        id: 'margin-pattern', name: 'Margin pattern', kind: 'component', status: 'active',
        summary: 'The personal pattern in the page margins of the home, the chat and the settings pages.',
        module: '/js/margin-pattern.js', sheet: '/css/components/margin-pattern.css',
        data: { shape: '<html data-margin-pattern="a".."h">', fields: { pattern: 'the person\'s choice' } },
        useFor: ['Set by the person in the home\'s settings; drawn in the margins.'],
        variants: [], example: {},
    },
    {
        id: 'notification-bell', name: 'NotificationBell', kind: 'component', status: 'active',
        summary: 'The bell in the top bar, its count and its list with inline actions.',
        module: '/components/NotificationBell.js', sheet: '/css/components/top-bar.css', classes: ['notif-bell', 'notif-bell-btn', 'notif-item'],
        data: { shape: 'NotificationBell({ t, onNavigate })', fields: { t: 'the translator', onNavigate: 'how a link opens' } },
        useFor: ['In the top bar of every signed-in page.'],
        variants: [], example: {},
    },
    {
        id: 'open-items-button', name: 'OpenItemsButton', kind: 'component', status: 'active',
        summary: 'The open items mark and count in the top bar.',
        module: '/components/OpenItemsButton.js', sheet: '/css/components/open-items.css', classes: ['open-items-btn'],
        data: { shape: 'OpenItemsButton({ t, onNavigate })', fields: { t: 'the translator', onNavigate: 'how the list opens' } },
        useFor: ['In the top bar of every signed-in page.'],
        variants: [], example: {},
    },
    {
        id: 'agent-consent', name: 'AgentConsent', kind: 'component', status: 'active',
        summary: 'An agent asking to connect: who it is, what it may do, and approve or deny.',
        module: '/components/AgentConsent.js', sheet: '/css/components/agent-consent.css', classes: ['agent-consent', 'agent-consent-card'],
        data: { shape: 'AgentConsent({ requests, onApprove, onDeny, busyCode, variant })', fields: { requests: 'the pending device requests' } },
        useFor: ['Where a person approves an agent (the home and the profile).'],
        variants: [], example: {},
        note: 'Its own sheet since 2026-09-27: the rules moved unchanged under its own names (.agent-consent-*) from views/profile.css, profile-poster.css and step-card.css; the Settings rules keep their .pf scope, so the home draws it as before.',
    },
    {
        id: 'contact-card', name: 'ContactCard', kind: 'component', status: 'active',
        summary: 'The node\'s own people, as a card in the dashed aside.',
        module: '/components/ContactCard.js', sheet: '/css/components/contact-card.css', classes: ['contact-card'],
        data: { shape: 'ContactCard()', fields: {} },
        useFor: ['The front page and the help page.'],
        variants: [], example: {},
    },
    {
        id: 'display-prefs-fields', name: 'DisplayPrefsFields', kind: 'component', status: 'active',
        summary: 'The region and time zone fields.',
        module: '/components/DisplayPrefsFields.js', sheet: '/css/components/display-prefs-fields.css', classes: ['display-prefs-field'],
        data: { shape: 'DisplayPrefsFields({ region, timezone, onChange })', fields: { region: 'the region', timezone: 'the time zone' } },
        useFor: ['The profile\'s settings.'],
        variants: [], example: {},
        note: 'Its own sheet since 2026-09-27 (.display-prefs-field, moved unchanged from views/profile.css .pf-edit-label and profile-poster.css); the controls are the field kit.',
    },
    {
        id: 'inbox-link', name: 'InboxLink', kind: 'component', status: 'active',
        summary: 'A link that opens the inbox with a message addressed.',
        module: '/components/InboxLink.js', sheet: '/css/components/page-base.css',
        data: { shape: 'InboxLink({ to, subject, title, className, children })', fields: { to: 'the address', subject: 'the subject', className: 'the look the caller gives it' } },
        useFor: ['Wherever a person is invited to write to someone.'],
        variants: [], example: {}, note: 'It draws no look of its own: it is a link that wears the caller\'s class.',
    },
    {
        id: 'json-view', name: 'JsonView', kind: 'component', status: 'active',
        summary: 'A stored value shown as readable, coloured JSON.',
        module: '/components/JsonView.js', sheet: '/css/components/json-view.css', classes: ['json-view-block'],
        data: { shape: 'JsonValue({ value }) · JsonNode({ value })', fields: { value: 'any stored value' } },
        useFor: ['A record\'s raw value in the profile.', 'A stored value opened under its row, as the library draws it: a task\'s memory value, an ecosystem app\'s data value and a guidance body; the box around it keeps only its place.'],
        variants: [], example: {},
    },
    {
        id: 'link-preview', name: 'LinkPreview', kind: 'component', status: 'active',
        summary: 'A card for a link in a message: its site, title and picture.',
        module: '/components/LinkPreview.js', sheet: '/css/components/link-preview.css', classes: ['link-preview'],
        data: { shape: 'LinkPreview({ url, onDismiss }) · MessageLinkPreviews({ msg })', fields: { url: 'the link' } },
        useFor: ['Under a message that carries a link.'],
        variants: [], example: {},
    },
    {
        id: 'memory-embed', name: 'MemoryEmbed', kind: 'component', status: 'active',
        summary: 'A stored record shown inside a text.',
        module: '/components/MemoryEmbed.js', sheet: '/css/components/markdown.css', classes: ['md-mem-value'],
        data: { shape: 'MemoryEmbed({ spec })', fields: { spec: 'which record, and how' } },
        useFor: ['Inside a Markdown text that names a record.'],
        variants: [], example: {},
    },
    {
        id: 'mermaid', name: 'Mermaid', kind: 'component', status: 'active',
        summary: 'A diagram drawn from its text.',
        module: '/components/Mermaid.js', sheet: '/css/components/mermaid.css', classes: ['mermaid-diagram'],
        data: { shape: 'Mermaid({ chart })', fields: { chart: 'the diagram\'s text' } },
        useFor: ['A diagram inside a text.'],
        variants: [], example: {},
    },
    {
        id: 'offer-card-view', name: 'Offer card parts', kind: 'component', status: 'unused',
        summary: 'An offer\'s badges, example and requirements.',
        module: '/components/offer-card-view.js', sheet: '/css/components/offer-card-view.css', classes: ['offer-card-badges'],
        data: { shape: 'OfferBadges({ offer }) · OfferExample({ offer }) · OfferRequirements({ offer })', fields: { offer: 'the offer' } },
        useFor: ['The offers page and an offer\'s own page.'],
        variants: [], example: {}, note: "No routed page imports it today (the offers view draws its own). Kept until Jouni says keep or delete." 
    },
];
