/**
 * @file src/services/ui-library/entries-page.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Catalogue entries for the parts a page is built from: its frame and headline, the
 *   masthead, the bands and the rows inside them, the record of what happened, the settings dialog's
 *   insides, the task chooser and an operator's own passages. The purpose half only;
 *   facts.generated.ts carries what the files say.
 * @structure PAGE_ENTRIES
 * @usage import { PAGE_ENTRIES } from './entries-page.js';
 * @version-history
 *   v1.8.0 — 2026-10-03 — PageStart: what a page is for, what to do first and what happens next (guidance part B).
 *   v1.7.0 — 2026-09-27 — SettingsStack's SettingsSection and SwatchPicker's pattern (the home's settings dialog
 *     passes meanings, not classes).
 *   v1.6.0 — 2026-09-26 — The Timeline is every list of what happened in Settings & Controls (Jouni's decision "Activity log", a unification).
 *   v1.5.0 — 2026-09-26 — A list of things to do or of steps is the numbered list (components/NumberedIndex.js: IndexList with IndexItem, or IndexStep for a step that opens nothing): the overview's next steps with the line under each name and the first on the sun, the Wallet key steps, a calibration run's proposals, the MCP and Agents connect steps, the basic agents, a server's setup steps (the number said once), the ecosystem steps out of their grey box, the decision rules' order and the notes of your own AI use; a place keeps only its margin (a unification: Jouni's decision "Numbered list").
 *   v1.4.0 — 2026-09-26 — The Masthead takes a page's own lines under the address and a picture that opens something; the Settings overview draws it (Jouni's decision "Person head").
 *   v1.3.0 — 2026-09-25 — The hint entry: the look most Settings & Controls tabs draw, its classes (drawn as markup inside a row), and the slab tone (UI consolidation phase 5, a unification).
 *   v1.2.0 — 2026-09-24 — Specimen is active: Themes & Styles draws it too.
 *   v1.1.0 — 2026-09-23 — DiagonalBand deleted with ChatDoor (Jouni's decision); Specimen added.
 *   v1.0.0 — 2026-09-23 — Initial (UI consolidation phase 1).
 */
import type { UiEntryWritten } from './types.js';

const one = (children: string) => ({ children });

export const PAGE_ENTRIES: UiEntryWritten[] = [
    {
        id: 'page-frame', name: 'PageFrame', kind: 'component', status: 'active',
        summary: 'The page itself: a wide paper column, or a narrow one for reading, or a loading state.',
        module: '/components/PageFrame.js', sheet: '/css/components/page-frame.css',
        data: { shape: 'PageFrame({ width, loading, children })', fields: { width: "'wide' (default) or 'narrow'", loading: 'true while the page has nothing to show yet', children: 'the page' } },
        useFor: ['The outermost element of a page in the poster look.'],
        variants: [{ name: 'narrow', class: 'poster-page--narrow', prop: "width='narrow'", when: 'a page that is read rather than worked in' }],
        example: { width: 'wide', children: '…' },
    },
    {
        id: 'page-intro', name: 'PageIntro', kind: 'component', status: 'active',
        summary: 'A page\'s own headline and one line under it.',
        module: '/components/PageIntro.js', sheet: '/css/components/page-intro.css',
        data: { shape: 'PageIntro({ title, sub })', fields: { title: 'the page headline', sub: 'one line on what the page is for' } },
        useFor: ['The first thing on a page that has no masthead.'],
        variants: [],
        example: { title: 'What has happened', sub: 'Everything your agents and you did here, newest first.' },
    },
    {
        id: 'error-note', name: 'ErrorNote', kind: 'component', status: 'active',
        summary: 'What went wrong, in a danger frame, with a hint and a way forward.',
        module: '/components/ErrorNote.js', sheet: '/css/components/error-note.css',
        data: { shape: 'ErrorNote({ text, hint, children }) · ErrorNoteFallback({ onClick, children })', fields: { text: 'what went wrong, in words', hint: 'what to do about it', children: 'an optional way forward (ErrorNoteFallback)' } },
        useFor: ['A refusal a person can act on. Name what was missing rather than "try again".'],
        variants: [],
        example: { text: 'I could not find a page in what you pasted.', hint: 'Your text is still in the box.' },
    },
    {
        id: 'action-row', name: 'ActionRow', kind: 'component', status: 'active',
        summary: 'A row of actions that becomes one per line on a phone.',
        module: '/components/ActionRow.js', sheet: '/css/components/action-row.css',
        data: { shape: 'ActionRow({ children })', fields: { children: 'the buttons, the next move first' } },
        useFor: ['The actions at the foot of a step or a card.'],
        variants: [],
        example: one('<button class="btn-primary">Here is my welcome mat</button>'),
    },
    {
        id: 'hint', name: 'Hint', kind: 'component', status: 'active',
        summary: 'A quiet line of help near a control or a section: the body face, small and grey, with a gap above.',
        module: '/components/Hint.js', sheet: '/css/components/hint.css', classes: ['poster-hint', 'poster-hint--slab'],
        data: { shape: 'Hint({ children }) · <span class="poster-hint">…</span> inside a row · <small class="poster-hint poster-hint--slab">…</small>', fields: { children: 'the help sentence' } },
        useFor: ['One sentence that tells what a control does or what happens next.', 'A grey paragraph that explains a section.'],
        variants: [{ name: 'slab', class: 'poster-hint--slab', when: 'beside a loud action: the mono line that says what it does, or why it cannot be pressed yet' }],
        example: one('You can change the name later.'),
        note: 'Hint draws only the plain hint. Since 2026-09-27 hint.css also holds rules that Note (components/Note.js, entry \'note\') draws for appcat, the app catalogue rebuilt on components: the hint sizes small, intro, note and text and the chapter line (.poster-hint--small, --intro, --note, --text, --chapter), the caption (.note-caption*), the report (.note-report*) and the state line (.state-line*). Hint takes none of them; a page reaches them through Note.',
    },
    {
        id: 'help-tip', name: 'HelpTip', kind: 'component', status: 'active',
        summary: 'A question mark beside a setting a person cannot be expected to know: a Tooltip while the pointer or the focus is on it, and an ExplainDialog when pressed. Both read the locale\'s explain.<term>.*, so a page passes only the term.',
        module: '/components/HelpTip.js', sheet: '/css/components/help-tip.css',
        classes: ['help-tip', 'help-tip-button', 'field-label-row'],
        data: {
            shape: 'HelpTip({ term, label }) · HelpLabel({ term, label, children }) · a field of the family: TextField({ label, help: term, … }) · Check({ help }) · SettingLine({ help })',
            fields: {
                term: 'the explanation\'s name: the words are the locale\'s explain.<term>.* (title, short, what, range, low, high, lowLabel, highLabel, ex1 … ex6, tip)',
                label: 'the setting\'s name on the page, used when the locale gives no title',
                children: 'HelpLabel: the label as drawn (a Facts row\'s name, a heading\'s words, a Label block); the question mark stands after it',
            },
        },
        useFor: ['Explain a setting whose name says nothing to a person who is not an expert: temperature, top P, a token limit.', 'Any field of a form, by giving the field `help`: the question mark stands after its row label.'],
        variants: [],
        example: { term: 'ai.temperature' },
        note: 'The explanation is locale data, never words a page writes: add explain.<term>.* to en, fi and es. The button is the icon button of poster.css made 20px; Field draws it beside its label when given `help` (field-label-row), outside the <label>, because a button inside a label would be a second control it names.',
    },
    {
        id: 'tooltip', name: 'Tooltip', kind: 'component', status: 'active',
        summary: 'A short explanation beside a control while the pointer rests on it or the focus is in it: a dark block with a small sun heading, the words, a quiet line under them, and a pointer towards the control.',
        module: '/components/Tooltip.js', sheet: '/css/components/tooltip.css',
        classes: ['tooltip-anchor', 'tooltip', 'tooltip--below', 'tooltip-title', 'tooltip-more', 'tooltip-said'],
        data: {
            shape: 'Tooltip({ text, title, more, quiet, children })',
            fields: {
                text: 'the explanation, one or two sentences; without it the control stands alone',
                title: 'the small heading over it: the name of the thing',
                more: 'a quiet line under it: what pressing the control gives',
                quiet: 'keeps it hidden while what the control opened is in front of it',
                children: 'the one control it describes (aria-describedby is set on it)',
            },
        },
        useFor: ['Explain an icon button or a short control in a sentence, without taking room on the page.'],
        variants: [{ name: 'below', class: 'tooltip--below', when: 'the window has no room above the control: the tooltip opens under it, its pointer up' }],
        example: { title: 'Temperature', text: 'How much the answers vary. A value from 0 to 2.', more: 'Click for examples.' },
        note: 'It stands against the window (position: fixed), so an ancestor\'s overflow cannot cut it. WCAG 1.4.13: Escape hides it, the pointer can move onto it, it stays until the pointer or the focus leaves, and scrolling hides it. The words describe the control whether it is shown or not. A theme reaches it through the corner and the action\'s shadow.',
    },
    {
        id: 'explain-dialog', name: 'ExplainDialog', kind: 'component', status: 'active',
        summary: 'The dialog that explains one setting in full: what it does, its range and default, what a lower and a higher value give, examples, and when to change it.',
        module: '/components/ExplainDialog.js', sheet: '/css/components/explain-dialog.css',
        classes: ['explain-examples', 'explain-when'],
        data: {
            shape: 'ExplainDialog({ term, label, open, onClose }) · explainOf(term, part)',
            fields: {
                term: 'the explanation\'s name: explain.<term>.* in the locale (title, what, range, low, high, lowLabel, highLabel, ex1 … ex6, tip), each part drawn only when it exists',
                label: 'the setting\'s name on the page, the title when the locale gives none',
                open: 'whether it is open',
                onClose: 'called by the X, Escape, the page behind and Close',
            },
        },
        useFor: ['Explain a setting in full from a question mark, a link or a menu row.'],
        variants: [],
        example: { term: 'ai.temperature' },
        note: 'The site\'s Modal with the library\'s parts inside: Note lead, Facts, the row label and the small dashed aside. Its own sheet only spaces the examples and the aside.',
    },
    {
        id: 'page-start', name: 'PageStart', kind: 'component', status: 'active',
        summary: 'The start of a page for a person who has not used it yet: one quiet block under the head that says what the page is for, gives one first action (a prompt to paste into their own AI, and the page\'s own button for the same) and says what happens next. It folds to one line, and the browser remembers that per page.',
        module: '/components/PageStart.js', sheet: '/css/components/page-start.css',
        data: {
            shape: 'PageStart({ id, vars, purpose, prompt, next, action, link, done }) · in a Settings page: SettingsPage({ start })',
            fields: {
                id: 'the page: its words are the locale\'s pageStart.<id>.* (purpose, prompt, next, action, link), and its fold is remembered under it',
                vars: 'the values the prompt\'s {placeholders} take (an address)',
                purpose: 'what the person gets here, one sentence (the locale\'s words when omitted)',
                prompt: 'the text the person copies into their own AI (the locale\'s words when omitted)',
                next: 'what follows the first action, one sentence (the locale\'s words when omitted)',
                action: '{ onClick | href | copy, label }: the page\'s own button for the same first action',
                link: '{ onClick | href, label }: a way on after the purpose sentence',
                done: 'true when the first action is done (it starts folded), null while the page does not know yet, false or absent: open; the person\'s own choice wins',
            },
        },
        useFor: ['The top of a main page a newcomer lands on: memory, organisms, agents, connect your AI, wallet, access, packages, apps, notebook, AI.'],
        variants: [{ name: 'folded', class: 'page-start--folded', prop: 'done or the person\'s choice', when: 'the person has done the first action, or folded it: one line with the way to open it' }],
        example: {
            id: 'memory',
            purpose: 'Memory keeps what every AI you connect should know about you and your work.',
            prompt: 'Remember in my AIMEAT that I [work as a bookkeeper and prefer short answers].',
            next: 'The entry appears on this page, and your connected AIs find it when they need it.',
        },
        note: 'Built from the library\'s parts: Label, Note (lead, hint), Action and PromptCard (its copy in the quiet tone). Its sheet only lays them out: the hairlines above and below, three columns, one column under 900px. The fold is stored in localStorage (aimeat.pageStart.<id>), never on the server.',
    },
    {
        id: 'masthead', name: 'Masthead', kind: 'component', status: 'active',
        summary: 'The top of a person\'s page: the avatar in its frame, the name as a headline, the identity line, and the doors on the right.',
        module: '/components/Masthead.js', sheet: '/css/components/masthead.css',
        data: {
            shape: 'Masthead({ avatarSvg, name, identity, identityTitle, plate, onAvatar, avatarTitle, children }) · MastheadButton({ onClick, children }) · MastheadCog',
            fields: { avatarSvg: 'the avatar as an SVG string', name: 'the person\'s name', identity: 'their address on this node', identityTitle: 'the full identity on hover', plate: 'what a page adds under the address (the Settings overview: this AIMEAT\'s address and its marks)', onAvatar: 'makes the picture a control that opens something', avatarTitle: 'the name of that control', children: 'the doors: links with poster-action, or a MastheadButton' },
        },
        useFor: ['The home, the Settings overview and any page that belongs to one person.'],
        variants: [],
        example: { avatarSvg: '<svg…/>', name: 'Alice', identity: 'alice@aimeat.io', children: 'Settings' },
    },
    {
        id: 'link-line', name: 'LinkLine', kind: 'component', status: 'active',
        summary: 'One sentence with a coral link in it.',
        module: '/components/LinkLine.js', sheet: '/css/components/link-line.css',
        data: { shape: 'LinkLine({ label, href, text })', fields: { label: 'the words before the link', href: 'where it goes', text: 'the link words' } },
        useFor: ['An address a person may want to open or share, said in a sentence.'],
        variants: [],
        example: { label: 'Your welcome mat is at', href: 'https://alice.aimeat.io/mat', text: 'alice.aimeat.io/mat' },
    },
    {
        id: 'stat-line', name: 'StatLine', kind: 'component', status: 'active',
        summary: 'One line with its number set big, or a state dot, over a 3px ink rule (poster.css .poster-stat).',
        module: '/components/StatLine.js', sheet: '/css/components/stat-line.css',
        data: {
            shape: 'StatLine({ href, tone, icon, dot, children }) · statSentence(sentence, placeholder, value)',
            fields: { href: 'where the line leads', tone: "'alert', 'ok' or 'trouble'", icon: 'an optional inline SVG', dot: 'a state dot instead of a number', children: 'the sentence; statSentence sets its number big where the language puts it' },
        },
        useFor: ['A count or a state a person reads at a glance and can open.'],
        variants: [
            { name: 'alert', class: 'poster-stat--alert', prop: "tone='alert'", when: 'something waits for the person' },
            { name: 'ok', class: 'poster-stat--ok', prop: "tone='ok'", when: 'all is well' },
            { name: 'trouble', class: 'poster-stat--trouble', prop: "tone='trouble'", when: 'something is broken' },
        ],
        example: { href: '/v1/inbox', tone: 'alert', children: '3 messages wait for you' },
    },
    {
        id: 'band', name: 'Band', kind: 'component', status: 'active',
        summary: 'A section of a page: the ink headline slab (poster.css .poster-section-title--large) and the rows under it.',
        module: '/components/Band.js', sheet: '/css/components/band.css',
        data: { shape: 'Band({ title, tight, children }) · BandNote({ children })', fields: { title: 'the section headline', tight: 'less space above, for a band the layout engine places', children: 'the rows' } },
        useFor: ['Each section of the home, and each block the layout engine draws with a title.'],
        variants: [{ name: 'tight', class: 'poster-band--tight', prop: 'tight', when: 'a band inside a layout, where the engine sets the rhythm' }],
        example: { title: 'Your things', children: '…' },
    },
    {
        id: 'line-list', name: 'LineList', kind: 'component', status: 'active',
        summary: 'A list of one-line pointers: who, then what they said, cut to one line.',
        module: '/components/LineList.js', sheet: '/css/components/line-list.css',
        data: { shape: 'LineList({ rows, more })', fields: { rows: '[{ id, name, text, href }]', more: 'a sentence for the rows not shown, or null' } },
        useFor: ['Messages or posts where the person only needs to know who and roughly what.'],
        variants: [],
        example: { rows: [{ id: '1', name: 'Bob', text: 'The draft is ready for you to read', href: '/v1/inbox/1' }], more: 'and 4 more' },
    },
    {
        id: 'named-row', name: 'NamedRow', kind: 'component', status: 'active',
        summary: 'A row with its category word in a fixed left column and its content on the right, under a 3px ink rule.',
        module: '/components/NamedRow.js', sheet: '/css/components/named-row.css',
        data: { shape: 'NamedRow({ label, title, stack, children })', fields: { label: 'the category word', title: 'the full category on hover', stack: 'the content one part under another at the row\'s full width', children: 'the row content' } },
        useFor: ['A band that lists several kinds of thing, one kind per row.'],
        variants: [{ name: 'stack', class: 'poster-named-row-body--stack', prop: 'stack', when: 'the row holds a form field, or a list with a way on under it' }],
        example: { label: 'Apps', children: 'ThingLink × n' },
    },
    {
        id: 'thing-link', name: 'ThingLink', kind: 'component', status: 'active',
        summary: 'A thing a person has, as a link: an optional coral count and its name.',
        module: '/components/ThingLink.js', sheet: '/css/components/thing-link.css',
        data: {
            shape: 'ThingLink({ href, n, label, named, newTab }) · ThingChip({ href, label, n, starred, starTitle, onStar })',
            fields: { href: 'where it opens', n: 'a count, or nothing', label: 'its name', named: 'a named thing rather than a count', newTab: 'opens in a new tab', starred: 'ThingChip: kept always visible', onStar: 'ThingChip: toggles the star' },
        },
        useFor: ['Inside a NamedRow: the apps, workspaces or records a person has.'],
        variants: [{ name: 'named', class: 'poster-thing--named', prop: 'named', when: 'one named thing rather than a count of a kind' }],
        example: { href: '/v1/apps', n: 12, label: 'apps' },
    },
    {
        id: 'star-toggle', name: 'StarToggle', kind: 'component', status: 'active',
        summary: 'A star that keeps one thing always visible: hollow and grey when off, on the sun when on. The bright star is the app catalogue\'s favourite: the coloured star when on, the hollow one faint until the pointer comes to it.',
        module: '/components/StarToggle.js', sheet: '/css/components/star-toggle.css',
        data: {
            shape: 'StarToggle({ on, title, onClick, bright })',
            fields: {
                on: 'starred', title: 'what the star does (its tooltip; with bright also its name for a screen reader)', onClick: 'toggle',
                bright: 'the coloured star (⭐) when on and the hollow one (☆) faint when off, a little larger under the pointer',
            },
        },
        useFor: ['Beside a thing in a list that shows only some of them.', 'Beside an app\'s name in the app catalogue, to make it a favourite (bright).'],
        variants: [
            { name: 'on', class: 'poster-star--on', prop: 'on', when: 'the thing is starred' },
            { name: 'bright', class: 'poster-star--bright', prop: 'bright', when: 'a favourite beside a name in a row: the coloured star when on, the hollow one faint until pointed at' },
        ],
        example: { on: true, title: 'Keep this one visible' },
        note: 'bright came with appcat (2026-09-27): it draws the old app catalogue\'s row star (.fav-toggle).',
    },
    {
        id: 'fold-button', name: 'FoldButton', kind: 'component', status: 'active',
        summary: 'A mono coral underlined button: without `on` the action link\'s more tone, with `on` the tab\'s fold tone; the chosen one on the sun.',
        module: '/components/FoldButton.js', sheet: '/css/poster.css', classes: ['poster-action--more', 'poster-tab--fold'],
        data: { shape: 'FoldButton({ on, expanded, onClick, children })', fields: { on: 'given: one choice in a ModeSwitch, true for the chosen one', expanded: 'aria-expanded for a fold', onClick: 'handler', children: 'the words' } },
        useFor: ['"Show all" under a cut list, or one choice in a ModeSwitch.'],
        variants: [{ name: 'on', prop: 'on', when: 'the chosen one (poster.css .poster-tab--fold.is-on)' }],
        example: one('Show all'),
    },
    {
        id: 'mode-switch', name: 'ModeSwitch', kind: 'component', status: 'active',
        summary: 'A small group of fold buttons that chooses what a row shows.',
        module: '/components/ModeSwitch.js', sheet: '/css/components/mode-switch.css',
        data: { shape: 'ModeSwitch({ label, children })', fields: { label: 'what is being chosen, for a screen reader', children: 'FoldButtons' } },
        useFor: ['A row that can show one of two or three lists.'],
        variants: [],
        example: { label: 'Which apps', children: 'FoldButton on: Recent · FoldButton: Mine' },
    },
    {
        id: 'quiet-note', name: 'QuietNote', kind: 'component', status: 'active',
        summary: 'A quiet line where a list has nothing to show.',
        module: '/components/QuietNote.js', sheet: '/css/components/quiet-note.css',
        data: { shape: 'QuietNote({ children })', fields: { children: 'what is empty, and what fills it' } },
        useFor: ['An empty list, said in words.'],
        variants: [],
        example: one('You have not opened any apps yet.'),
        note: 'QuietNote draws only the plain quiet line. Since 2026-09-27 quiet-note.css also holds two cuts that Note (components/Note.js, entry \'note\') draws for appcat, the app catalogue rebuilt on components: kind="quiet" size="small" (.poster-quiet--small, a step smaller and not bold) and kind="quiet" chapter (.poster-quiet--chapter, a chapter\'s small light grey "nothing here" line). QuietNote takes neither; a page reaches them through Note.',
    },
    {
        id: 'numbered-index', name: 'NumberedIndex', kind: 'component', status: 'active',
        summary: 'A numbered list: each row a name with its number and an arrow, a 2px ink rule under it; in the index the open one shows its steps in a record (poster.css .poster-record).',
        module: '/components/NumberedIndex.js', sheet: '/css/components/numbered-index.css',
        data: {
            shape: 'NumberedIndex({ lead, label, tour, children, panel }) · IndexItem({ on, expanded, onClick, first, line, end, children }) · IndexList({ steps, className, children }) · IndexStep({ line, end, children }) · IndexPanel({ what, steps, proof, children })',
            fields: { lead: 'the line above the index', label: 'the list name, for a screen reader', tour: '{ href, label } for a guided tour', children: 'the rows (IndexItem, or IndexStep in a list of steps)', panel: 'the open row\'s IndexPanel', what: 'what the open one is', steps: 'its steps; on IndexList, a list of steps to read', proof: 'how a person knows it worked', line: 'a line under the name that says what the row gives you', first: 'the one to do first', end: 'a word that stands before the arrow' },
        },
        useFor: ['A short set of things a person can learn to do, one opened at a time.', 'Things to do next, under a page\'s own heading (IndexList).', 'A list of steps, or of short notes, in Settings (IndexList steps).'],
        variants: [
            { name: 'with a line', class: 'poster-index-line', prop: 'line', when: 'a line under the name says what the row gives you' },
            { name: 'first', class: 'poster-index-item--first', prop: 'first', when: 'the one to do first: on the sun, every mark dark' },
            { name: 'steps', class: 'poster-index-item--step', prop: 'IndexList steps', when: 'a list of steps or notes: a row that opens nothing' },
        ],
        example: { lead: 'Things to try', rows: ['Make a page', 'Connect an agent'], panel: { what: 'A page with its own address', steps: ['Ask for it', 'Open it'], proof: 'It opens in a new tab.' } },
    },
    {
        id: 'ink-foot', name: 'InkFoot', kind: 'component', status: 'active',
        summary: 'The foot of a page: two facts in paper words on ink, two columns on a desktop and one on a phone, reaching the page\'s edges. With a brand, one small word in the poster face on the sun runs under both facts.',
        module: '/components/InkFoot.js', sheet: '/css/components/ink-foot.css',
        data: {
            shape: 'InkFoot({ brand, children })',
            fields: {
                children: 'two paragraphs',
                brand: 'a word under both facts, across the foot: small spaced poster letters in the sun colour',
            },
        },
        useFor: ['The last thing on a person\'s own page.', 'The foot of the app catalogue, with the node\'s name under the facts (brand).'],
        variants: [
            { name: 'brand', class: 'poster-foot-brand', prop: 'brand', when: 'a name signs the foot under its facts' },
        ],
        example: one('<p>Everything here is yours.</p><p>Nothing is public until you publish it.</p>'),
        note: 'brand came with appcat (2026-09-27): it draws the old app catalogue\'s footer word (.footer-brand).',
    },
    {
        id: 'check-item', name: 'CheckItem', kind: 'component', status: 'active',
        summary: 'One thing tried or not yet tried: a ticked box on the sun, or a dashed empty one.',
        module: '/components/CheckItem.js', sheet: '/css/components/check-item.css',
        data: { shape: 'CheckItem({ done, href, external, onClick, children })', fields: { done: 'tried', href: 'where to try it', external: 'opens elsewhere', onClick: 'handler', children: 'the thing' } },
        useFor: ['A list of first things to try, which ticks itself as they happen.'],
        variants: [{ name: 'done', class: 'poster-check--done', prop: 'done', when: 'already tried' }],
        example: { done: true, href: '/v1/chat', children: 'Talk to your agent' },
    },
    {
        id: 'timeline', name: 'Timeline', kind: 'component', status: 'active',
        summary: 'What has happened: time first, a category dot, one line, one rule per row.',
        module: '/components/Timeline.js', sheet: '/css/components/timeline.css',
        data: {
            shape: 'Timeline({ title, band, quiet, more, children }) · TimelineList({ children }) · TimelineRow({ category, live, href, text, when })',
            fields: { title: 'the headline', band: 'drawn as a Band', quiet: '{ href, text } for a quiet period', more: '{ href, text } to the full record', category: 'made, agent, trouble, money, access or system', live: 'happening now (pulses)', text: 'what happened', when: 'the time' },
        },
        useFor: ['A record of events, on the home and on the full history page.', 'Every list of what happened in Settings & Controls: an agent\'s activity (the kind tag before the line), an opened task\'s events, a workspace\'s activity and its recent decisions.'],
        variants: [
            { name: 'made', class: 'poster-timeline-item--made', prop: "category='made'", when: 'something was made' },
            { name: 'agent', class: 'poster-timeline-item--agent', prop: "category='agent'", when: 'an agent did it' },
            { name: 'trouble', class: 'poster-timeline-item--trouble', prop: "category='trouble'", when: 'something failed' },
            { name: 'money', class: 'poster-timeline-item--money', prop: "category='money'", when: 'money moved' },
            { name: 'access', class: 'poster-timeline-item--access', prop: "category='access'", when: 'access changed' },
            { name: 'system', class: 'poster-timeline-item--system', prop: "category='system'", when: 'the node did it' },
            { name: 'live', class: 'poster-timeline-item--live', prop: 'live', when: 'still happening' },
        ],
        example: { title: 'What has happened', rows: [{ category: 'made', text: 'You published a page', when: '10:42', href: '/v1/pages/mat' }] },
    },
    {
        id: 'back-link', name: 'BackLink', kind: 'component', status: 'active',
        summary: 'A mono coral link back to where a person came from.',
        module: '/components/BackLink.js', sheet: '/css/components/back-link.css',
        data: { shape: 'BackLink({ href, onClick, children })', fields: { href: 'where back is', onClick: 'the router\'s handler', children: '↩ and the words' } },
        useFor: ['The top of a page a person reached from another one.'],
        variants: [],
        example: { href: '/v1/home', children: '↩ Back to your home' },
    },
    {
        id: 'day-group', name: 'DayGroup', kind: 'component', status: 'active',
        summary: 'One day of a record: the day as a small coral heading over its rows.',
        module: '/components/DayGroup.js', sheet: '/css/components/day-group.css',
        data: { shape: 'DayGroup({ title, children }) · DayList({ children }) · DayEmpty({ children })', fields: { title: 'the day', children: 'TimelineRows; DayEmpty says a record has nothing' } },
        useFor: ['A long record, grouped by day.', 'The heading alone (.poster-day-title) over any list: the chat\'s side column, and quiet over its work log.'],
        variants: [{ name: 'quiet', class: 'poster-day-title--quiet', prop: 'class', when: 'a heading over a record rather than over the page\'s structure (the chat\'s work log)' }],
        example: { title: 'Today', children: 'TimelineRow × n' },
    },
    {
        id: 'archive', name: 'ArchiveSection', kind: 'component', status: 'active',
        summary: 'The older part of a record, under its own rule, opened on request.',
        module: '/components/ArchiveSection.js', sheet: '/css/components/archive.css',
        data: { shape: 'ArchiveSection({ title, note, children }) · ArchiveMore({ disabled, onClick, children }) · ArchiveError({ children })', fields: { title: 'the heading', note: 'why it is kept apart', children: 'the older rows and an ArchiveMore' } },
        useFor: ['Where a record keeps what is older than its first page.'],
        variants: [],
        example: { title: 'Older', note: 'Kept for a year, then removed.', more: 'Show older' },
    },
    {
        id: 'settings-stack', name: 'SettingsStack', kind: 'component', status: 'active',
        summary: 'The inside of a settings dialog: its sections in one column, each under its headline slab.',
        module: '/components/SettingsStack.js', sheet: '/css/components/settings-stack.css',
        data: { shape: 'SettingsStack({ children }) · SettingsSection({ title, children })', fields: { children: 'the SettingsSections, and a SettingsDoor last', 'SettingsSection.title': 'the section\'s headline, on its slab', 'SettingsSection.children': 'what the section holds' } },
        useFor: ['Inside a Modal that holds a page\'s own settings.'],
        variants: [{ name: 'section', prop: 'SettingsSection title', when: 'one section of the dialog under its headline slab (poster.css .poster-section)' }],
        example: one('<section class="poster-section">…</section>'),
    },
    {
        id: 'settings-switch', name: 'SettingsSwitch', kind: 'component', status: 'active',
        summary: 'A setting that is on or off: a checkbox and its words.',
        module: '/components/SettingsSwitch.js', sheet: '/css/components/settings-switch.css',
        data: { shape: 'SettingsSwitch({ checked, onChange, disabled, children })', fields: { checked: 'on', onChange: 'flip', disabled: 'it cannot change now', children: 'what it turns on' } },
        useFor: ['One on-or-off choice in a settings dialog.'],
        variants: [],
        example: { checked: true, children: 'Show what I have tried' },
    },
    {
        id: 'swatch-picker', name: 'SwatchPicker', kind: 'component', status: 'active',
        summary: 'A choice among a few named looks: a preview strip and the choices, the chosen one on the sun.',
        module: '/components/SwatchPicker.js', sheet: '/css/components/swatch-picker.css',
        data: {
            shape: 'SwatchPicker({ title, hint, preview, pattern, emptyLabel, choices, onChoose })',
            fields: { title: 'what is chosen', hint: 'one line of help', preview: 'any other preview, drawn by the page', pattern: 'the margin figure\'s name (a to h, or x); the picker draws its swatch itself', emptyLabel: 'the words when nothing is chosen', choices: '[{ value, label, active }]', onChoose: 'called with the value' },
        },
        useFor: ['A pattern or colour choice with a handful of options.'],
        variants: [{ name: 'pattern', prop: 'pattern', when: 'the margin pattern: the preview is the pattern\'s own swatch (.mp-swatch, margin-pattern.css), so the page passes a name, not a class' }],
        example: { title: 'Margin pattern', choices: [{ value: 'none', label: 'None', active: true }, { value: 'dots', label: 'Dots', active: false }] },
    },
    {
        id: 'settings-door', name: 'SettingsDoor', kind: 'component', status: 'active',
        summary: 'A way out of a dialog to the full settings, as a row under the 3px ink rule.',
        module: '/components/SettingsDoor.js', sheet: '/css/components/settings-door.css',
        data: { shape: 'SettingsDoor({ href, title, hint })', fields: { href: 'the full settings', title: 'the door words', hint: 'what is there' } },
        useFor: ['The last row of a small settings dialog.'],
        variants: [],
        example: { href: '/v1/profile', title: 'All settings →', hint: 'Your account, your agents and your keys.' },
    },
    {
        id: 'open-items', name: 'OpenItemsList', kind: 'component', status: 'active',
        summary: 'What a person is going to do here: the list, its one prompt at the top, and the header button with the count.',
        module: '/components/OpenItemsList.js', sheet: '/css/components/open-items.css',
        data: { shape: 'OpenItemsList({ maxAgeDays })', fields: { maxAgeDays: 'hide rows older than this many days' } },
        useFor: ['The open items band on the home. It reads its own rows from the node.'],
        variants: [],
        example: { maxAgeDays: 7 },
        note: 'The header button with the count is OpenItemsButton, which reads the same sheet.',
    },
    {
        id: 'chooser', name: 'Chooser', kind: 'component', status: 'active',
        summary: 'Pick a task and get what it needs: the choices row, the panel with the sun bar that the choice governs, the status row, a framed box, a fold, the result and the links.',
        module: '/components/Chooser.js', sheet: '/css/components/chooser.css',
        data: {
            shape: 'Chooser({ titleId, title, lead, children }) · ChooserChoices({ label, children }) · ChooserChoice({ on, onClick, children }) · ChooserPanel · ChooserStatus · ChooserBox · ChooserFold({ summary }) · ChooserLinks · ChooserResult',
            fields: { titleId: 'the heading id', title: 'the headline', lead: 'the line under it', label: 'the choices, for a screen reader', on: 'the chosen task', summary: 'the fold\'s words' },
        },
        useFor: ['A band where the person first picks what they want to do, then gets the prompt or the connection for it.'],
        variants: [{ name: 'chosen', prop: 'on', when: 'the chosen task, the chosen tab (poster.css .poster-tab.is-on)' }],
        example: { title: 'Connect your AI', choices: [{ on: true, children: 'Claude' }, { on: false, children: 'ChatGPT' }] },
    },
    {
        id: 'settings-account', name: 'SettingsAccount', kind: 'component', status: 'active',
        summary: 'The account actions in a settings dialog, one per line, full-width headline.',
        module: '/components/SettingsAccount.js', sheet: '/css/components/settings-account.css',
        data: { shape: 'SettingsAccount({ title, children })', fields: { title: 'the headline', children: 'poster-action buttons' } },
        useFor: ['Sign out and the other account actions, at the foot of a settings dialog.'],
        variants: [],
        example: { title: 'Account', children: 'Sign out' },
    },
    {
        id: 'free-text', name: 'FreeText', kind: 'component', status: 'active',
        summary: 'A passage an operator wrote into a layout (plain, card or band), and the front page\'s text and notice blocks.',
        module: '/components/FreeText.js', sheet: '/css/components/free-text.css',
        data: { shape: 'FreeText({ tone, title, children }) · TextBlock({ title, children }) · NoticeBlock({ title, children })', fields: { tone: "'plain', 'card' or 'band'", title: 'an optional heading', children: 'the passage, as rendered Markdown' } },
        useFor: ['The common.freeform block, and the portal text and notice blocks.'],
        variants: [
            { name: 'card', class: 'poster-free--card', prop: "tone='card'", when: 'a framed passage' },
            { name: 'band', class: 'poster-free--band', prop: "tone='band'", when: 'a passage on a band' },
        ],
        example: { tone: 'card', title: 'Opening hours', children: 'We answer on weekdays.' },
    },
    {
        id: 'specimen', name: 'Specimen', kind: 'component', status: 'active',
        note: 'Drawn by the design lab and by Themes & Styles (views/admin/themes-*), the two views of the admin\'s Design group.',
        summary: 'One live preview of an interface part in its own frame, with a caption; a row of them shows one part in several looks side by side.',
        module: '/components/Specimen.js', sheet: '/css/components/specimen.css',
        data: {
            shape: 'Specimens({ children }) · Specimen({ label, src, phone, note })',
            fields: { label: 'the caption', src: 'the preview page address (/v1/design-lab/frame?id=&v=&theme=)', phone: 'a 390-pixel frame', note: 'a line under the frame' },
        },
        useFor: ['The design lab and Themes & Styles: a part or a real page drawn live, light and dark side by side, and at a phone width.'],
        variants: [{ name: 'phone', class: 'poster-specimen--phone', prop: 'phone', when: 'the phone-width frame' }],
        example: { label: 'Light', src: '/v1/design-lab/frame?id=turn&v=0&theme=light' },
    },
];
