/**
 * @file ai-image.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Image generation on the owner's key, with the result landing in storage rather than
 *   in anyone's context.
 *
 *   It runs the node's one gate: prepareAiCall (provider allowlist, app allowlist, model, key,
 *   budget), the gateway (services/ai/gateway.ts), then settleAiCall (spend, allowance, provenance),
 *   because those steps are the node's answer to "who is paying and may they", and a second AI
 *   capability that answered it differently would be a second answer.
 *
 *   What is specific to images is the destination. Generated bytes go straight to the caller's own
 *   storage under `ai-images/`, and the caller is handed a key and a URL. Returning base64 would put
 *   a whole picture through a tool result and an agent's context for nothing, and the node already
 *   has a place where bytes live and can be referenced.
 * @structure
 *   - IMAGE_UNSET_MESSAGE — the one place the "no model chosen" wording lives
 *   - generateForOwner() — the whole path, refusing with AiCompletionError codes
 * @usage
 *   import { generateForOwner } from '../services/ai-image.js';
 *   const out = await generateForOwner(storage, config, gaii, { prompt: 'a red bicycle' });
 * @version-history
 *   v2.6.0 -- 2026-10-07 -- A provider's key refusal is 424 INVALID_API_KEY, not 401 (PROVIDER_KEY_REFUSED_STATUS).
 *   v2.5.0 — 2026-10-05 — The AI call limit is counted per account in the service, so the MCP tools share it (secaudit 2026-10, C5).
 *   v2.4.0 — 2026-10-05 — `caller` is required: every call says who asks (secaudit 2026-10, AI-3).
 *   v2.3.0 — 2026-10-02 — Takes `lang`, so a refusal's sentence is in the person's language.
 *   v2.2.0 — 2026-09-28 — Takes `role`, the AI role the call runs as (services/ai/roles.ts).
 *   v2.1.0 — 2026-09-28 — Takes caller and verifiedApp for the owner's model policy (V2).
 *   v2.1.0 — 2026-09-28 — Providers (System 2 plan, V3): the owner's candidates are tried by their
 *     rules (services/ai/route-run.ts), a call may name a `provider` and turn `fallback` off, the
 *     attempts that failed before a fallback are usage rows of their own, and the result has `route`.
 *   v2.0.0 — 2026-09-28 — Through the shared gate (System 2 plan, V1): prepareAiCall with op
 *     `image`, the gateway's image(), settleAiCall. What changes for a person: an agent's own key and
 *     the node's key can pay for a picture the way they pay for text (the node's only when the
 *     operator named a node default image model), the node's allowance is drawn down, and every
 *     picture gets a provenance record whose content hash is the SHA-256 of its bytes. The model
 *     refusal, its wording and the order of the refusals are unchanged.
 *   v1.1.1 — 2026-09-19 — The allowlist and cap checks take the owner, so they match an app under
 *     any of its names (services/ai-app-id.ts).
 *   v1.1.0 — 2026-08-28 — imageFetchUrl + fetchUrl on the result: the URL that loads for the
 *     visibility's audience, built once. Both doors used to hand back the owner-authenticated
 *     /v1/storage/ form for public images, and the first imagery-pipeline demo shipped it into an
 *     app where every visitor got 401.
 *   v1.0.0 — 2026-08-16 — Initial. The node had no image generation at all: no setting, no route, no
 *     tool, and no 'image' in the modality union, so scripts/gen_image.py was the only way to make a
 *     picture here and it is a developer's script rather than a capability of the node.
 */
import type { AimeatConfig } from '../config.js';
import type { Storage, AiProvenanceRecordRow } from '../storage/interface.js';
import {
  AiCompletionError, PROVIDER_KEY_REFUSED_STATUS, prepareAiCall, settleAiCall, planFor, recordFailedAttempts, type AiCallPlan,
} from './ai/completion.js';
import { image as gatewayImage } from './ai/gateway.js';
import { runRoute, type AiRoute } from './ai/route-run.js';
import { callCost } from './ai/catalog/price.js';
import type { AiCandidate } from './ai/route-plan.js';
import { contentHashOf } from './ai-provenance.js';
import type { CallerClass } from './ai/policy.js';
import type { RequestLanguage } from './ai/ai-fix-words.js';
import { logger } from '../utils/logger.js';
import { requireAiCallTurn, type AiCallLimitMark } from './account-limits.js';

/**
 * Said when neither the call, the owner nor the node has named an image model. Lives in
 * services/ai/unset-model.ts since the gate refuses it; re-exported so the name stays where it was.
 */
export { IMAGE_UNSET_MESSAGE } from './ai/unset-model.js';

/** Longest prompt accepted. Providers reject far shorter ones; this is the local sanity bound. */
const MAX_PROMPT_CHARS = 4000;

export interface GenerateForOwnerOptions {
  prompt: string;
  /** Model override. Without it the owner's `imageModel`, then the node default, is used. */
  model?: string;
  /** Provider-specific size string, e.g. '1024x1024'. Passed through untouched. */
  size?: string;
  /** Storage key to write to. Defaults to `ai-images/<timestamp>-<random>.<ext>`. */
  storageKey?: string;
  /** Make the stored image publicly readable. Needed when a model has to fetch it back by URL. */
  publicVisibility?: boolean;
  /** App/source attribution — enables the app allowlist and per-app quota. */
  appId?: string;
  /** The owner's agent that asked, by bare name: its own key pays first and its cap applies. The
   *  caller derives it from the principal (aiPayerOf), never from a request body. */
  agent?: string;
  /** An outside reason to stop waiting, combined with the call's own timeout. */
  signal?: AbortSignal;
  /** Whose call this is and the app its grant names, for the owner's model policy. */
  caller: CallerClass;
  verifiedApp?: string;
  /** The request's word on the person's language, for a refusal's sentence. */
  lang?: RequestLanguage;
  /** A provider the call names (an id or a type), and the call's word on fallback. */
  provider?: string;
  fallback?: boolean;
  /** The AI role the call runs as (services/ai/roles.ts). A named model or provider wins over it. */
  role?: string;
  /** 'exempt' for node-internal work; absent, the call counts against the account's AI call limit
   *  (services/account-limits.ts). */
  limit?: AiCallLimitMark;
}

export interface GenerateForOwnerResult {
  storageKey: string;
  /** The node-relative URL that actually loads for the audience the visibility implies: the
   * anonymous /v1/pub/ form when public, the owner-authenticated /v1/storage/ form when private.
   * Built here ONCE — the first imagery-pipeline demo shipped a "publicly readable" /v1/storage/
   * URL that answered 401 to everyone but the owner, because each door built its own. */
  fetchUrl: string;
  mime: string;
  sizeBytes: number;
  model: string;
  visibility: 'public' | 'private';
  usage: { costUsd: number; costExact: boolean };
  budget: { dailyBudgetUsd: number; spentTodayUsd: number; remainingUsd: number };
  /** The provenance record minted for this picture; its content hash is the SHA-256 of the bytes.
   *  Absent when provenance is off on this node or minting failed (a paid picture is never failed
   *  for bookkeeping). */
  provenance?: AiProvenanceRecordRow;
  /** Which pocket paid: the agent's key, the owner's own, or the node's allowance. */
  keySource: 'agent' | 'own' | 'node';
  /** Who chose the provider, who answered, and every attempt (services/ai/route-run.ts). */
  route: AiRoute;
}

/** `image/png` -> `png`, defaulting to png rather than guessing something exotic. */
function extensionFor(mime: string): string {
  const sub = mime.split('/')[1] ?? 'png';
  return sub.replace(/[^a-z0-9]/gi, '') || 'png';
}

/**
 * The node-relative URL a stored image actually loads from, for the audience its visibility
 * implies. Public files are served anonymously ONLY under /v1/pub/{owner}/{key}; the
 * /v1/storage/{key} form is owner-authenticated and answers 401 to everyone else — which is how
 * the first imagery-pipeline demo shipped a "publicly readable" URL no visitor could open.
 * @param {('public'|'private')} visibility
 */
export function imageFetchUrl(visibility: 'public' | 'private', ownerGaii: string, key: string): string {
  const encodedKey = key.split('/').map(encodeURIComponent).join('/');
  return visibility === 'public'
    ? `/v1/pub/${encodeURIComponent(ownerGaii)}/${encodedKey}`
    : `/v1/storage/${encodedKey}`;
}

/**
 * Generate one image on the owner's key and store it.
 *
 * The order matters and is the same order every other AI path uses: refuse before spending, spend,
 * then record. A caller over budget is told so before the provider is called, not after.
 */
export async function generateForOwner(
  storage: Storage,
  config: AimeatConfig,
  gaii: string,
  opts: GenerateForOwnerOptions,
): Promise<GenerateForOwnerResult> {
  const prompt = typeof opts.prompt === 'string' ? opts.prompt.trim() : '';
  if (!prompt) throw new AiCompletionError('INVALID_BODY', 400, 'prompt is required.');
  if (prompt.length > MAX_PROMPT_CHARS) {
    throw new AiCompletionError('PROMPT_TOO_LONG', 400,
      `Prompt is ${prompt.length} characters; the limit is ${MAX_PROMPT_CHARS}.`);
  }
  // POST /v1/ai/image and aimeat_image_generate both arrive here: one count per account, before any spend.
  requireAiCallTurn(config, gaii, opts.limit);

  const plan = await prepareAiCall(storage, config, gaii, {
    op: 'image', model: opts.model, appId: opts.appId, ...(opts.agent ? { agent: opts.agent } : {}),
    caller: opts.caller, ...(opts.verifiedApp ? { verifiedApp: opts.verifiedApp } : {}),
    ...(opts.lang ? { lang: opts.lang } : {}),
    ...(opts.provider ? { provider: opts.provider } : {}), ...(opts.fallback !== undefined ? { fallback: opts.fallback } : {}),
    ...(opts.role ? { role: opts.role } : {}),
  });

  let result;
  let answered: AiCallPlan;
  let route: AiRoute;
  try {
    const run = await runRoute({
      storage, gaii, capability: plan.capability, candidates: plan.candidates, chosenBy: plan.chosenBy,
      allowFallback: plan.allowFallback, rules: plan.rules, ...(opts.signal ? { signal: opts.signal } : {}),
    }, (c) => gatewayImage({
      target: c.target, model: c.model, prompt,
      ...(opts.size ? { size: opts.size } : {}),
      ...(opts.signal ? { signal: opts.signal } : {}),
    }));
    result = run.result;
    answered = planFor(plan, run.candidate);
    route = run.route;
    if (route.fellBack) await recordFailedAttempts(storage, config, gaii, plan, run.failed, { appId: opts.appId, source: 'ai-image' });
  } catch (e) {
    const moved = e as { route?: AiRoute; failed?: Array<{ candidate: AiCandidate; error: string; costUsd: number }> };
    if (moved.route?.fellBack && moved.failed) await recordFailedAttempts(storage, config, gaii, plan, moved.failed, { appId: opts.appId, source: 'ai-image' });
    const status = (e as { status?: number }).status;
    if (status === 401) throw new AiCompletionError('INVALID_API_KEY', PROVIDER_KEY_REFUSED_STATUS, 'API key was rejected by the provider.');
    if (status === 429) throw new AiCompletionError('RATE_LIMITED', 429, 'Provider rate limit hit. Try again later.');
    throw new AiCompletionError('PROVIDER_ERROR', 502, (e as Error).message);
  }

  // The provider's own charge, then the catalogue's price per picture (services/ai/catalog/price.ts).
  const price = callCost({ type: answered.providerType, model: result.model, requestedModel: answered.model, images: 1, reported: result.costUsd });
  const costExact = price.costSource === 'provider';
  const costUsd = price.costUsd;

  const key = opts.storageKey
    || `ai-images/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${extensionFor(result.mime)}`;
  const visibility = opts.publicVisibility ? 'public' as const : 'private' as const;
  await storage.createStorageFile({
    key,
    ownerGaii: gaii,
    visibility,
    mimeType: result.mime,
    size: result.data.length,
    data: result.data,
    createdAt: new Date().toISOString(),
  });

  const settled = await settleAiCall(storage, config, gaii, answered, {
    model: result.model,
    // Image models are priced per image rather than per token, so the authoritative number is the
    // cost. Zero tokens is the honest report, not a gap.
    promptTokens: 0, completionTokens: 0, totalTokens: 0,
    costUsd, content: '',
    // The provenance record names the picture by its bytes, the way a voice reply names its audio.
    contentHash: contentHashOf(result.data),
    appId: opts.appId, source: 'ai-image',
    units: { images: 1 }, costSource: price.costSource, priceRef: price.priceRef,
  });

  logger.info(`[image] gaii=${gaii} app=${opts.appId || '_unknown'} model=${result.model} `
    + `bytes=${result.data.length} cost=$${costUsd.toFixed(6)} day_total=$${settled.usage.total_cost_usd.toFixed(4)}`);

  const dailyBudget = plan.dailyBudgetUsd;
  const spent = settled.usage.total_cost_usd;
  return {
    storageKey: key,
    fetchUrl: imageFetchUrl(visibility, gaii, key),
    mime: result.mime,
    sizeBytes: result.data.length,
    model: result.model,
    visibility,
    usage: { costUsd, costExact },
    budget: {
      dailyBudgetUsd: dailyBudget,
      spentTodayUsd: spent,
      remainingUsd: Math.max(0, dailyBudget - spent),
    },
    ...(settled.provenance ? { provenance: settled.provenance } : {}),
    keySource: answered.keyScope,
    route: { ...route, attempts: route.attempts.map(a => a.ok ? { ...a, costUsd } : a) },
  };
}
