/**
 * @file ai-image.ts
 * @description Image generation on the owner's key, with the result landing in storage rather than
 *   in anyone's context.
 *
 *   It follows transcribeForOwner() step for step — provider allowlist, app allowlist, key decrypt,
 *   daily budget, call, spend recorded — because those steps are the node's answer to "who is paying
 *   and may they", and a second AI capability that answered it differently would be a second answer.
 *
 *   What is specific to images is the destination. Generated bytes go straight to the caller's own
 *   storage under `ai-images/`, and the caller is handed a key and a URL. Returning base64 would put
 *   a whole picture through a tool result and an agent's context for nothing, and the node already
 *   has a place where bytes live and can be referenced.
 * @structure
 *   - IMAGE_UNSET_MESSAGE — the one place the "no model chosen" wording lives
 *   - generateForOwner() — the whole path, refusing with AiCompletionError codes
 * @usage
 *   import { generateForOwner } from '../services/ai-image.js';
 *   const out = await generateForOwner(storage, config, gaii, { prompt: 'a red bicycle' });
 * @version-history
 *   v1.0.0 — 2026-08-16 — Initial. The node had no image generation at all: no setting, no route, no
 *     tool, and no 'image' in the modality union, so scripts/gen_image.py was the only way to make a
 *     picture here and it is a developer's script rather than a capability of the node.
 */
import type { AimeatConfig } from '../config.js';
import type { Storage } from '../storage/interface.js';
import { generateImage, DEFAULT_BASE_URLS, type ProviderType } from './openrouter.js';
import {
  AiCompletionError, assertProviderAllowed, assertAppAllowed, decryptOwnerKey,
  assertWithinBudget, recordAiUsage, todayKey, type UsageRecord,
} from './ai-completion.js';
import { logger } from '../utils/logger.js';
import { resolveModelFor } from './ai-model-defaults.js';

/**
 * Said when neither the owner nor the node has named an image model. A refusal rather than a
 * fallback, for the same reason speech-to-text refuses: a chat model handed an image request
 * answers with prose, and the person is left holding an opaque provider error instead of a sentence
 * naming the setting they have to fill in.
 */
export const IMAGE_UNSET_MESSAGE =
  'No image model is configured. Choose one in Profile > OpenRouter (an image model, not a chat '
  + 'model), or ask the operator to set a default for this node.';

/** Longest prompt accepted. Providers reject far shorter ones; this is the local sanity bound. */
const MAX_PROMPT_CHARS = 4000;

export interface GenerateForOwnerOptions {
  prompt: string;
  /** Model override. Without it the owner's `imageModel`, then the node default, is used. */
  model?: string;
  /** Provider-specific size string, e.g. '1024x1024'. Passed through untouched. */
  size?: string;
  /** Storage key to write to. Defaults to `ai-images/<timestamp>-<random>.<ext>`. */
  storageKey?: string;
  /** Make the stored image publicly readable. Needed when a model has to fetch it back by URL. */
  publicVisibility?: boolean;
  /** App/source attribution — enables the app allowlist and per-app quota. */
  appId?: string;
}

export interface GenerateForOwnerResult {
  storageKey: string;
  mime: string;
  sizeBytes: number;
  model: string;
  visibility: 'public' | 'private';
  usage: { costUsd: number; costExact: boolean };
  budget: { dailyBudgetUsd: number; spentTodayUsd: number; remainingUsd: number };
}

const emptyUsage = (): UsageRecord => ({
  date: todayKey(), total_cost_usd: 0, total_calls: 0, total_tokens: 0,
  per_app: {}, updated_at: new Date().toISOString(),
});

/** `image/png` -> `png`, defaulting to png rather than guessing something exotic. */
function extensionFor(mime: string): string {
  const sub = mime.split('/')[1] ?? 'png';
  return sub.replace(/[^a-z0-9]/gi, '') || 'png';
}

/**
 * Generate one image on the owner's key and store it.
 *
 * The order matters and is the same order every other AI path uses: refuse before spending, spend,
 * then record. A caller over budget is told so before the provider is called, not after.
 */
export async function generateForOwner(
  storage: Storage,
  config: AimeatConfig,
  gaii: string,
  opts: GenerateForOwnerOptions,
): Promise<GenerateForOwnerResult> {
  const prompt = typeof opts.prompt === 'string' ? opts.prompt.trim() : '';
  if (!prompt) throw new AiCompletionError('INVALID_BODY', 400, 'prompt is required.');
  if (prompt.length > MAX_PROMPT_CHARS) {
    throw new AiCompletionError('PROMPT_TOO_LONG', 400,
      `Prompt is ${prompt.length} characters; the limit is ${MAX_PROMPT_CHARS}.`);
  }

  const [apiKeyRecord, prefsRecord, usageRecord] = await Promise.all([
    storage.getMemory(gaii, 'openrouter.apikey'),
    storage.getMemory(gaii, 'openrouter.settings'),
    storage.getMemory(gaii, `ai-usage.${gaii}.${todayKey()}`),
  ]);
  const prefs = (prefsRecord?.value as Record<string, unknown>) ?? {};
  const provider = (prefs.provider as ProviderType) || 'openrouter';
  const baseUrl = (prefs.baseUrl as string) || DEFAULT_BASE_URLS[provider];

  assertProviderAllowed(config, baseUrl);
  assertAppAllowed(prefs, opts.appId);

  const model = opts.model || resolveModelFor(config, prefs, 'image');
  if (!model) throw new AiCompletionError('NO_IMAGE_MODEL', 400, IMAGE_UNSET_MESSAGE);

  const decryptedKey = decryptOwnerKey(config, apiKeyRecord?.value, provider);

  const usage = (usageRecord?.value as UsageRecord | undefined) ?? emptyUsage();
  const dailyBudget = assertWithinBudget(usage, prefs, opts.appId);

  let result;
  try {
    result = await generateImage(decryptedKey, model, prompt, baseUrl, { size: opts.size });
  } catch (e) {
    const status = (e as { status?: number }).status;
    if (status === 401) throw new AiCompletionError('INVALID_API_KEY', 401, 'API key was rejected by the provider.');
    if (status === 429) throw new AiCompletionError('RATE_LIMITED', 429, 'Provider rate limit hit. Try again later.');
    throw new AiCompletionError('PROVIDER_ERROR', 502, (e as Error).message);
  }

  const costExact = typeof result.costUsd === 'number';
  const costUsd = costExact ? result.costUsd! : 0;

  const key = opts.storageKey
    || `ai-images/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${extensionFor(result.mime)}`;
  const visibility = opts.publicVisibility ? 'public' as const : 'private' as const;
  await storage.createStorageFile({
    key,
    ownerGaii: gaii,
    visibility,
    mimeType: result.mime,
    size: result.data.length,
    data: result.data,
    createdAt: new Date().toISOString(),
  });

  const updated = await recordAiUsage(storage, gaii, usage, {
    costUsd,
    // Image models are priced per image rather than per token, so the authoritative number is the
    // cost. Zero tokens is the honest report, not a gap.
    tokens: 0, appId: opts.appId,
    model: result.model, provider, promptTokens: 0, completionTokens: 0,
    source: 'ai-image',
  });

  logger.info(`[image] gaii=${gaii} app=${opts.appId || '_unknown'} model=${result.model} `
    + `bytes=${result.data.length} cost=$${costUsd.toFixed(6)} day_total=$${updated.total_cost_usd.toFixed(4)}`);

  const spent = updated.total_cost_usd;
  return {
    storageKey: key,
    mime: result.mime,
    sizeBytes: result.data.length,
    model: result.model,
    visibility,
    usage: { costUsd, costExact },
    budget: {
      dailyBudgetUsd: dailyBudget,
      spentTodayUsd: spent,
      remainingUsd: Math.max(0, dailyBudget - spent),
    },
  };
}
