/**
 * @file gen-third-party-notices.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Writes THIRD-PARTY-NOTICES.md: every third-party component AIMEAT distributes, its
 *   copyright holder, and its licence text in full. MIT, BSD and ISC all ask for the same one
 *   thing — that the copyright notice travels with the copy — and this file is where it travels.
 *   Whether we modified anything is beside the point: the obligation attaches to distribution, not
 *   to modification.
 *
 *   IT HAS TO BE GENERATED. Six of the vendored browser libraries (p5, phaser, pixi, drawflow,
 *   tailwind, daisyui) are minified builds with no copyright line anywhere in the file, so copying
 *   the file satisfies nothing on its own; and the npm side is 412 packages, which no one is going
 *   to maintain by hand. Both halves come from scripts/lib/license-inventory.ts, which reads the
 *   real LICENSE file each package ships rather than a table someone typed.
 *
 *   TWO COPIES, ONE SOURCE. The repository root copy is what a person or a legal team reads on
 *   GitHub. public/THIRD-PARTY-NOTICES.md is the one the node serves and the one the npm tarball
 *   carries (the build copies public/ into dist/). `--check` proves they are both current, which is
 *   what makes it safe to put in the pre-commit hook.
 * @structure componentRow() → the inventory table; licenceSections() → texts deduplicated by
 *   content, each naming the components that share it; render() → the whole file; main() →
 *   write both copies, or compare them under --check
 * @usage
 *   pnpm gen:notices     # regenerate both copies
 *   pnpm check:notices   # fail if either is stale (pre-commit hook + CI)
 * @version-history
 *   v1.0.0 — 2026-08-31 — Initial: npm production tree + served /lib/ components, texts in full.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import {
  AIMEAT_ROOT, REPO_ROOT, SPDX_OF_NOTE, npmComponents, vendoredComponents,
  type Component,
} from './lib/license-inventory.js';

const OUTPUTS = [
  join(REPO_ROOT, 'THIRD-PARTY-NOTICES.md'),
  join(AIMEAT_ROOT, 'public', 'THIRD-PARTY-NOTICES.md'),
];

/** Markdown table cells cannot carry a pipe or a newline. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').trim();
}

function link(name: string, url: string): string {
  return url ? `[${cell(name)}](${url})` : cell(name);
}

function servedRow(c: Component): string {
  const obligation = SPDX_OF_NOTE[c.spdx] ? '**see below**' : 'notice only';
  const shipped = c.fetched === true ? 'installed by the operator' : 'served by the node';
  return `| ${link(c.name, c.homepage)} | ${cell(c.version)} | ${cell(c.spdx)} | ${cell(c.copyright)} | ${shipped} | ${obligation} |`;
}

function npmRow(c: Component): string {
  return `| ${link(c.name, c.homepage)} | ${cell(c.version)} | ${cell(c.spdx)} |`;
}

interface TextGroup { text: string; components: Component[] }

/**
 * One section per distinct licence text, naming every component that ships exactly that text.
 * Deduplicating by content rather than by SPDX id is the honest way round: two MIT packages carry
 * two different copyright lines, and collapsing them would drop the very notice this file exists
 * to preserve.
 */
function licenceSections(components: Component[]): TextGroup[] {
  const groups = new Map<string, TextGroup>();
  for (const c of components) {
    if (c.licenseText === null) continue;
    const key = createHash('sha256').update(c.licenseText).digest('hex');
    const existing = groups.get(key);
    if (existing === undefined) groups.set(key, { text: c.licenseText, components: [c] });
    else existing.components.push(c);
  }
  return [...groups.values()].sort((a, b) => a.components[0].name.localeCompare(b.components[0].name));
}

function render(served: Component[], npm: Component[]): string {
  const version = (JSON.parse(readFileSync(join(AIMEAT_ROOT, 'package.json'), 'utf-8')) as { version: string }).version;
  const out: string[] = [];

  out.push('# Third-party notices');
  out.push('');
  // An absolute link, because this file is written to two places at different depths and served
  // from a third: a relative one would resolve in the repository root copy and nowhere else.
  out.push(`AIMEAT ${version} is MIT-licensed`);
  out.push('([LICENSE](https://github.com/miikkij/aimeat-protocol/blob/main/LICENSE)) and carries third-party code.');
  out.push('This file lists that code and reproduces its licence texts. It is generated by');
  out.push('`pnpm gen:notices` from the installed dependency tree and from');
  out.push('`aimeat/public/lib/licenses.json` — do not edit it by hand.');
  out.push('');
  out.push('## If you are shipping AIMEAT');
  out.push('');
  out.push('You may use, modify and sell this software, including in a closed-source product. Three');
  out.push('things travel with it:');
  out.push('');
  out.push('1. **Keep this file and LICENSE with whatever you distribute.** That is the whole of what');
  out.push('   MIT, BSD and ISC ask for, and it is most of the list below. It applies whether or not');
  out.push('   you changed anything.');
  out.push('2. **Read the components marked "see below".** They carry an obligation beyond the notice,');
  out.push('   and each one says what it costs you.');
  out.push('3. **Nothing here requires you to publish your own code.** No dependency of this project is');
  out.push('   under the AGPL, and none of the copyleft components below is linked into the server.');
  out.push('');
  out.push('If your own product adds dependencies to AIMEAT, this file does not describe those.');
  out.push('');

  const notable = served.filter(c => SPDX_OF_NOTE[c.spdx] !== undefined);
  if (notable.length > 0) {
    out.push('## Components that ask for more than a notice');
    out.push('');
    for (const c of notable) {
      out.push(`### ${c.name} — ${c.spdx}`);
      out.push('');
      out.push(SPDX_OF_NOTE[c.spdx]);
      out.push('');
      if (c.note) { out.push(c.note); out.push(''); }
      if (c.sourceOffer) {
        out.push(`**Complete source of the exact version:** ${c.sourceOffer}`);
        out.push('');
      }
    }
  }

  out.push('## Served to browsers from /lib/');
  out.push('');
  out.push('Everything this node serves to a browser, which is distribution in the same sense a');
  out.push('tarball is. "Installed by the operator" means AIMEAT does not ship the file at all:');
  out.push('`pnpm vendor:libs` fetches it onto the machine that runs the node.');
  out.push('');
  out.push('| Component | Version | Licence | Copyright | How it gets there | Obligation |');
  out.push('|---|---|---|---|---|---|');
  for (const c of served) out.push(servedRow(c));
  out.push('');

  const modified = served.filter(c => c.modified);
  if (modified.length > 0) {
    out.push('Components AIMEAT changed rather than copied verbatim: '
      + modified.map(c => `**${c.name}** (${c.note ?? 'see licenses.json'})`).join('; '));
    out.push('');
  }

  out.push('## Production dependencies');
  out.push('');
  out.push(`The ${npm.length} npm packages that travel inside the \`aimeat\` package. Build and test`);
  out.push('tools are not listed: they do not ship, so they carry no obligation for you.');
  out.push('');
  out.push('| Package | Version | Licence |');
  out.push('|---|---|---|');
  for (const c of npm) out.push(npmRow(c));
  out.push('');

  out.push('## Licence texts');
  out.push('');
  out.push('Each text below is reproduced as the component ships it. Where several components ship');
  out.push('the identical text, they share one section.');
  out.push('');
  for (const group of licenceSections([...served, ...npm])) {
    out.push(`### ${group.components.map(c => `${c.name} ${c.version}`).join(', ')}`);
    out.push('');
    out.push('```text');
    out.push(group.text);
    out.push('```');
    out.push('');
  }

  const notices = [...served, ...npm].filter(c => c.noticeText !== null);
  if (notices.length > 0) {
    out.push('## NOTICE files');
    out.push('');
    out.push('Apache-2.0 section 4(d) asks that these travel with the work.');
    out.push('');
    for (const c of notices) {
      out.push(`### ${c.name} ${c.version}`);
      out.push('');
      out.push('```text');
      out.push(c.noticeText as string);
      out.push('```');
      out.push('');
    }
  }

  return out.join('\n');
}

function main(): void {
  const checkOnly = process.argv.includes('--check');
  const served = vendoredComponents();
  const npm = npmComponents();
  const content = render(served, npm);

  if (checkOnly) {
    const stale = OUTPUTS.filter(f => !existsSync(f) || readFileSync(f, 'utf-8') !== content);
    if (stale.length > 0) {
      console.error('✗ THIRD-PARTY-NOTICES.md is out of date:');
      for (const f of stale) console.error(`    ${f}`);
      console.error('  A dependency changed and the notices did not follow. Run: pnpm gen:notices');
      process.exit(1);
    }
    console.log(`✓ notices current: ${served.length} served components + ${npm.length} dependencies.`);
    return;
  }

  for (const file of OUTPUTS) writeFileSync(file, content, 'utf-8');
  const kb = Math.round(content.length / 1024);
  console.log(`✓ THIRD-PARTY-NOTICES.md written (${kb} kB): ${served.length} served components, ${npm.length} dependencies.`);
  for (const file of OUTPUTS) console.log(`    ${file}`);
}

main();
