/**
 * Assemble the extension action scripts: codec + engine + shared helpers + the action body.
 * The sandbox has no module system, so each action ships the whole engine inline.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = import.meta.dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
fs.mkdirSync(DIST, { recursive: true });

const read = (p) => fs.readFileSync(path.join(SRC, p), 'utf8');

// The Node interop tails would be dead weight in QuickJS; strip them from the bundle.
const strip = (s) => s.replace(/\nif \(typeof module !== 'undefined'[^\n]*\n?/g, '\n');

const codec = strip(read('codec.js'));
const engine = strip(read('engine.js'));
const common = read(path.join('actions', 'common.js'));

const HEADER = (name) => `/**
 * @file ${name}
 * @description Pixel Mirage extension action — generated by build.mjs from src/codec.js,
 *   src/engine.js, src/actions/common.js and src/actions/${name}. Edit those, not this.
 * @version-history
 *   v1.0.0 - 2026-07-25 - Agent-facing dither service.
 */
`;

const actions = ['dither.js', 'variants.js', 'styles.js'];
const bundles = {};
for (const a of actions) {
  const body = read(path.join('actions', a));
  const out = `${HEADER(a)}${codec}\n${engine}\n${common}\n${body}`;
  bundles[a] = out;
  fs.writeFileSync(path.join(DIST, a), out);
  const kb = Buffer.byteLength(out, 'utf8') / 1024;
  console.log(`${a}: ${kb.toFixed(1)} KB${kb > 256 ? '  ** OVER THE 256 KB SANDBOX LIMIT **' : ''}`);
  const exports = out.match(/export\s+default\s+/g) || [];
  if (exports.length !== 1) throw new Error(`${a}: expected exactly one "export default", found ${exports.length}`);
}

fs.writeFileSync(path.join(DIST, 'manifest.yaml'), fs.readFileSync(path.join(SRC, 'manifest.yaml')));
console.log('manifest.yaml copied');

// The studio inlines the SAME engine the sandbox runs, which is the whole point: a preview here
// and a render bought through the app-tool cannot drift apart.
const app = read('app.template.html').replace('/*__ENGINE__*/', engine);
if (app.includes('/*__ENGINE__*/')) throw new Error('engine placeholder not substituted');
fs.writeFileSync(path.join(DIST, 'pixel-mirage.html'), app);
console.log(`pixel-mirage.html: ${(Buffer.byteLength(app, 'utf8') / 1024).toFixed(1)} KB`);
