/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Action {
  actionId: string;
  category: string | null;
  createdAt: Generated<Timestamp>;
  description: string;
  displayName: string;
  estimatedTimeSeconds: number | null;
  federate: Generated<boolean>;
  id: Generated<string>;
  inputSchema: Json;
  maxInputSizeBytes: number | null;
  outputSchema: Json;
  pricingBaseMorsels: number;
  pricingPerUnit: Json | null;
  providerGaii: string;
  semantic: Json | null;
  tags: string[] | null;
  updatedAt: Timestamp;
  webhookUrl: string | null;
}

export interface Agent {
  activityStats: Json | null;
  agentLimitations: Json | null;
  allowedOrigins: string[] | null;
  capabilities: string[] | null;
  createdAt: Generated<Timestamp>;
  dailySpendLimit: number | null;
  defaultScopes: string[] | null;
  description: string | null;
  displayName: string | null;
  domainCapabilities: Json | null;
  federate: Generated<boolean>;
  gaii: string;
  id: Generated<string>;
  languages: Json | null;
  lastSeen: Generated<Timestamp>;
  maxConcurrentTasks: Generated<number>;
  mode: string | null;
  modulesLoaded: Json | null;
  morselBalance: Generated<number>;
  name: string;
  owner: string;
  platform: string | null;
  platformDetectedBy: string | null;
  platformVersion: string | null;
  publicKey: string;
  scheduleConstraintDefaults: Json | null;
  tags: string[] | null;
  technicalCapabilities: Json | null;
  trustScore: Generated<number>;
  webhookEnabled: Generated<boolean>;
  webhookFailCount: Generated<number>;
  webhookLastFailure: Timestamp | null;
  webhookLastSuccess: Timestamp | null;
  webhookSecret: string | null;
  webhookUrl: string | null;
}

export interface AgentActivity {
  agentGaii: string;
  date: string;
  hour: number;
  id: Generated<string>;
  metric: string;
  value: Generated<number>;
}

export interface AgentDirective {
  agentGaii: string;
  budgetLimits: Json | null;
  id: Generated<string>;
  memoryAreas: Generated<Json>;
  purpose: Generated<string>;
  resources: Generated<Json>;
  rules: Generated<Json>;
  updatedAt: Timestamp;
}

export interface AgentMessage {
  agentGaii: string;
  content: string;
  createdAt: Generated<Timestamp>;
  direction: string;
  id: Generated<string>;
  linkedTaskId: string | null;
  metadata: Json | null;
  processedAt: Timestamp | null;
  senderGaii: string;
  status: Generated<string>;
  threadId: string;
}

export interface AgentOnboarding {
  agentGaii: string;
  completedAt: Timestamp | null;
  detectedPlatform: string | null;
  healthComponents: Json | null;
  healthRecalculatedAt: Timestamp | null;
  id: Generated<string>;
  installedRuntime: string | null;
  onboardingBaseline: number | null;
  operationalHealth: number | null;
  readinessLevel: string | null;
  readinessOverride: Json | null;
  readinessScore: number | null;
  startedAt: Generated<Timestamp>;
  status: Generated<string>;
  steps: Generated<Json>;
}

export interface AgentTask {
  agentGaii: string;
  automation: Json | null;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deliverableKey: string | null;
  description: Generated<string>;
  id: Generated<string>;
  lastEventAt: Timestamp | null;
  ownerGaii: string;
  parentTaskId: string | null;
  rating: Json | null;
  resources: Json | null;
  rules: Generated<Json>;
  scope: Generated<Json>;
  status: Generated<string>;
  telemetry: Json | null;
  title: string;
  todos: Generated<Json>;
  triage: string | null;
  updatedAt: Timestamp;
  verification: Generated<Json>;
  workTrackingCode: string | null;
}

export interface AgentTaskEvent {
  details: Json | null;
  id: Generated<string>;
  message: string;
  taskId: string;
  timestamp: Generated<Timestamp>;
  type: string;
}

export interface AgentUsageDaily {
  agentGaii: string;
  apiKeyScope: Generated<string>;
  calls: Generated<number>;
  completionTokens: Generated<number>;
  costUsd: Generated<number>;
  date: string;
  id: Generated<string>;
  model: string;
  organismId: Generated<string>;
  ownerGhii: string;
  promptTokens: Generated<number>;
  provider: string;
  unpricedCalls: Generated<number>;
  workspaceId: Generated<string>;
}

export interface AgentUsageEvent {
  agentGaii: string;
  apiKeyScope: Generated<string>;
  capabilityId: string | null;
  completionTokens: Generated<number>;
  consumerGhii: string | null;
  costUsd: number | null;
  id: Generated<string>;
  model: string;
  organismId: string | null;
  ownerGhii: string;
  priceRef: string | null;
  promptTokens: Generated<number>;
  provider: string;
  runId: string | null;
  source: string;
  ts: string;
  workspaceId: string | null;
}

export interface App {
  accessCode: string | null;
  createdAt: Generated<Timestamp>;
  data: Buffer;
  filename: string;
  forkable: Generated<boolean>;
  id: Generated<string>;
  manifest: Json;
  mimeType: string;
  operatorHidden: Generated<boolean>;
  operatorHiddenAt: Timestamp | null;
  operatorHiddenBy: string | null;
  operatorHideReason: string | null;
  ownerGaii: string;
  ownerName: string;
  parked: Generated<boolean>;
  size: number;
  versionNumber: number;
}

export interface AppDownload {
  count: Generated<number>;
  filename: string;
  id: Generated<string>;
  ownerGaii: string;
}

export interface AppDraft {
  data: Buffer;
  filename: string;
  id: Generated<string>;
  manifest: Json;
  mimeType: string;
  ownerGaii: string;
  ownerName: string;
  size: number;
  updatedAt: Generated<Timestamp>;
}

export interface Appeal {
  appealedBy: string;
  createdAt: Generated<Timestamp>;
  flagId: string;
  id: Generated<string>;
  reason: string;
  reviewedAt: Timestamp | null;
  reviewedBy: string | null;
  reviewNote: string | null;
  status: Generated<string>;
}

export interface AppFork {
  childFilename: string;
  childOwnerGaii: string;
  childOwnerName: string;
  forkedAt: Generated<Timestamp>;
  forkedByGaii: string;
  id: Generated<string>;
  sourceFilename: string;
  sourceOwnerGaii: string;
  sourceOwnerName: string;
  sourceVersion: number;
}

export interface AppGrant {
  app: string;
  appName: string;
  appOrigin: string;
  createdAt: Generated<Timestamp>;
  gaii: string;
  grantId: string;
  id: Generated<string>;
  lastUsedAt: Timestamp | null;
  owner: string;
  refreshTokenHash: string | null;
  revoked: Generated<boolean>;
  scopes: string[] | null;
}

export interface AppPurchase {
  appContent: string;
  appFilename: string;
  appManifest: Json;
  appName: string;
  appScreenshot: string | null;
  appVersionNumber: number;
  buyerGaii: string;
  buyerOwner: string;
  id: Generated<string>;
  licenseType: string;
  nodeId: string;
  nodePublicKey: string;
  priceMorsels: number;
  purchasedAt: Generated<Timestamp>;
  sellerGaii: string;
  sellerOwner: string;
  signature: string;
  transactionFeeMorsels: number;
  transactionId: string;
}

export interface Board {
  allowedGaiis: string[] | null;
  boardId: string;
  createdAt: Generated<Timestamp>;
  description: string | null;
  federate: Generated<boolean>;
  id: Generated<string>;
  name: string;
  ownerGaii: string;
  visibility: string;
}

export interface BoardPost {
  authorGaii: string;
  boardId: string;
  body: string;
  category: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  postId: string;
  reactions: Generated<Json>;
  replyTo: string | null;
  tags: string[] | null;
  title: string;
  ttlExpiresAt: Timestamp | null;
}

export interface BoardSubscription {
  boardId: string;
  callbackUrl: string | null;
  createdAt: Generated<Timestamp>;
  filters: Json | null;
  gaii: string;
  id: Generated<string>;
}

export interface Capability {
  authRequired: Generated<string>;
  callable: Generated<boolean>;
  cost: Json | null;
  createdAt: Generated<Timestamp>;
  dependencies: Generated<Json>;
  deprecationMessage: string | null;
  examples: Generated<Json>;
  exports: Json | null;
  id: Generated<string>;
  inputSchema: Json | null;
  name: string;
  operatorOverride: Json | null;
  outputSchema: Json | null;
  ownerGhii: string;
  redactedFields: Generated<Json>;
  rejectionReason: string | null;
  replacedBy: string | null;
  schemaHash: Generated<string>;
  scope: Generated<string>;
  sourceRef: string;
  sourceType: string;
  sourceVersion: Generated<string>;
  stats: Json;
  status: Generated<string>;
  summary: Generated<string>;
  tags: Generated<Json>;
  trust: Json;
  trustRequired: number | null;
  updatedAt: Timestamp;
  usage: Generated<string>;
  visibility: Generated<string>;
  webhookUrl: string | null;
  whenNotToUse: Generated<string>;
  whenToUse: Generated<string>;
}

export interface CapabilityLog {
  callerGhii: string;
  capabilityId: string;
  durationMs: Generated<number>;
  error: string | null;
  id: Generated<string>;
  input: Generated<Json>;
  status: string;
  timestamp: Generated<Timestamp>;
}

export interface CapabilityVouch {
  capabilityId: string;
  comment: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  userGhii: string;
}

export interface ChatInstance {
  agentGaii: string | null;
  appName: string;
  createdAt: Generated<Timestamp>;
  ghii: string;
  id: Generated<string>;
  isAnonymous: Generated<boolean>;
  lastSeen: Generated<Timestamp>;
  mcpClientId: string | null;
  nodeId: string;
  ownerName: string;
  platform: string;
}

export interface Consent {
  dataPattern: string;
  expires: Timestamp | null;
  grantedAt: Generated<Timestamp>;
  id: Generated<string>;
  metadata: Json | null;
  ownerGaii: string;
  purpose: string;
  recipient: string;
  revokedAt: Timestamp | null;
  scope: string;
  status: Generated<string>;
}

export interface ConsentAudit {
  accessorGaii: string;
  action: string;
  allowed: boolean;
  consentId: string;
  id: Generated<string>;
  memoryKey: string;
  ownerGaii: string;
  timestamp: Generated<Timestamp>;
}

export interface ContactConsent {
  contactId: string;
  createdAt: Generated<Timestamp>;
  firstMessageId: string | null;
  id: Generated<string>;
  origin: Generated<string>;
  ownerGhii: string;
  state: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface CortexExtension {
  activatedAt: Timestamp | null;
  activationArtifacts: Json;
  aimeatCompat: string | null;
  apiVersion: string;
  author: string;
  components: Json;
  description: string;
  id: Generated<string>;
  installedAt: Generated<Timestamp>;
  installedBy: string;
  labels: Json;
  license: string | null;
  manifest: string;
  name: string;
  namespace: string;
  shortName: string;
  status: Generated<string>;
  tags: string[] | null;
  version: string;
  visibility: Generated<string>;
}

export interface CortexLibFile {
  content: string;
  extName: string;
  id: Generated<string>;
  libName: string;
}

export interface Csm {
  definition: Json;
  federate: Generated<boolean>;
  id: Generated<string>;
  jsonSchemaKey: string;
  name: string;
  registeredAt: Generated<Timestamp>;
  registeredBy: string;
  semantic: Json | null;
  serviceType: string;
  updatedAt: Timestamp;
}

export interface DeviceAuth {
  agentCredentials: Json | null;
  agentName: string;
  approvedBy: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  deviceCode: string;
  displayName: string | null;
  expiresAt: Timestamp;
  id: Generated<string>;
  lastPolledAt: Timestamp | null;
  mode: string | null;
  ownerName: string;
  pollInterval: Generated<number>;
  scopes: string[] | null;
  status: Generated<string>;
  userCode: string;
}

export interface DirectMessage {
  attachments: Json | null;
  body: Generated<string>;
  broadcastId: string | null;
  conversationId: string;
  createdAt: Generated<Timestamp>;
  deliveredAt: Timestamp | null;
  direction: string;
  error: string | null;
  id: Generated<string>;
  interactive: Json | null;
  mid: string;
  origin: Generated<string>;
  originNodeId: string;
  ownerGhii: string;
  readAt: Timestamp | null;
  recipientGhii: string;
  replyToId: string | null;
  respondable: boolean | null;
  senderGhii: string;
  status: Generated<string>;
  subject: string | null;
}

export interface Dispute {
  createdAt: Generated<Timestamp>;
  disputeId: string;
  id: Generated<string>;
  openedBy: string;
  reason: string;
  ruling: Json | null;
  status: string;
  trackingCode: string;
  updatedAt: Timestamp;
}

export interface DisputeAudit {
  actor: string;
  data: Json;
  disputeId: string;
  event: string;
  hash: string;
  id: Generated<string>;
  previousHash: string;
  sequence: number;
  timestamp: Timestamp;
}

export interface EcoAuth {
  app: string;
  appCredentials: Json | null;
  approvedBy: string | null;
  automation: Json | null;
  boundRef: string | null;
  capabilities: Json | null;
  createdAt: Generated<Timestamp>;
  dataAreas: Json | null;
  description: string | null;
  deviceCode: string;
  displayName: string | null;
  expiresAt: Timestamp;
  id: Generated<string>;
  lastPolledAt: Timestamp | null;
  ownerName: string;
  pollInterval: Generated<number>;
  publicKey: string | null;
  scopes: string[] | null;
  setup: Json | null;
  status: Generated<string>;
  userCode: string;
  validationResult: Json | null;
}

export interface EcoAutomationRecipe {
  agents: Json;
  app: string;
  createdAt: Generated<Timestamp>;
  email: Generated<boolean>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  organism: string | null;
  owner: string;
  requireApproval: Generated<boolean>;
  trigger: Json;
  updatedAt: Generated<Timestamp>;
}

export interface EcosystemApp {
  app: string;
  automation: Json | null;
  boundRef: string | null;
  capabilities: Json | null;
  createdAt: Generated<Timestamp>;
  dataAreas: Json | null;
  description: string | null;
  displayName: string | null;
  geai: string;
  id: Generated<string>;
  lastSeen: Generated<Timestamp>;
  morselBalance: Generated<number>;
  owner: string;
  publicKey: string;
  scopes: string[] | null;
  setup: Json | null;
  status: Generated<string>;
}

export interface EmailVerification {
  attempts: Generated<number>;
  code: string;
  createdAt: Generated<Timestamp>;
  emailHash: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  ownerName: string;
  purpose: string;
  status: Generated<string>;
  verifiedAt: Timestamp | null;
}

export interface EscrowHold {
  amount: number;
  createdAt: Generated<Timestamp>;
  extensionName: string;
  fromGaii: string;
  holdId: string;
  id: Generated<string>;
  reason: string;
  releasedAt: Timestamp | null;
  releasedTo: string | null;
  status: Generated<string>;
  updatedAt: Timestamp;
}

export interface ExecutionLog {
  actionId: string | null;
  createdAt: Generated<Timestamp>;
  durationMs: Generated<number>;
  errorMessage: string | null;
  extensionName: string | null;
  id: Generated<string>;
  jobId: string;
  jobName: string;
  memoryReads: Generated<Json>;
  memoryWrites: Generated<Json>;
  result: string;
  taskId: string | null;
  trigger: string;
  type: string;
}

export interface Extension {
  actions: Json;
  activatedAt: Timestamp | null;
  author: string;
  config: Json;
  createdAt: Generated<Timestamp>;
  description: string;
  federation: Json;
  id: Generated<string>;
  installedAt: Generated<Timestamp>;
  installedBy: string;
  instances: Json | null;
  limits: Json;
  name: string;
  requiredApis: string[] | null;
  status: Generated<string>;
  updatedAt: Timestamp;
  version: string;
}

export interface ExtensionInstance {
  config: Generated<Json>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  createdByAgent: string | null;
  extensionName: string;
  id: Generated<string>;
  instanceId: string;
  status: Generated<string>;
  translations: Json | null;
  updatedAt: Timestamp;
}

export interface FederationPeer {
  addedAt: Generated<Timestamp>;
  allowFederatedAuth: Generated<boolean>;
  allowRouting: Generated<boolean>;
  availability: string | null;
  availabilityPct: number | null;
  availabilityWindow: string | null;
  expiresAt: Timestamp | null;
  federationAuthScopes: Generated<string[] | null>;
  heartbeatOk: Generated<number>;
  heartbeatTotal: Generated<number>;
  lastSeen: Generated<Timestamp>;
  nodeCardHash: string | null;
  nodeId: string;
  peerMode: Generated<string>;
  publicKey: Generated<string>;
  replicateMemory: Generated<boolean>;
  shareCatalogue: Generated<boolean>;
  softwareVersion: string | null;
  status: Generated<string>;
  tier: Generated<string>;
  url: string;
}

export interface Flag {
  createdAt: Generated<Timestamp>;
  description: string | null;
  flaggedBy: string;
  id: Generated<string>;
  reason: string;
  reviewedAt: Timestamp | null;
  reviewedBy: string | null;
  status: Generated<string>;
  targetId: string;
  targetType: string;
}

export interface Feedback {
  body: string;
  category: string;
  context: Json | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  messages: Generated<Json>;
  sender: string;
  status: Generated<string>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface GenesisPeer {
  catalogueHash: string;
  createdAt: Generated<Timestamp>;
  genesisNodeId: string;
  genesisUrl: string;
  id: Generated<string>;
  lastSyncAt: Generated<Timestamp>;
  publicKey: string;
  status: Generated<string>;
  updatedAt: Timestamp;
}

export interface Ghii {
  allowedOrigins: string[] | null;
  avatar: string | null;
  bio: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  emailHash: string | null;
  emailVerifiedAt: string | null;
  externalIdentities: Json | null;
  ftnVerified: Generated<boolean>;
  ghii: string;
  googleSub: string | null;
  id: Generated<string>;
  lastLoginAt: string | null;
  locale: string | null;
  loginCount: Generated<number>;
  magicLinkEnabled: Generated<boolean>;
  morselBalance: number | null;
  nodeId: string;
  notificationEmail: string | null;
  ownerName: string;
  passwordHash: string | null;
  totpBackupCodes: string[] | null;
  totpEnabled: Generated<boolean>;
  totpFailedAttempts: Generated<number>;
  totpLastUsedAt: string | null;
  totpLastUsedCode: string | null;
  totpLockedUntil: string | null;
  totpSecret: string | null;
  trustScore: number | null;
  updatedAt: Timestamp;
  username: string;
  verificationCredentialHash: string | null;
  verificationIssuer: string | null;
  verificationLevel: Generated<number>;
  verificationMethod: string | null;
  verifiedAttributes: string[] | null;
}

export interface Invitation {
  acceptedAt: Timestamp | null;
  acceptedBy: string | null;
  createdAt: Timestamp;
  email: string;
  emailHash: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  invitedBy: string;
  message: string | null;
  organismId: string;
  orgRole: Generated<string>;
  provisionedOwner: string | null;
  returnUrl: string | null;
  status: Generated<string>;
  tokenHash: string;
  type: Generated<string>;
  workspaces: Json;
}

export interface JoinRequest {
  createdAt: Generated<Timestamp>;
  ghii: string;
  id: Generated<string>;
  message: string | null;
  organismId: string;
  reviewedAt: Timestamp | null;
  reviewedBy: string | null;
  status: Generated<string>;
}

export interface KnowledgeLink {
  description: string;
  id: Generated<string>;
  linkedAt: Generated<Timestamp>;
  linkedBy: string;
  relation: string;
  source: string;
  target: string;
}

export interface KnowledgeReview {
  action: string;
  customText: string | null;
  id: Generated<string>;
  operatorGaii: string;
  packageId: string;
  reason: string;
  timestamp: Generated<Timestamp>;
}

export interface Listing {
  availability: string | null;
  category: string;
  condition: string | null;
  createdAt: Generated<Timestamp>;
  description: string;
  flagCount: Generated<number>;
  id: Generated<string>;
  images: string[] | null;
  location: Json | null;
  memoryKey: string;
  ownerName: string;
  priceMorsels: number;
  sellerGhii: string;
  semantic: Json | null;
  status: Generated<string>;
  tags: string[] | null;
  title: string;
  updatedAt: Timestamp;
}

export interface MailboxItem {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  fromGaii: string;
  id: Generated<string>;
  payload: string;
  personalNodeId: string;
  retentionDays: number;
  sizeBytes: number;
  toGaii: string;
  type: string;
}

export interface Match {
  breakdown: Json;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  notifiedAt: Timestamp | null;
  profileA: string;
  profileB: string;
  respondedAt: Timestamp | null;
  score: number;
  status: Generated<string>;
}

export interface Memory {
  allowedOrigins: string[] | null;
  archived: Generated<boolean>;
  archivedAt: Timestamp | null;
  archivedBy: string | null;
  archivedRoot: string | null;
  byteSize: Generated<number>;
  createdAt: Generated<Timestamp>;
  flagCount: Generated<number>;
  groupId: string | null;
  id: Generated<string>;
  key: string;
  ownerGaii: string;
  searchBlob: string | null;
  searchTsv: Generated<string | null>;
  tags: string[] | null;
  trackable: Generated<boolean>;
  ttlHours: number | null;
  updatedAt: Timestamp;
  value: Json | null;
  version: Generated<number>;
  visibility: Generated<string>;
  workspaceRef: string | null;
}

export interface MemoryVersion {
  actor: string | null;
  event: string | null;
  id: Generated<string>;
  key: string;
  ownerGaii: string;
  recordedAt: Generated<Timestamp>;
  value: Json | null;
  version: number;
}

export interface MessageDeliveryLog {
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  httpStatus: number | null;
  id: Generated<string>;
  latencyMs: Generated<number>;
  messageId: string;
  origin: string;
  status: string;
  targetNodeId: string;
}

export interface MicroMemory {
  accessCode: string | null;
  entries: Json;
  gaii: string;
  id: Generated<string>;
  setName: string;
  updatedAt: Timestamp;
  visibility: string;
}

export interface Msm {
  actionsCount: number;
  authType: string;
  category: string;
  definition: Json;
  federate: Generated<boolean>;
  id: Generated<string>;
  name: string;
  registeredAt: Generated<Timestamp>;
  registeredBy: string;
  updatedAt: Timestamp;
}

export interface NodeKey {
  id: Generated<string>;
  privateKey: string;
  publicKey: string;
}

export interface NotificationPreference {
  channels: string[] | null;
  cooldownMinutes: Generated<number>;
  email: string | null;
  enabled: Generated<boolean>;
  id: Generated<string>;
  locale: string | null;
  notifyTypes: string[] | null;
  personalNodeId: string;
  quietHoursUtc: Json | null;
}

export interface NotificationTemplate {
  fields: Json;
  id: Generated<string>;
  locale: string;
  placeholders: string[] | null;
  templateId: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
}

export interface OAuthApproval {
  approvedAt: Generated<Timestamp>;
  clientId: string;
  gaii: string;
  id: Generated<string>;
  owner: string;
  scope: Generated<string>;
}

export interface OAuthClient {
  clientId: string;
  clientName: string;
  clientSecret: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  redirectUris: string[] | null;
}

export interface OAuthRefreshToken {
  clientId: string;
  createdAt: Generated<Timestamp>;
  gaii: string;
  id: Generated<string>;
  owner: string;
  roles: string[] | null;
  tokenHash: string;
}

export interface Organism {
  admins: string[] | null;
  agentGaiis: string[] | null;
  archived: Generated<boolean>;
  archivedAt: Timestamp | null;
  archivedBy: string | null;
  boardId: string;
  createdAt: Generated<Timestamp>;
  creatorGhii: string;
  description: string;
  id: Generated<string>;
  interests: string[] | null;
  joinPolicy: Generated<string>;
  location: Json | null;
  maxMembers: Generated<number>;
  members: string[] | null;
  memberVisibility: string | null;
  memoryNamespace: string;
  moderationConfig: Json;
  name: string;
  semantic: Json | null;
  type: string;
  updatedAt: Timestamp;
  visibility: Generated<string>;
}

export interface OrganismMembership {
  ghii: string;
  id: Generated<string>;
  invitedBy: string | null;
  invitedWorkspaces: Json | null;
  joinedAt: Generated<Timestamp>;
  organismId: string;
  role: string;
  status: Generated<string>;
}

export interface OrganismReputation {
  breakdown: Json;
  calculatedAt: Generated<Timestamp>;
  id: Generated<string>;
  organismId: string;
  score: number;
}

export interface Otk {
  action: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  initial: Generated<boolean>;
  key: string;
  ownerGaii: string;
  params: Json;
  sessionId: string | null;
  used: Generated<boolean>;
  usedAt: Timestamp | null;
}

export interface Owner {
  createdAt: Generated<Timestamp>;
  displayName: string | null;
  id: Generated<string>;
  name: string;
  publicKey: string;
  roles: string[] | null;
}

export interface OwnerAgentDefault {
  defaultMemoryAreas: Generated<Json>;
  defaultTokenBudget: number | null;
  id: Generated<string>;
  ownerGaii: string;
  rules: Generated<Json>;
  updatedAt: Timestamp;
}

export interface Package {
  author: string;
  authorGhii: string;
  category: Generated<string>;
  changelog: Generated<string>;
  components: Json;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  manifest: Generated<string>;
  name: string;
  packageGroupId: string;
  status: Generated<string>;
  tags: string[] | null;
  updatedAt: Timestamp;
  version: string;
  visibility: Generated<string>;
}

export interface PackageInstance {
  id: Generated<string>;
  installedAt: Generated<Timestamp>;
  installedComponents: Json;
  label: Generated<string>;
  owner: string;
  ownerGhii: string;
  packageGroupId: string;
  packageRecordId: string;
  packageVersion: string;
  status: Generated<string>;
  updatedAt: Timestamp;
}

export interface PeeringRequest {
  createdAt: Generated<Timestamp>;
  fromNodeId: string | null;
  fromNodeUrl: string;
  id: Generated<string>;
  message: string | null;
  publicKey: string | null;
  requestId: string;
  status: Generated<string>;
  targetUrl: string | null;
  toNodeId: string | null;
  updatedAt: Timestamp;
}

export interface PendingApproval {
  action: string;
  actor: string;
  approverRole: Generated<string>;
  arguments: Json | null;
  createdAt: Generated<Timestamp>;
  deadline: Timestamp | null;
  decidedAt: Timestamp | null;
  decidedBy: string | null;
  flowGateId: string | null;
  id: Generated<string>;
  organismId: string;
  prompt: string | null;
  resolutionNote: string | null;
  risk: Generated<string>;
  stageId: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface PersonalAccessToken {
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  gaii: string;
  grantOperator: Generated<boolean>;
  grantOwner: Generated<boolean>;
  id: Generated<string>;
  label: string;
  lastUsedAt: Timestamp | null;
  owner: string;
  readOwnerData: Generated<boolean>;
  revoked: Generated<boolean>;
  scopes: string[] | null;
  tokenHash: string;
}

export interface PersonalNode {
  agentGaiis: string[] | null;
  anchorNodeId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lastSeen: Generated<Timestamp>;
  mailboxQuotaBytes: number;
  mailboxUsedBytes: Generated<number>;
  ownerName: string;
  publicKey: string;
  status: Generated<string>;
  updatedAt: Timestamp;
  visibility: Generated<string>;
}

export interface PersonalPushSubscription {
  createdAt: Generated<Timestamp>;
  endpoint: string;
  failureCount: Generated<number>;
  id: Generated<string>;
  keys: Json;
  lastUsedAt: Timestamp | null;
  ownerName: string;
  personalNodeId: string;
}

export interface Purchase {
  buyerOwner: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  listingId: string;
  priceMorsels: number;
  ratingComment: string | null;
  ratingScore: number | null;
  sellerOwner: string;
  status: Generated<string>;
  totalCostMorsels: number;
  trackingCode: string;
  transactionFeeMorsels: number;
}

export interface PushSubscription {
  createdAt: Generated<Timestamp>;
  endpoint: string;
  id: Generated<string>;
  keys: Json;
  lastUsedAt: Generated<Timestamp>;
  ownerName: string;
}

export interface RealtimeRoom {
  appType: string;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<string>;
  isPublic: Generated<boolean>;
  lastActivityAt: Generated<Timestamp>;
  maxPeers: number;
  name: string;
  peerCount: Generated<number>;
  tags: string[] | null;
}

export interface ReplicationQueue {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lastAttemptAt: Timestamp | null;
  payload: string | null;
  status: Generated<string>;
  targetPeers: string[] | null;
  type: string;
}

export interface RevokedToken {
  expiresAt: number;
  id: Generated<string>;
  tokenHash: string;
}

export interface ScheduledJob {
  actionId: string | null;
  agentGaii: string | null;
  agentName: string | null;
  constraints: Json | null;
  coreHandler: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  createdByAgent: Generated<boolean>;
  cron: string;
  description: string | null;
  displayName: string | null;
  enabled: Generated<boolean>;
  extensionName: string | null;
  id: Generated<string>;
  input: Json | null;
  instanceId: string | null;
  lastRunAt: Timestamp | null;
  lastRunDurationMs: number | null;
  lastRunError: string | null;
  lastRunResult: string | null;
  name: string;
  nextRunAt: Timestamp | null;
  ownerScope: string | null;
  purpose: string | null;
  runCount: Generated<number>;
  timezone: string | null;
  type: string;
  updatedAt: Timestamp;
}

export interface SchemaLock {
  applyTo: string;
  id: Generated<string>;
  keyPattern: string;
  lockedBy: string;
  schemaJson: Json;
  schemaMode: Generated<string>;
  semanticContext: Json | null;
  setAt: Generated<Timestamp>;
  updatedAt: Timestamp;
}

export interface Session {
  absoluteExpiresAt: Timestamp | null;
  deviceLabel: string | null;
  expiresAt: Timestamp;
  gaii: string;
  id: Generated<string>;
  idleExpiresAt: Timestamp | null;
  issuedAt: Timestamp;
  lastUsedAt: Timestamp | null;
  owner: string;
  prevTokenHash: string | null;
  prevValidUntil: Timestamp | null;
  refreshTokenHash: string | null;
  revoked: Generated<boolean>;
  sessionId: string;
  userAgent: string | null;
}

export interface SharingGroup {
  createdAt: Generated<Timestamp>;
  defaultPermissions: Generated<Json>;
  description: string | null;
  id: Generated<string>;
  members: Generated<Json>;
  name: string;
  ownerGaii: string;
  updatedAt: Timestamp;
}

export interface SiteChangeLog {
  action: string;
  changedAt: Generated<Timestamp>;
  changedBy: string;
  id: Generated<string>;
  summary: string;
}

export interface StatsCounter {
  id: Generated<string>;
  value: Generated<number>;
}

export interface StatsDailyHistory {
  date: string;
  id: Generated<string>;
  key: string;
  value: Generated<number>;
}

export interface StorageStatsSnapshot {
  id: string;
  capturedAt: Timestamp;
  counts: Json;
  totalRows: Generated<number>;
}

export interface StorageFile {
  createdAt: Generated<Timestamp>;
  data: Buffer;
  federate: Generated<boolean>;
  groupId: string | null;
  id: Generated<string>;
  key: string;
  mimeType: string;
  ownerGaii: string;
  size: number;
  tags: Generated<string[] | null>;
  visibility: string;
  workspaceRef: string | null;
}

export interface SubdomainSite {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  enabled: Generated<boolean>;
  id: Generated<string>;
  kind: string;
  subdomain: string;
  target: string;
  updatedAt: Generated<Timestamp>;
}

export interface SystemPrompt {
  active: Generated<boolean>;
  content: string;
  description: Generated<string>;
  group: string;
  id: Generated<string>;
  locales: Json | null;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  usedIn: string[] | null;
  variables: string[] | null;
  version: Generated<number>;
}

export interface SystemPromptVersion {
  changedAt: Generated<Timestamp>;
  changedBy: string;
  changeNote: string | null;
  content: string;
  id: Generated<string>;
  locales: Json | null;
  promptId: string;
  version: number;
}

export interface SystemSetting {
  id: Generated<string>;
  key: string;
  value: string;
}

export interface TelemetryEvent {
  agentGaii: string;
  createdAt: Generated<Timestamp>;
  data: Json;
  id: Generated<string>;
  sessionId: string | null;
  taskId: string | null;
  type: string;
}

export interface TemplateDiscussion {
  authorGhii: string;
  authorName: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  listingId: string;
  message: string;
  parentId: string | null;
}

export interface TemplateListing {
  category: Generated<string>;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  featured: Generated<boolean>;
  id: Generated<string>;
  installCount: Generated<number>;
  packageAuthor: string;
  packageGroupId: string;
  packageName: string;
  proposedAt: Timestamp | null;
  proposedBy: string | null;
  publishedBy: string;
  publishedByGhii: string;
  rating: Generated<number>;
  rejectionReason: string | null;
  reviewComment: string | null;
  reviewCount: Generated<number>;
  reviewedAt: Timestamp | null;
  reviewedBy: string | null;
  screenshots: string[] | null;
  status: Generated<string>;
  tags: string[] | null;
  title: string;
  updatedAt: Timestamp;
}

export interface TemplateReview {
  authorGhii: string;
  authorName: string;
  comment: Generated<string>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  listingId: string;
  rating: number;
}

export interface Transaction {
  amount: number;
  counterpartyGaii: string | null;
  gaii: string;
  id: Generated<string>;
  timestamp: Generated<Timestamp>;
  trackingCode: string | null;
  txId: string;
  type: string;
}

export interface TrustedIssuer {
  addedBy: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  publicKey: string;
  trusted: Generated<boolean>;
  type: string;
  url: string;
}

export interface VerificationNonce {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  nonce: string;
  owner: string;
  redirectUri: Generated<string>;
  state: string;
  type: string;
}

export interface WebhookDeliveryLog {
  agentGaii: string;
  attemptCount: number;
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  event: string;
  httpStatus: number | null;
  id: Generated<string>;
  latencyMs: number;
  payload: Json;
  status: string;
}

export interface Work {
  actionId: string;
  callbackUrl: string | null;
  costBasePrice: number;
  costInEscrow: number;
  costNetworkFee: number;
  costTotal: number;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  input: Json;
  output: Json | null;
  providerGaii: string;
  ratingComment: string | null;
  ratingScore: number | null;
  requesterGaii: string;
  status: string;
  trackingCode: string;
  ttlExpiresAt: Timestamp;
  updatedAt: Timestamp;
}

export interface DB {
  Action: Action;
  Agent: Agent;
  AgentActivity: AgentActivity;
  AgentDirective: AgentDirective;
  AgentMessage: AgentMessage;
  AgentOnboarding: AgentOnboarding;
  AgentTask: AgentTask;
  AgentTaskEvent: AgentTaskEvent;
  AgentUsageDaily: AgentUsageDaily;
  AgentUsageEvent: AgentUsageEvent;
  App: App;
  AppDownload: AppDownload;
  AppDraft: AppDraft;
  Appeal: Appeal;
  AppFork: AppFork;
  AppGrant: AppGrant;
  AppPurchase: AppPurchase;
  Board: Board;
  BoardPost: BoardPost;
  BoardSubscription: BoardSubscription;
  Capability: Capability;
  CapabilityLog: CapabilityLog;
  CapabilityVouch: CapabilityVouch;
  ChatInstance: ChatInstance;
  Consent: Consent;
  ConsentAudit: ConsentAudit;
  ContactConsent: ContactConsent;
  CortexExtension: CortexExtension;
  CortexLibFile: CortexLibFile;
  Csm: Csm;
  DeviceAuth: DeviceAuth;
  DirectMessage: DirectMessage;
  Dispute: Dispute;
  DisputeAudit: DisputeAudit;
  EcoAuth: EcoAuth;
  EcoAutomationRecipe: EcoAutomationRecipe;
  EcosystemApp: EcosystemApp;
  EmailVerification: EmailVerification;
  EscrowHold: EscrowHold;
  ExecutionLog: ExecutionLog;
  Extension: Extension;
  ExtensionInstance: ExtensionInstance;
  FederationPeer: FederationPeer;
  Feedback: Feedback;
  Flag: Flag;
  GenesisPeer: GenesisPeer;
  Ghii: Ghii;
  Invitation: Invitation;
  JoinRequest: JoinRequest;
  KnowledgeLink: KnowledgeLink;
  KnowledgeReview: KnowledgeReview;
  Listing: Listing;
  MailboxItem: MailboxItem;
  Match: Match;
  Memory: Memory;
  MemoryVersion: MemoryVersion;
  MessageDeliveryLog: MessageDeliveryLog;
  MicroMemory: MicroMemory;
  Msm: Msm;
  NodeKey: NodeKey;
  NotificationPreference: NotificationPreference;
  NotificationTemplate: NotificationTemplate;
  OAuthApproval: OAuthApproval;
  OAuthClient: OAuthClient;
  OAuthRefreshToken: OAuthRefreshToken;
  Organism: Organism;
  OrganismMembership: OrganismMembership;
  OrganismReputation: OrganismReputation;
  Otk: Otk;
  Owner: Owner;
  OwnerAgentDefault: OwnerAgentDefault;
  Package: Package;
  PackageInstance: PackageInstance;
  PeeringRequest: PeeringRequest;
  PendingApproval: PendingApproval;
  PersonalAccessToken: PersonalAccessToken;
  PersonalNode: PersonalNode;
  PersonalPushSubscription: PersonalPushSubscription;
  Purchase: Purchase;
  PushSubscription: PushSubscription;
  RealtimeRoom: RealtimeRoom;
  ReplicationQueue: ReplicationQueue;
  RevokedToken: RevokedToken;
  ScheduledJob: ScheduledJob;
  SchemaLock: SchemaLock;
  Session: Session;
  SharingGroup: SharingGroup;
  SiteChangeLog: SiteChangeLog;
  StatsCounter: StatsCounter;
  StatsDailyHistory: StatsDailyHistory;
  StorageFile: StorageFile;
  StorageStatsSnapshot: StorageStatsSnapshot;
  SubdomainSite: SubdomainSite;
  SystemPrompt: SystemPrompt;
  SystemPromptVersion: SystemPromptVersion;
  SystemSetting: SystemSetting;
  TelemetryEvent: TelemetryEvent;
  TemplateDiscussion: TemplateDiscussion;
  TemplateListing: TemplateListing;
  TemplateReview: TemplateReview;
  Transaction: Transaction;
  TrustedIssuer: TrustedIssuer;
  VerificationNonce: VerificationNonce;
  WebhookDeliveryLog: WebhookDeliveryLog;
  Work: Work;
}
