/**
 * @file launcher.ts
 * @author Jouni Miikki
 * SPDX-License-Identifier: MIT
 * @description Generates the two small scripts a connected client needs, so a token never has to
 *   live inside a config file: a LAUNCHER that exports the agent token and starts the client in a
 *   sane working directory, and a HEADERS HELPER that prints an Authorization header on stdout for
 *   clients that can call one (Claude Code's `headersHelper`).
 * @structure
 *   - writeLauncher() — `<home>/launch-<client>.ps1` + `.sh`, chmod +x on POSIX.
 *   - writeHeadersHelper() — `<home>/auth-header.ps1` + `.sh`, prints `Authorization: Bearer <token>`.
 * @usage Called by clients/*.ts via the shared connect flow.
 * @version-history
 *   v1.0.0 — 2026-08-02 — Initial creation: one-command client connect.
 */

import { chmodSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ClientTarget } from './types.js';

/** True on Windows, where the .ps1 variant is the one that gets used. */
const isWindows = process.platform === 'win32';

/**
 * Write the launcher pair for one client. The launcher reads the token from the connector home at
 * run time (so a re-authenticated agent is picked up with no config edit), sets the working
 * directory, and execs the client's own command.
 *
 * Returns the path of the script that is actually usable on this platform first.
 */
export function writeLauncher(target: ClientTarget, clientId: string, command: string, args: string[] = []): string[] {
    const argLine = args.length ? ` ${args.join(' ')}` : '';
    const ps1 = join(target.home, `launch-${clientId}.ps1`);
    const sh = join(target.home, `launch-${clientId}.sh`);

    writeFileSync(ps1, [
        `# Starts ${clientId} with the AIMEAT agent "${target.agent}@${target.owner}" attached.`,
        `# Generated by: aimeat connect client ${clientId}`,
        `$ErrorActionPreference = 'Stop'`,
        `$env:AIMEAT_HOME = '${target.home}'`,
        `$tokenFile = '${target.tokenFile}'`,
        `if (-not (Test-Path $tokenFile)) { Write-Error "No token at $tokenFile. Run: aimeat connect client ${clientId}"; exit 1 }`,
        `$env:AIMEAT_AGENT_TOKEN = (Get-Content $tokenFile -Raw).Trim()`,
        `$workdir = '${target.workdir}'`,
        `if (-not (Test-Path $workdir)) { New-Item -ItemType Directory -Force $workdir | Out-Null }`,
        `Set-Location $workdir`,
        `${command}${argLine} @args`,
        '',
    ].join('\r\n'), 'utf8');

    writeFileSync(sh, [
        '#!/usr/bin/env bash',
        `# Starts ${clientId} with the AIMEAT agent "${target.agent}@${target.owner}" attached.`,
        `# Generated by: aimeat connect client ${clientId}`,
        'set -euo pipefail',
        `export AIMEAT_HOME="${target.home.replace(/\\/g, '/')}"`,
        `TOKEN_FILE="${target.tokenFile.replace(/\\/g, '/')}"`,
        `[ -f "$TOKEN_FILE" ] || { echo "No token at $TOKEN_FILE. Run: aimeat connect client ${clientId}" >&2; exit 1; }`,
        'export AIMEAT_AGENT_TOKEN="$(tr -d "\\r\\n" < "$TOKEN_FILE")"',
        `mkdir -p "${target.workdir.replace(/\\/g, '/')}"`,
        `cd "${target.workdir.replace(/\\/g, '/')}"`,
        `exec ${command}${argLine} "$@"`,
        '',
    ].join('\n'), 'utf8');

    // eslint-disable-next-line aimeat/no-silent-catch -- Windows has no exec bit; the .ps1 is the usable script there and a failed chmod changes nothing.
    try { chmodSync(sh, 0o755); } catch { /* no exec bit on this platform */ }
    return isWindows ? [ps1, sh] : [sh, ps1];
}

/**
 * Write the headers-helper pair. Claude Code runs this at connection time and merges its stdout
 * into the request headers, which keeps the token out of ~/.claude.json entirely and picks up a
 * refreshed token automatically.
 */
export function writeHeadersHelper(target: ClientTarget): { ps1: string; sh: string; preferred: string } {
    const ps1 = join(target.home, 'auth-header.ps1');
    const sh = join(target.home, 'auth-header.sh');

    writeFileSync(ps1, [
        '# Prints the AIMEAT Authorization header for an MCP client that asks for one.',
        '# Generated by: aimeat connect client',
        `$t = (Get-Content '${target.tokenFile}' -Raw).Trim()`,
        `Write-Output "Authorization: Bearer $t"`,
        '',
    ].join('\r\n'), 'utf8');

    writeFileSync(sh, [
        '#!/usr/bin/env bash',
        '# Prints the AIMEAT Authorization header for an MCP client that asks for one.',
        '# Generated by: aimeat connect client',
        'set -euo pipefail',
        `echo "Authorization: Bearer $(tr -d '\\r\\n' < "${target.tokenFile.replace(/\\/g, '/')}")"`,
        '',
    ].join('\n'), 'utf8');

    // eslint-disable-next-line aimeat/no-silent-catch -- same as above: no exec bit on Windows, the .ps1 variant is what gets used.
    try { chmodSync(sh, 0o755); } catch { /* no exec bit on this platform */ }
    return { ps1, sh, preferred: isWindows ? ps1 : sh };
}
