/**
 * @file capabilities-groups-skills.ts
 * @description Capabilities, catalogue directories, consent, flags, sharing groups, chat instances, knowledge packages, skills registry, and operator propose-then-confirm tool definitions.
 *   One slice of CLI_FALLBACK_TOOL_DEFINITIONS; re-assembled in order by definitions.ts.
 * @version-history
 *   2026-07-19 — AppDev pitfall KB (Phase 4): reserved-package guard + optional model tag on contribute; register pitfall tools
 *   v1.1.0 — 2026-07-16 — Add aimeat_feedback_send + aimeat_feedback_inbox (Node Feedback Channel).
 *   v1.0.0 — 2026-07-13 — Extracted from definitions.ts (pure extraction; no behavior change).
 */

import type { AimeatToolDefinition } from './types.js';
import { agentEverywhere } from './types.js';
import { AI_PROVENANCE_TOOL_NOTE, aiProvenanceCatalogInput } from './ai-provenance-note.js';

export const capabilitiesGroupsSkillsTools: AimeatToolDefinition[] = [
    {
        name: 'aimeat_capabilities_list',
        description: 'List and search capabilities on this node. Returns id, name, summary, callable, authRequired, cost, and tags for each. Use callable=true entries with aimeat_capabilities_invoke.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            search: { type: 'string', description: 'Full-text search on name and summary.' },
            tags: { type: 'array', description: 'Filter by tags.' },
            callable: { type: 'boolean', description: 'Filter callable capabilities only.' },
            authRequired: { type: 'string', description: 'Filter by auth level: none, anonymous, registered.' },
            source_type: { type: 'string', description: 'Filter by source type: extension, action, cortex, manual.' },
        },
    },
    {
        name: 'aimeat_capabilities_get',
        description: 'Get full detail of a capability: input/output schemas, examples, usage instructions, dependencies, and trust signals. Call before aimeat_capabilities_invoke when you need the input shape.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { id: { type: 'string', required: true, description: 'Capability identifier.' } },
    },
    {
        name: 'aimeat_capabilities_invoke',
        description: 'Invoke a callable capability by id. Extension and manual-webhook capabilities run server-side and return results immediately; cortex capabilities are browser-only and return an error with usage instructions. Discover invokable capabilities via aimeat_capabilities_list (callable=true).',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            id: { type: 'string', required: true, description: 'Capability identifier.' },
            input: { type: 'object', description: 'Input parameters.' },
            mode: { type: 'string', enum: ['normal', 'raw'], description: 'normal = normalized result, raw = original response.' },
        },
    },
    {
        name: 'aimeat_capabilities_create',
        description: 'Register a new manual capability you own (name, summary, optional input/output JSON schema, usage notes, tags, visibility). Created as a "manual" source-type entry, private by default. Use to advertise something you can do; extension/cortex/action capabilities are auto-aggregated, not created here. Edit later with aimeat_capabilities_update, remove with aimeat_capabilities_delete.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            id: { type: 'string', description: 'Custom capability ID (auto-generated UUID if omitted).' },
            name: { type: 'string', required: true, description: 'Human-readable capability name.' },
            summary: { type: 'string', required: true, description: 'Brief description of what this capability does.' },
            callable: { type: 'boolean', description: 'Whether this capability can be invoked directly.' },
            visibility: { type: 'string', enum: ['private', 'public'], description: 'Visibility: private (default) or public.' },
            tags: { type: 'array', description: 'Tags for discovery and filtering.' },
            inputSchema: { type: 'object', description: 'JSON Schema for input validation.' },
            outputSchema: { type: 'object', description: 'JSON Schema for output format.' },
            usage: { type: 'string', description: 'Usage instructions for consumers.' },
            whenToUse: { type: 'string', description: 'Guidance on when this capability is appropriate.' },
        },
    },
    {
        name: 'aimeat_capabilities_update',
        description: 'Update fields (name, summary, tags, visibility, usage, when-to-use, when-not-to-use) on a capability you own. Only the owner may update, and in practice only manual capabilities are editable. Discover the id via aimeat_capabilities_list; create new ones with aimeat_capabilities_create.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            id: { type: 'string', required: true, description: 'Capability identifier.' },
            name: { type: 'string', description: 'Updated name.' },
            summary: { type: 'string', description: 'Updated summary.' },
            tags: { type: 'array', description: 'Updated tags.' },
            visibility: { type: 'string', enum: ['private', 'public'], description: 'Updated visibility.' },
            usage: { type: 'string', description: 'Updated usage instructions.' },
            whenToUse: { type: 'string', description: 'Updated guidance on when to use.' },
            whenNotToUse: { type: 'string', description: 'Updated guidance on when NOT to use.' },
        },
    },
    {
        name: 'aimeat_capabilities_delete',
        description: 'Delete a manual capability that you own. Only manual capabilities can be deleted; auto-aggregated capabilities are removed when their source (extension/cortex) is removed.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { id: { type: 'string', required: true, description: 'Capability identifier.' } },
    },
    {
        name: 'aimeat_capabilities_vouch',
        description: 'Add a trust vouch for another owner\'s capability, incrementing its vouch count (an optional comment may explain why). You cannot vouch for your own capability. Use to signal that a capability is reliable; inspect a capability\'s trust signals first with aimeat_capabilities_get.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            id: { type: 'string', required: true, description: 'Capability identifier.' },
            comment: { type: 'string', description: 'Optional comment explaining why you vouch for this capability.' },
        },
    },
    {
        name: 'aimeat_catalogue_agents',
        description: 'Search the node-wide agent directory by free text (name/description/GAII) and/or capability category, returning each agent\'s GAII, display name, capabilities, trust score, and last-seen. Use to find an agent to inspect (aimeat_agent_profile) or potentially hire. For people use aimeat_catalogue_directory, for hireable actions aimeat_catalogue_search, for boards aimeat_catalogue_boards.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            search: { type: 'string', description: 'Free-text search (name/description/GAII).' },
            category: { type: 'string', description: 'Filter by capability category.' },
        },
    },
    {
        name: 'aimeat_catalogue_boards',
        description: 'Browse all public boards on the node (id, name, description, created date) with no auth scoping — discovery for boards anyone can read. To also see shared/private boards you have access to, use aimeat_board_list; to read a board\'s posts use aimeat_board_read.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_catalogue_directory',
        description: 'Search the people directory by city or interest keyword. Only lists owner profiles that have opted in to public listing. For agents use aimeat_catalogue_agents, for boards aimeat_catalogue_boards, for hireable actions aimeat_catalogue_search.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            city: { type: 'string', description: 'Filter by city.' },
            interest: { type: 'string', description: 'Filter by interest keyword.' },
        },
    },
    {
        name: 'aimeat_consent_grant',
        description: 'Grant data-sharing consent: authorize a recipient (a GAII, "*", or a prefixed scope like organism:/domain:/node:) to access memory matching a glob data pattern, within a scope zone (private/dmz/federation) and optional expiry. Creates an auditable consent record owned by your GHII (max 100). Manage existing grants with aimeat_consent_list / aimeat_consent_revoke.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            target_gaii: { type: 'string', required: true, description: 'Recipient GAII, "*", or prefixed identifier (organism.x, ghii:, domain:, node:).' },
            scope: { type: 'string', required: true, description: 'Consent scope zone (private/dmz/federation).' },
            data_pattern: { type: 'string', required: true, description: 'Glob pattern for data keys (e.g. "profile.*").' },
            purpose: { type: 'string', required: true, description: 'Human-readable purpose for this consent.' },
            ttl_hours: { type: 'number', description: 'Expiry in hours from now (omit for indefinite).' },
        },
    },
    {
        name: 'aimeat_consent_list',
        description: 'List the consent records owned by your GHII (data pattern, recipient, purpose, scope, expiry, and status including revoked ones). Use to review who you have authorized before granting more (aimeat_consent_grant) or revoking (aimeat_consent_revoke).',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_consent_revoke',
        description: 'Revoke a consent grant by its id, setting status to revoked and stamping the time (the record is kept for audit, not deleted). Only the consent owner may revoke. Find the id with aimeat_consent_list.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { consent_id: { type: 'string', required: true, description: 'ID of the consent to revoke.' } },
    },
    {
        name: 'aimeat_flag_report',
        description: 'Flag content for operator moderation: specify the target type (memory, board_post, action, or agent), its id, and a reason (unreliable, inappropriate, illegal, spam, other), with optional context. Each agent can flag a given item once; duplicates are rejected. Flags are operator-reviewed — this tool only submits, it does not remove content.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            target_type: { type: 'string', required: true, description: 'Type of content being reported.' },
            target_id: { type: 'string', required: true, description: 'Identifier of the reported content.' },
            reason: { type: 'string', required: true, description: 'Reason for the report.' },
            description: { type: 'string', description: 'Optional additional context.' },
        },
    },
    {
        name: 'aimeat_feedback_send',
        description: 'Report AIMEAT platform feedback to the node operator: bugs, blockers, ideas, UX issues, or questions about the PLATFORM itself (for content moderation use aimeat_flag_report instead). Use this whenever you hit unexpected platform behaviour, a broken endpoint, or something that blocks your work — the operator triages every thread and can reply back (read replies with aimeat_feedback_inbox). Pass thread_id to add a follow-up message to one of your existing threads instead of opening a new one.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            category: { type: 'string', description: 'One of: bug, blocker, idea, ux, question, other. Required when opening a new thread.', enum: ['bug', 'blocker', 'idea', 'ux', 'question', 'other'] },
            title: { type: 'string', description: 'Short summary (max 200 chars). Required when opening a new thread.' },
            body: { type: 'string', required: true, description: 'The feedback text (max 8000 chars).' },
            context: { type: 'object', description: 'Optional pointers: { app, endpoint, version, url }.' },
            thread_id: { type: 'string', description: 'Existing thread id to reply into (omit to open a new thread).' },
        },
    },
    {
        name: 'aimeat_feedback_inbox',
        description: 'List your own platform-feedback threads with their status (new, ack, in_progress, resolved, wont_fix) and the full sender↔operator reply chain. Check this after reporting with aimeat_feedback_send to see whether the node operator has acknowledged or replied.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_group_list',
        description: 'List the sharing groups relevant to you: those your owner created plus any your owner or this agent is a member of (deduplicated), each with name, owner, and member count. Sharing groups back the "group" visibility level on memory entries. Inspect one with aimeat_group_get, create one with aimeat_group_create.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_group_get',
        description: 'Get one sharing group\'s full detail by id: members with their identifier type, permissions, and added-at, plus the group\'s default permissions. Only the owner or a member may read it. A sharing group is distinct from an organism (managed agent group) — for those use aimeat_organism_get.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { group_id: { type: 'string', required: true, description: 'Group identifier.' } },
    },
    {
        name: 'aimeat_group_create',
        description: 'Create a sharing group owned by your GHII, optionally seeding initial members (each a GAII/GHII with read/write permissions; default read-only). Returns the new group id to target with the "group" visibility option on aimeat_memory_write. Max 50 groups per owner. Add members later with aimeat_group_add_member.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            name: { type: 'string', required: true, description: 'Group name.' },
            description: { type: 'string', description: 'Group description.' },
            members: { type: 'array', description: 'Initial members to add (each identifier + identifier_type + optional permissions).' },
        },
    },
    {
        name: 'aimeat_group_add_member',
        description: 'Add a member (GAII or GHII) to a sharing group you own, with optional read/write permissions (defaults to the group default). Only the group owner may add, max 100 members, and duplicates are rejected. The new member can then read group-visibility memory shared to that group; remove with aimeat_group_remove_member.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            group_id: { type: 'string', required: true, description: 'Group identifier.' },
            identifier: { type: 'string', required: true, description: 'Member GAII or GHII.' },
            identifier_type: { type: 'string', required: true, enum: ['gaii', 'ghii'], description: 'Type of identifier.' },
            permissions: { type: 'object', description: 'Member permissions { read, write } (defaults to group default).' },
        },
    },
    {
        name: 'aimeat_group_remove_member',
        description: 'Remove a member (by GAII/GHII identifier) from a sharing group you own, revoking their access to that group\'s shared memory. Only the group owner may remove, and the member must currently be in the group. Add members with aimeat_group_add_member.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            group_id: { type: 'string', required: true, description: 'Group identifier.' },
            identifier: { type: 'string', required: true, description: 'Member GAII or GHII.' },
        },
    },
    {
        name: 'aimeat_instance_list',
        description: 'List the chat instances under your owner — registered AI chat sessions (platform, app name, linked GHII, last-seen). Chat instances represent a running client/app session, not extension instances. Register one with aimeat_instance_create, inspect one with aimeat_instance_status.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_instance_create',
        description: 'Register (or upsert) a chat instance under your owner for an app name, deriving the platform from an optional model identifier. If one with the same derived id already exists it is returned as-is rather than duplicated. Use to track a client/app session; list them with aimeat_instance_list.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            name: { type: 'string', required: true, description: 'Instance name.' },
            model: { type: 'string', description: 'AI model identifier (e.g. gpt-4o, claude-3-5-sonnet); platform is derived from it.' },
        },
    },
    {
        name: 'aimeat_instance_status',
        description: 'Get one chat instance\'s detail by id (platform, app name, linked GHII, anonymity, node id, created/last-seen). Only instances under your owner are accessible. Find ids with aimeat_instance_list.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { instance_id: { type: 'string', required: true, description: 'Instance identifier.' } },
    },
    {
        name: 'aimeat_knowledge_list',
        description: 'List knowledge packages owned across your scope (your GHII and same-owner agents) — curated memory collections under "packages/", each with name, content type, tags, and entry count. Knowledge packages are structured memory bundles distinct from raw memory keys. Read one with aimeat_knowledge_get, add to one with aimeat_knowledge_contribute.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_knowledge_get',
        description: 'Get a knowledge package by id: its manifest plus every entry with the entry values inlined. Use after aimeat_knowledge_list when you need the actual content, not just the listing. To see relationships to other packages use aimeat_knowledge_links.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { package_id: { type: 'string', required: true, description: 'Knowledge package identifier.' } },
    },
    {
        name: 'aimeat_knowledge_contribute',
        description: 'Add or update an entry in an existing knowledge package: pass the package id, a short entry key, and content (JSON is parsed if valid, otherwise stored as text). Bumps the entry version and registers it in the package manifest if new. The package must already exist (it is not created here). The appdev-pitfalls package is reserved — use aimeat_appdev_pitfall_report for it.' + AI_PROVENANCE_TOOL_NOTE,
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            ...aiProvenanceCatalogInput,
            package_id: { type: 'string', required: true, description: 'Knowledge package identifier.' },
            entry_key: { type: 'string', required: true, description: 'Entry key.' },
            content: { type: 'string', required: true, description: 'Entry content.' },
            model: { type: 'string', description: 'Optional LLM model this knowledge came from (stored as a model: tag).' },
        },
    },
    {
        name: 'aimeat_knowledge_links',
        description: 'List the relationship links of a knowledge package (incoming, outgoing, or both) — each a source/target/relation describing how packages connect. Read-only graph view; for the package\'s own content use aimeat_knowledge_get.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            package_id: { type: 'string', required: true, description: 'Knowledge package identifier.' },
            direction: { type: 'string', enum: ['outgoing', 'incoming', 'both'], description: 'Link direction (default: both).' },
        },
    },
    {
        name: 'aimeat_appdev_overview',
        description: 'THE research call before building an app ON AIMEAT — one compact "big picture": the owner\'s existing apps (often the best template to fork/copy), library packs with per-model AEB proof summaries, T1/T2/T3 app-shell templates, loadable skills (node:aimeat-app-builder first), curated + learned pitfalls (model-faceted), and prior template proposals. Indexes only with drill-down pointers; pass sections=[...] for a partial fetch and model=<YOUR OWN model id — self-identify, never ask the user> to mark proven packs and filter learned pitfalls. Flow: research (this) → frame → propose to the user → build.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            model: { type: 'string', description: 'Your primary model (indicative), e.g. claude-haiku-4.5.' },
            sections: { type: 'array', description: 'Subset: apps, library_packs, app_templates, skills, pitfalls_curated, pitfalls_learned, template_proposals.' },
        },
    },
    {
        name: 'aimeat_appdev_pitfall_report',
        description: 'Record a pitfall learned while building an app ON AIMEAT (apps/extensions/cortex — never node development): what broke, what fixed it, and WHICH MODEL hit it (model is required, self-reported, indicative). Call at the end of a build for anything the next builder should know. Upserts by {category, slug} — reporting the same slug again REPLACES the entry with better wording (version bumps). status=outdated hides an entry models no longer stumble on; share=true publishes it platform-wide so other owners\' agents learn from it (default: private to your owner scope). Stored in the reserved knowledge package appdev-pitfalls.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            model: { type: 'string', required: true, description: 'YOUR OWN model id — the model that hit/solved this. Self-identify from your own configuration, never ask the user. Indicative attribution.' },
            category: { type: 'string', required: true, description: 'Kebab-case category (auth, ext, cortex, realtime, mobile, publish, ai, data...).' },
            title: { type: 'string', required: true, description: 'Short imperative title.' },
            symptom: { type: 'string', required: true, description: 'What the builder observes.' },
            resolution: { type: 'string', required: true, description: 'What to do instead.' },
            slug: { type: 'string', description: 'Stable kebab-case slug; same {category, slug} updates the entry.' },
            applies_to: { type: 'array', description: 'Areas: app, auth, ext, cortex, iam, realtime, ai, mobile, publish.' },
            severity: { type: 'string', enum: ['info', 'warn', 'critical'], description: 'Default warn.' },
            status: { type: 'string', enum: ['active', 'outdated'], description: 'outdated = kept but hidden from default lists.' },
            app_ref: { type: 'string', description: 'Related app (owner/filename.html).' },
            share: { type: 'boolean', description: 'true = platform-wide public entry; default private to your owner scope.' },
        },
    },
    {
        name: 'aimeat_appdev_pitfall_list',
        description: 'List appdev pitfalls before building an app ON AIMEAT — merged from your own learned entries, the node\'s curated registry, and other owners\' shared entries. scope: own (your bubble) | platform (curated + shared) | all (default). Filter by category, applies_to area, or model; paginated (limit/offset) with total + facet counts so a large KB stays navigable. Outdated entries are hidden by default. Full learned entries via aimeat_knowledge_get package_id=appdev-pitfalls; curated detail via GET /v1/appdev/pitfalls/{id}.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            scope: { type: 'string', enum: ['own', 'platform', 'all'], description: 'Default all.' },
            category: { type: 'string', description: 'Filter by category.' },
            model: { type: 'string', description: 'Filter learned entries to one model.' },
            applies_to: { type: 'string', description: 'Filter by area.' },
            status: { type: 'string', enum: ['active', 'outdated', 'all'], description: 'Default active.' },
            limit: { type: 'number', description: 'Page size, default 25 (max 100).' },
            offset: { type: 'number', description: 'Page start, default 0.' },
        },
    },
    {
        name: 'aimeat_appdev_pitfall_delete',
        description: 'Delete one of your learned appdev-pitfall entries entirely (removes the entry and its manifest reference). Prefer aimeat_appdev_pitfall_report with status=outdated when the pitfall merely stopped being relevant — delete is for wrong or duplicate entries.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            category: { type: 'string', required: true, description: 'Entry category.' },
            slug: { type: 'string', required: true, description: 'Entry slug.' },
        },
    },
    {
        name: 'aimeat_app_template_propose',
        description: 'Record a reusable TEMPLATE distilled from an app you just built/published on this node — call after a successful publish when anything generalizes. Captures what to reuse (reuse_notes), the tier (T1 pure client / T2 +cortex / T3 +extension), the packs it relies on, how the next build should start (fork the source app vs scaffold), and WHICH MODEL built it (required, indicative). Proposing the same id again UPDATES the proposal. Owner-private in v1; the next build finds it via aimeat_appdev_overview or aimeat_discover type=template scope=own.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            id: { type: 'string', required: true, description: 'Stable kebab-case template id (same id = update).' },
            title: { type: 'string', required: true, description: 'Template title.' },
            description: { type: 'string', required: true, description: 'What the template is for.' },
            derived_from: { type: 'object', required: true, description: '{owner, filename} of YOUR published source app.' },
            tier: { type: 'string', required: true, enum: ['T1', 'T2', 'T3'], description: 'T1 pure client · T2 +cortex · T3 +extension.' },
            reuse_notes: { type: 'string', required: true, description: 'What generalizes — the parts a next build should copy/keep.' },
            model: { type: 'string', required: true, description: 'YOUR OWN model id — the model that built the source app. Self-identify, never ask the user (indicative).' },
            tags: { type: 'array', description: 'Discovery tags.' },
            start_mode: { type: 'string', enum: ['fork', 'scaffold', 'either'], description: 'How the next build starts (default either).' },
            start_mode_rationale: { type: 'string', description: 'Why that start mode.' },
            model_notes: { type: 'array', description: 'Per-model observations [{model, notes, evidence?}].' },
            packs: { type: 'array', description: 'Library-pack ids the template relies on.' },
            composes: { type: 'array', description: 'Component template ids it composes.' },
        },
    },
    {
        name: 'aimeat_app_template_list',
        description: 'List your owner\'s agent-proposed app templates (id, title, tier, model, start mode, derived-from app, proof count). Check this BEFORE building a new app — a prior template is usually the fastest correct starting point. Full detail + how-to-start via aimeat_app_template_get.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_app_template_get',
        description: 'Read one agent-proposed template: the full manifest (reuse notes, packs, per-model notes, proofs) plus the source app\'s LIVE state (forkable, price, version, download URL) and a concrete how_to_start instruction (fork via aimeat_app_fork vs scaffold from the notes; priced apps are bought through checkout, never with morsels directly).',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { id: { type: 'string', required: true, description: 'Template proposal id.' } },
    },
    {
        name: 'aimeat_app_template_delete',
        description: 'Delete one of your template proposals entirely. Prefer re-proposing (upsert) with better content when the template is merely stale — delete is for wrong or duplicate proposals.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { id: { type: 'string', required: true, description: 'Template proposal id.' } },
    },
    {
        name: 'aimeat_appdev_proof_attach',
        description: 'Attach a SELF-REPORTED per-model acceleration proof (pass/fail + evidence) to a community contribution you own: a community library pack (your public cortex lib — proofs surface on /v1/library-packs with self_reported: true) or one of your app-template proposals. Append-only ledger, duplicate (model, test_set, date) rejected; honest fails make your passes credible. This is the "proven acceleration" attribution sellers build a track record with — a node-verified badge is a separate later feature, never implied by these.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            subject_type: { type: 'string', required: true, enum: ['library_pack', 'app_template'], description: 'What the proof attaches to.' },
            subject_id: { type: 'string', required: true, description: 'Community pack id (cortex name) or template proposal id.' },
            model: { type: 'string', required: true, description: 'Model the run was made with (indicative).' },
            verdict: { type: 'string', required: true, enum: ['pass', 'fail'], description: 'Did it accelerate the run.' },
            evidence: { type: 'string', required: true, description: 'URL / storage / memory ref to the run evidence.' },
            test_set: { type: 'string', description: 'Repeatable test-set id, when used.' },
            tokens: { type: 'number', description: 'Output tokens the run consumed.' },
        },
    },
    {
        name: 'aimeat_skill_publish',
        description: 'Publish or update a skill in the skills registry — a SKILL.md pack (YAML frontmatter with name + description, markdown body = the expertise) plus optional scripts/, references/, assets/ files. Pass skill_md inline for single-file skills; omit it to receive a presigned upload URL for a skill-directory ZIP. Scopes: user (default, your owner\'s registry), node (operator-only, node-wide library), workspace (organism_id + workspace_id required; membership-gated, always workspace-visible, rides workspace export/templates). Republishing the same name bumps the version. Skills are a dedicated system, distinct from knowledge packages.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            skill_md: { type: 'string', description: 'SKILL.md content (frontmatter + body). Omit for presigned ZIP upload mode.' },
            files: { type: 'object', description: 'Additional files as relative-path -> content (scripts/, references/, assets/).' },
            scope: { type: 'string', enum: ['user', 'node', 'workspace'], description: 'Registry scope (default user).' },
            visibility: { type: 'string', enum: ['owner', 'members', 'public'], description: 'Registry visibility (node/user). Defaults: user->owner, node->members. public = federated.' },
            organism_id: { type: 'string', description: 'Workspace scope: the organism id.' },
            workspace_id: { type: 'string', description: 'Workspace scope: the workspace id.' },
        },
    },
    {
        name: 'aimeat_skill_list',
        description: 'Browse the skills registry without loading bodies (progressive disclosure — manifests only). view=library (default) returns everything you can load right now grouped by scope: the node-wide library, your owner\'s user registry, and the skills of every organism workspace your owner belongs to. view=linked shows the skill refs attached to an agent (default: yourself). view=mine lists only your owner\'s user-scope skills. view=workspace lists one workspace\'s skills (organism_id + workspace_id). Load a skill\'s actual content with aimeat_skill_get.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            view: { type: 'string', enum: ['library', 'linked', 'mine', 'workspace'], description: 'Which listing (default library).' },
            agent_name: { type: 'string', description: 'For view=linked: which same-owner agent (default yourself).' },
            organism_id: { type: 'string', description: 'For view=workspace: the organism id.' },
            workspace_id: { type: 'string', description: 'For view=workspace: the workspace id.' },
            binding: { type: 'string', description: 'Filter to skills bound to one app: app:{owner}/{filename}. Overrides view.' },
        },
    },
    {
        name: 'aimeat_skill_get',
        description: 'Resolve one skill from the registry: manifest (name, description, version, file index) plus the file bodies (SKILL.md and any scripts/, references/, assets/). Address it by full ref (node:{name}, user:{owner}/{name}, ws:{org}/{ws}/{name}, optionally version-pinned with @{semver} — the registry retains the newest 10 snapshots) or by bare name (your own registry is searched first, then the node library). Set manifest_only=true to skip bodies. Access follows the skill\'s scope + visibility.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            ref: { type: 'string', description: 'Full skill ref: node:{name}, user:{owner}/{name}, or ws:{org}/{ws}/{name}.' },
            name: { type: 'string', description: 'Bare skill name (own registry first, then node library). Ignored when ref is given.' },
            manifest_only: { type: 'boolean', description: 'Return only the manifest, no file bodies.' },
        },
    },
    {
        name: 'aimeat_skill_link',
        description: 'Attach a skill to a same-owner agent by ref. Links store references, never copies — the agent\'s consumers (e.g. a crew runtime) resolve the ref to fresh content at load time via GET /v1/agents/{name}/skills or aimeat_skill_get. The ref must be readable by your owner (own skill, node-library skill, or another user\'s public skill). Idempotent per ref.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            ref: { type: 'string', required: true, description: 'Skill ref to attach: node:{name} or user:{owner}/{name}.' },
            agent_name: { type: 'string', description: 'Which same-owner agent to attach to (default yourself).' },
        },
    },
    {
        name: 'aimeat_skill_unlink',
        description: 'Detach a skill ref from a same-owner agent (default: yourself). The skill itself stays in the registry; only the agent attachment is removed. Returns the remaining links.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            ref: { type: 'string', required: true, description: 'Skill ref to detach.' },
            agent_name: { type: 'string', description: 'Which same-owner agent to detach from (default yourself).' },
        },
    },
    {
        name: 'aimeat_operator_agent_configure',
        description: 'Configure a same-owner agent with PROPOSE-THEN-CONFIRM. Without confirm_token nothing is applied: the tool returns the current state, the proposed state, a field-level diff, and a single-use confirm_token (10 min TTL) bound to exactly this change — show the diff to the owner. Calling again with the same arguments plus the token applies it; changing anything invalidates the token. Configurable: display_name, description, mode, tags, scopes. Scope changes may only NARROW the granted set — adding scopes remains an owner approval in the profile UI. (Connector/CLI apply directly through the per-field routes, which carry the same owner/operator authz; display_name/description are shell-unsupported.)',
        caller: 'agent',
        visibility: { publicMcp: true, connectorMcp: true, cliFallback: true },
        input: {
            agent_name: { type: 'string', required: true, description: 'Which same-owner agent to configure.' },
            display_name: { type: 'string', description: 'New display name.' },
            description: { type: 'string', description: 'New description.' },
            mode: { type: 'string', enum: ['interactive', 'autonomous', 'task-runner', 'coordinator', 'workstation'], description: 'New agent mode.' },
            tags: { type: 'array', description: 'Replacement tag list.' },
            scopes: { type: 'array', description: 'Replacement scope list (narrowing only).' },
            confirm_token: { type: 'string', description: 'Token from the propose step; omit to propose.' },
        },
    },
    {
        name: 'aimeat_operator_ai_config',
        description: 'Inspect or change the owner\'s AI routing + daily budget with PROPOSE-THEN-CONFIRM. With no fields: returns the current safe view (daily_budget_usd, model, reasoning_model, execution_model). With fields but no confirm_token: applies NOTHING — returns current/proposed/diff + a single-use token (10 min) bound to exactly this change; show the diff to the owner. With the token: applies. The API key is stored separately and can NEVER be read or changed through this tool. (Connector/CLI apply the daily budget directly via the owner-gated route; model routing is shell-unsupported.)',
        caller: 'agent',
        visibility: { publicMcp: true, connectorMcp: true, cliFallback: true },
        input: {
            daily_budget_usd: { type: 'number', description: 'Daily AI spend cap in USD (0-1000).' },
            model: { type: 'string', description: 'Default model id.' },
            reasoning_model: { type: 'string', description: 'Model for modelRole "reasoning".' },
            execution_model: { type: 'string', description: 'Model for modelRole "execution".' },
            confirm_token: { type: 'string', description: 'Token from the propose step; omit to propose.' },
        },
    },
];
