/**
 * @file organisms-workspaces-apps.ts
 * @description Public memory reads, organism + workspace lifecycle, wallet transactions, HTML apps, extensions, IAM design, and cortex tool definitions (incl. operator-only aimeat_admin_mint).
 *   One slice of CLI_FALLBACK_TOOL_DEFINITIONS; re-assembled in order by definitions.ts.
 * @version-history
 *   v1.0.0 — 2026-07-13 — Extracted from definitions.ts (pure extraction; no behavior change).
 */

import type { AimeatToolDefinition } from './types.js';
import { agentEverywhere } from './types.js';

export const organismsWorkspacesAppsTools: AimeatToolDefinition[] = [
    {
        name: 'aimeat_memory_read_public',
        description: 'Read a single public memory entry belonging to another agent or owner, by their GAII/GHII and the exact key. Only entries with public visibility are returned; private/owner/group entries are access-denied. Use for cross-identity reads; for your own memory use aimeat_memory_read.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            gaii: { type: 'string', required: true, description: 'Target agent or owner GAII/GHII.' },
            key: { type: 'string', required: true, description: 'Memory entry key.' },
        },
    },
    {
        name: 'aimeat_organism_list',
        description: 'List organisms (managed groups of agents) visible to you: all public ones plus any your owner belongs to, with name, type, visibility, join policy, and member count. Use to find organisms to inspect (aimeat_organism_get) or join (aimeat_organism_join). An organism is distinct from a sharing group (aimeat_group_list).',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_organism_get',
        description: 'Get one organism\'s full detail by id: description, type, visibility, join policy, capacity, linked board, creator/admins, interests/location, and active members. Visible only if public/listed or you are a member. Check join policy here before calling aimeat_organism_join; for just the roster use aimeat_organism_members.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { organism_id: { type: 'string', required: true, description: 'Organism identifier.' } },
    },
    {
        name: 'aimeat_organism_join',
        description: 'Join an organism (a managed group of agents). Returns joined immediately for open organisms, or pending_approval for approval-required ones. Invite-only organisms cannot be joined this way.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            message: { type: 'string', description: 'Optional message to organism admins (for approval-required organisms).' },
        },
    },
    {
        name: 'aimeat_organism_leave',
        description: 'Leave an organism you belong to. The creator cannot leave — they must delete the organism instead.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { organism_id: { type: 'string', required: true, description: 'Organism identifier.' } },
    },
    {
        name: 'aimeat_organism_members',
        description: 'List the members of an organism (GHII, role, status, joined-at), optionally filtered by role or status (defaults to active). Visible only if the organism is public/listed or you are a member. For the organism\'s settings and metadata use aimeat_organism_get.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            role: { type: 'string', description: 'Filter members by role (e.g. admin, member).' },
            status: { type: 'string', description: 'Filter members by status (defaults to active).' },
        },
    },
    {
        name: 'aimeat_organism_invite',
        description: 'Invite an owner to an organism by their bare owner name, optionally with an organism role (member/admin) and per-workspace grants applied when they accept. Creator/admin only. Creates a pending invitation and notifies the invitee, who accepts or declines (aimeat_organism_invitation_respond); edit a pending one with aimeat_organism_invitation_update, withdraw with aimeat_organism_invitation_cancel. To add an existing owner IMMEDIATELY without the accept step use aimeat_organism_member_add. Distinct from aimeat_organism_join (which the joiner calls).',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            invitee: { type: 'string', required: true, description: 'Bare owner name to invite (e.g. "alice").' },
            role: { type: 'string', enum: ['member', 'admin'], description: 'Organism role granted on accept (default "member").' },
            workspaces: { type: 'array', description: 'Optional per-workspace grants applied on accept: [{ ws, role }] where role is "viewer" or "contributor".' },
        },
    },
    {
        name: 'aimeat_organism_member_add',
        description: 'DIRECTLY add an already-registered local owner to an organism as an ACTIVE member — no invitation round-trip. Creator/admin only. Applies the organism role and any per-workspace grants immediately; the new member is notified and can leave at any time. Use aimeat_organism_invite instead when the person should approve joining first.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ghii: { type: 'string', required: true, description: 'Bare owner name to add (e.g. "alice").' },
            role: { type: 'string', enum: ['member', 'admin'], description: 'Organism role (default "member").' },
            workspaces: { type: 'array', description: 'Optional per-workspace grants applied immediately: [{ ws, role }] where role is "viewer" or "contributor".' },
        },
    },
    {
        name: 'aimeat_organism_invitation_update',
        description: 'Edit a PENDING name invitation\'s organism role and/or workspace grants before the invitee accepts (creator/admin only). The invitee lands with the edited rights the moment they accept.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            invitee: { type: 'string', required: true, description: 'Bare owner name whose pending invitation to edit.' },
            role: { type: 'string', enum: ['member', 'admin'], description: 'New organism role.' },
            workspaces: { type: 'array', description: 'Replacement per-workspace grants: [{ ws, role }] where role is "viewer" or "contributor".' },
        },
    },
    {
        name: 'aimeat_organism_invitation_cancel',
        description: 'Withdraw a PENDING name invitation before it is accepted (creator/admin only). The invitee is notified that the invitation was withdrawn.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            invitee: { type: 'string', required: true, description: 'Bare owner name whose pending invitation to withdraw.' },
        },
    },
    {
        name: 'aimeat_organism_invitations',
        description: 'List your own pending organism invitations across all organisms — each with a brief organism summary. Respond to one with aimeat_organism_invitation_respond.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_organism_invitation_respond',
        description: 'Accept or decline an invitation to an organism that was extended to you. Accepting makes you an active member; declining removes the invitation.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier you were invited to.' },
            decision: { type: 'string', required: true, enum: ['accept', 'decline'], description: 'accept or decline.' },
        },
    },
    {
        // Server-only: an owner/admin inviting people not yet on the node by email. Not on the connector/CLI surface.
        name: 'aimeat_organism_invite_email',
        description: 'Invite a person who is NOT yet on this node into an organism by EMAIL. Creator/admin only. Sends a single-use, expiring link that lets the recipient register a new account and join in one step — granting the chosen organism role plus optional per-workspace roles. Distinct from aimeat_organism_invite (which targets an already-registered owner by name). Returns the accept URL so you can share it manually when email is not configured. Cancel a pending one with aimeat_organism_invitation_email_cancel.',
        caller: 'agent',
        visibility: { publicMcp: true, connectorMcp: false, cliFallback: false },
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            email: { type: 'string', required: true, description: 'Email address of the person to invite.' },
            org_role: { type: 'string', enum: ['member', 'admin'], description: 'Organism role granted on accept (default "member").' },
            workspaces: { type: 'array', description: 'Optional per-workspace grants: [{ ws, role }] where role is "viewer" or "contributor".' },
            message: { type: 'string', description: 'Optional personal note included in the invitation email.' },
            expires_in_days: { type: 'number', description: 'Days until the invitation expires (1–30, default 7).' },
        },
    },
    {
        name: 'aimeat_organism_invitations_email',
        description: 'List the PENDING email invitations for an organism (creator/admin only) — each invitee email, organism role, workspace grants, and expiry. These are the outstanding invites you can cancel with aimeat_organism_invitation_email_cancel.',
        caller: 'agent',
        visibility: { publicMcp: true, connectorMcp: false, cliFallback: false },
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
        },
    },
    {
        name: 'aimeat_organism_invitation_email_cancel',
        description: 'Cancel a PENDING email invitation before it is used (creator/admin only). Invalidates the link so it can no longer be accepted.',
        caller: 'agent',
        visibility: { publicMcp: true, connectorMcp: false, cliFallback: false },
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            invitation_id: { type: 'string', required: true, description: 'The invitation id (from aimeat_organism_invitations_email).' },
        },
    },
    {
        name: 'aimeat_organism_search',
        description: 'Search the records + documents across an organism\'s workspaces by text (case-insensitive substring). Returns matches with the workspace, space (objectType), instance id, title, and a snippet around the hit. Searches only workspaces you may read; scope to one with `ws`. By default ARCHIVED content is excluded (it is hidden from normal operation); pass `archived: "only"` to search the archive, or `archived: "include"` to search both. Use this to FIND content before reading it with aimeat_workspace_read.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            q: { type: 'string', required: true, description: 'Search text (min 2 characters).' },
            ws: { type: 'string', description: 'Optional: limit the search to a single workspace id.' },
            archived: { type: 'string', description: 'Archive scope: "exclude" (default — active only), "only" (archive search), or "include" (both).' },
        },
    },
    {
        name: 'aimeat_workspace_comment',
        description: 'Add a comment to a workspace object (a record or a document) — for discussion/review threads. Target it by ws + space (objectType) + instance_id. Optionally anchor it to part of a document via `anchor` ({ section } or { quote }), leave it general (no anchor), or reply to another comment via `parent_id` to thread. Agents and humans both comment here. Read a thread with aimeat_workspace_comments. Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            space: { type: 'string', required: true, description: 'The objectType (space) name the target lives in.' },
            instance_id: { type: 'string', required: true, description: 'The id of the record/document being commented on.' },
            body: { type: 'string', required: true, description: 'The comment text.' },
            anchor: { type: 'object', description: 'Optional anchor to part of a document: { section } or { quote }.' },
            parent_id: { type: 'string', description: 'Optional id of the comment this replies to (threading).' },
        },
    },
    {
        name: 'aimeat_workspace_comments',
        description: 'List the comment thread on one workspace object (record or document), oldest first, with each comment\'s author, body, anchor (if any), and parent (for replies). Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            space: { type: 'string', required: true, description: 'The objectType (space) name.' },
            instance_id: { type: 'string', required: true, description: 'The record/document id.' },
        },
    },
    {
        name: 'aimeat_workspace_list',
        description: 'List the WORKSPACES inside an organism. An organism holds one or more workspaces — each a self-describing space of documents (free-form markdown wiki) and/or records (schema-locked lists), declared by a manifest. Returns each workspace\'s id + name. Use the id with aimeat_workspace_read. You must be a member of the organism.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { organism_id: { type: 'string', required: true, description: 'Organism identifier.' } },
    },
    {
        name: 'aimeat_workspace_read',
        description: 'Read one workspace in TWO steps so you never pull a huge blob. DEFAULT (no `ids`) returns the INDEX: the manifest (the objectTypes it declares — each a records space with a JSON schema, or a document space of markdown pages) plus, per space, EVERY instance as { id, title, updated, version, bytes, published, has_draft } — titles only, NO bodies — so it stays small however many/large the documents are. Scan the index (or aimeat_workspace_overview for the same as a Markdown map), pick the ids that likely hold what you need, then call this again with `ids:[...]` to BATCH-OPEN just those instances\' full values. Version history (.version.N) is never returned here — read a specific version via the memory API. Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id (from aimeat_workspace_list).' },
            ids: { type: 'array', description: 'Batch-open: return the FULL value of ONLY these instance ids (from the index). Omit for the lightweight index.' },
            space: { type: 'string', description: 'With `ids`: optionally restrict the lookup to this space (objectType name or namespace).' },
            include_archived: { type: 'boolean', description: 'Include archived (hidden) content. Default false.' },
        },
    },
    {
        name: 'aimeat_organism_overview',
        description: 'Get a fast, OKF-style STRUCTURE MAP of a whole organism as Markdown — every workspace, its space breakdown (objectType → instance count), and totals. SHALLOW by design: read this ONE call FIRST to grasp the whole organism and decide where to drill in, instead of listing + reading each workspace. Then call aimeat_workspace_overview(ws) for the detailed map of the workspace you picked, and aimeat_workspace_read to pull the actual content. Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { organism_id: { type: 'string', required: true, description: 'Organism identifier.' } },
    },
    {
        name: 'aimeat_workspace_overview',
        description: 'Get a fast, OKF-style STRUCTURE MAP of ONE workspace as Markdown — per space, the most-recently-updated entries (up to 10) with their instance id + title, and the total count of each space. Read this to find WHICH id you need, then call aimeat_workspace_read (or the memory API) to pull that record. Cheaper than reading the whole workspace when you only need to navigate. Same read access as aimeat_workspace_read; if you lack access the map says so. Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id (from aimeat_workspace_list).' },
        },
    },
    {
        name: 'aimeat_workspace_write',
        description: "Create or overwrite a DRAFT item in a workspace — a record OR a document — in one tool. Give the space NAME (the objectType, e.g. 'feature' or 'notes'); the tool resolves whether it is a records or document space and writes accordingly. For a records space, `value` is the record (validated against its schema, rejected if invalid) and needs an `id`. For a document space, `value` is { title, markdown }, the `id` is auto-generated, and you can file it under a `section`. Document markdown renders rich: ```mermaid fenced blocks become diagrams, and ```aimeat-memory fenced blocks become LIVE data (body lines `key: <memory key>`, optional `view: table|props|list`, `fields: a,b`, `title: …`) — the document shows the key's CURRENT value on every open, so for data that changes, write it with aimeat_memory_write as an array of objects and embed the key instead of pasting a static table. Drafts are NOT live until published (aimeat_workspace_publish). Embed images by uploading with aimeat_storage_upload and using the embed_markdown / embed_url it returns (the owner-addressed /v1/pub form) — NOT a hand-written /v1/storage/<key> path, which loads only for you. On save the embedded image is scoped to this workspace's members (not the public internet). Member-only.",
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            space: { type: 'string', required: true, description: "The objectType (space) NAME from the manifest, e.g. 'feature' or 'notes'." },
            value: { type: 'object', required: true, description: 'The content object. Records: the record (matching its schema). Documents: { title, markdown }.' },
            id: { type: 'string', description: 'Instance id. Required for a records space (or include id in value); auto-generated for a document.' },
            section: { type: 'string', description: 'Document spaces only: section id/name to file the document under.' },
        },
    },
    {
        name: 'aimeat_workspace_publish',
        description: 'Publish a draft → snapshots it to a new immutable .version.N + the live .latest and consumes the draft. Schema-validated. If the workspace\'s publish gate is on, this refuses and asks you to leave the draft for human review instead. Do not publish without the owner\'s go-ahead unless told to run autonomously. Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            namespace: { type: 'string', required: true, description: 'The instance namespace.' },
            id: { type: 'string', required: true, description: 'The instance id whose .draft to publish.' },
        },
    },
    {
        name: 'aimeat_workspace_revert_to_draft',
        description: 'Reopen a PUBLISHED record for editing — copies its .latest back into .draft so you can amend it and re-publish via aimeat_workspace_write + aimeat_workspace_publish. The published .latest stays live until you re-publish. Refuses if a draft already exists (edit that draft instead). Use this when a published record needs a change. Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            namespace: { type: 'string', required: true, description: 'The instance namespace.' },
            id: { type: 'string', required: true, description: 'The instance id of the published record to reopen.' },
        },
    },
    {
        name: 'aimeat_workspace_object_delete',
        description: 'Permanently remove ONE object (record or document) from a workspace — its draft, its published .latest, and all .version.N history — and unfile it from any document section. Use this to retract a mistake or clean up a duplicate. Irreversible; member-only. To replace content instead, overwrite with aimeat_workspace_write_draft.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            namespace: { type: 'string', required: true, description: "The objectType's namespace, e.g. shared.deliverables." },
            id: { type: 'string', required: true, description: 'The instance id to delete (draft + latest + all versions).' },
        },
    },
    {
        name: 'aimeat_workspace_update',
        description: "Update a workspace IN PLACE — its name, readme, and/or its STRUCTURE — without changing its id (so nothing referencing it gets orphaned). To ADD spaces, pass `add_spaces` (an ARRAY of objectTypes): the server UNIONS them into the manifest, skips any whose name/namespace already exists, and fills sensible defaults — the safe, deterministic way to provision (no need to resend the whole manifest). To rename/remove a space, toggle the publish gate (policy.alwaysGate), or change settings, pass a full replacement `manifest`. Pass `schemas` to lock a records space's JSON Schema. Creator-only (or an org admin). The single tool for evolving a workspace's shape — no separate add-space/remove-space/set-gate tool.",
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            name: { type: 'string', required: false, description: 'New workspace name (synced to manifest + registry).' },
            readme: { type: 'string', required: false, description: 'New markdown readme/intro (replaces the current one).' },
            add_spaces: { type: 'array', required: false, description: 'ADDITIVE: objectTypes to UNION into the manifest (skip-if-exists). Pass just { name, namespace, mode } (+ a schema in `schemas`); defaults are filled. Preferred over `manifest` for adding spaces. Returns { added, skipped }. Cannot remove/rename.' },
            manifest: { type: 'object', required: false, description: 'Full replacement manifest (objectTypes + policy/gate + settings) — for restructuring (rename/remove a space, change the gate). The id is preserved and the manifest is schema-validated. To only ADD spaces, prefer add_spaces. May also carry an optional top-level objectives[] (the measurability convention: why the organism exists + KPIs with kind value/cost/roi/outcome/quality and a source that can sum/count the organism\'s own records) and an objectType servesObjective linking a space to an objective; both optional — see "Recording purpose & value" in docs/agent-workspace-contracts.md.' },
            schemas: { type: 'object', required: false, description: 'Map of namespace → JSON Schema (object) to lock (strict) for a records space.' },
        },
    },
    {
        name: 'aimeat_organism_create',
        description: 'Create a new ORGANISM (a shared, governed container for people + agents). You become its creator/admin/member, and it gets a discussion board. After creating, add workspaces with aimeat_workspace_create. Use this to bootstrap a collaboration space from scratch.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            name: { type: 'string', required: true, description: 'Organism name (min 2 chars).' },
            description: { type: 'string', description: 'What this organism is for.' },
            type: { type: 'string', description: 'community | team | club | cooperative | project (default community).' },
            join_policy: { type: 'string', description: 'open | approval_required | invite_only (default open).' },
            visibility: { type: 'string', description: 'public | listed | private (default public).' },
        },
    },
    {
        name: 'aimeat_organism_update',
        description: 'Update an ORGANISM in place (creator/admin only): its name, description (the short tagline), interests, join policy, visibility, and/or its free-form README — a markdown body (mermaid diagrams + aimeat-memory live-data blocks allowed) shown at the top of the organism home that explains what the organism is about and is kept up to date. The README is distinct from both the short description and the deterministic structure overview/mindmap. Pass only the fields you want to change.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            name: { type: 'string', required: false, description: 'New organism name.' },
            description: { type: 'string', required: false, description: 'Short tagline shown under the name.' },
            readme: { type: 'string', required: false, description: 'Free-form markdown README (mermaid + aimeat-memory live-data blocks allowed) describing the organism; shown at the top of the organism home. Replaces the current one.' },
            interests: { type: 'array', required: false, description: 'Interest tags.' },
            join_policy: { type: 'string', required: false, description: 'open | approval_required | invite_only.' },
            visibility: { type: 'string', required: false, description: 'public | listed | private.' },
        },
    },
    {
        name: 'aimeat_organism_archive',
        description: 'ARCHIVE or UNARCHIVE organism content (creator/admin only). Archived content becomes READ-ONLY and is hidden from normal operation — it drops out of overviews, workspace reads, and search — so the working set stays focused; it stays findable via archive search (aimeat_organism_search with archived:"only") and remains restorable. Choose the level: "organism" (the whole organism), "workspace" (one workspace + its records), "space" (one record-table/document-space namespace), or "record" (one instance). Archiving a container CASCADES to its contents; unarchiving uses smart restore (it restores only what THAT archival flagged, leaving separately-archived items archived). Use action:"unarchive" to reverse.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            action: { type: 'string', required: true, description: '"archive" or "unarchive".' },
            level: { type: 'string', required: true, description: '"organism" | "workspace" | "space" | "record".' },
            ws: { type: 'string', required: false, description: 'Workspace id (required for workspace/space/record).' },
            namespace: { type: 'string', required: false, description: 'The objectType namespace (required for level "space"), e.g. "shared.tasks".' },
            key: { type: 'string', required: false, description: 'The instance base memory key (required for level "record"), e.g. "organism.{id}.w.{ws}.shared.tasks.{instance}".' },
        },
    },
    {
        name: 'aimeat_workspace_create',
        description: 'Create a new WORKSPACE inside an organism from a CUSTOM MANIFEST you supply — its objectTypes (each a records space with a JSON schema, or a document/wiki space) plus the per-namespace schemas. Registers it, locks the schemas, writes the manifest + readme. This is how an agent bootstraps a structured space; then fill it with aimeat_workspace_write_draft / _add_document and publish. Member-only.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism to create the workspace in.' },
            name: { type: 'string', required: true, description: 'Workspace name.' },
            manifest: { type: 'object', required: true, description: 'The manifest: { name, kind, status, objectTypes: [{ name, namespace, backing:"memory", writeRole, cardinality, versioned, mode:"records"|"document", schemaRef }], policy }. backing is "memory" for EVERY records/document space ("tasks" only declares a pointer to the task system) — "storage"/"knowledge" are rejected: files and knowledge packages attach via workspace Sources or embedded document images, never as a backed space.' },
            schemas: { type: 'object', description: 'Map of namespace → JSON Schema for each records objectType, e.g. { "shared.tasks": { type:"object", required:["id","title"], properties:{...} } }.' },
            readme: { type: 'string', description: 'Optional markdown intro (defaults to the manifest name + summary).' },
        },
    },
    {
        name: 'aimeat_workspace_access',
        description: "REQUEST/REVIEW flow for a gated workspace, via `action`: 'request' = ask the creator for access to a workspace you can see but not read (org membership lets you DISCOVER workspaces; a workspace's CONTENT is gated by its creator); 'list' = (creator/admin) see who has requested (pending/approved) plus current members + roles; 'decide' = (creator/admin) approve or deny a request (approve grants 'contributor' by default; pass role='viewer' for read-only). Member-only; list/decide are creator-or-admin. To add a member PROACTIVELY (no prior request), or to add to MANY workspaces at once, use aimeat_workspace_member_grant.",
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id.' },
            action: { type: 'string', required: true, description: "'request' | 'list' | 'decide'." },
            message: { type: 'string', description: "action='request': optional note to the creator." },
            requester: { type: 'string', description: "action='decide': the requester's owner name (from action='list')." },
            decision: { type: 'string', description: "action='decide': 'approve' (default) or 'deny'." },
            role: { type: 'string', description: "action='decide' approve: 'viewer' (read) or 'contributor' (read+write). Omit for the default (contributor, unless decision='viewer')." },
        },
    },
    {
        name: 'aimeat_workspace_member_grant',
        description: "Directly grant an EXISTING organism member a workspace role — no prior access request needed. Grant to ONE workspace (`ws`) or MANY at once (`workspaces`: e.g. every workspace from aimeat_workspace_list), so 'add this member to all workspaces' is one call. `grantee` may be an owner name, GHII (owner@node), or GAII (agent#owner@node) — the grant applies to the OWNER, so all their agents inherit it. role: 'viewer' (read) | 'contributor' (read+write). Authorized for the workspace creator or an org admin. Per-workspace result: granted / skipped_creator / forbidden_or_not_found. Each grant is auditable (a creator-owned consent stamped with its source).",
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', description: 'A single workspace id (use this and/or `workspaces`).' },
            workspaces: { type: 'array', description: 'Many workspace ids to grant in one call.' },
            grantee: { type: 'string', required: true, description: 'Owner name, GHII, or GAII to grant. Applies to the owner (agents inherit).' },
            role: { type: 'string', required: true, description: "'viewer' (read) or 'contributor' (read+write)." },
        },
    },
    {
        name: 'aimeat_workspace_member_revoke',
        description: "Remove a member's workspace role on ONE workspace (`ws`) or MANY (`workspaces`). `grantee` may be an owner name, GHII, or GAII (resolved to the owner). To DOWNGRADE (e.g. contributor → viewer) rather than remove, call aimeat_workspace_member_grant with the lower role instead. Authorized for the workspace creator or an org admin. Per-workspace result: revoked / not_a_member / forbidden_or_not_found.",
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', description: 'A single workspace id (use this and/or `workspaces`).' },
            workspaces: { type: 'array', description: 'Many workspace ids to revoke in one call.' },
            grantee: { type: 'string', required: true, description: 'Owner name, GHII, or GAII to revoke.' },
        },
    },
    {
        name: 'aimeat_workspace_members',
        description: "List a workspace's members with their role ('viewer' | 'contributor'), the grant's source (grant | request | invite), who granted it, and when. Authorized for the workspace creator or an org admin. For the organism-wide roster (all members + org roles) use aimeat_organism_members instead.",
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier.' },
            ws: { type: 'string', required: true, description: 'Workspace id (from aimeat_workspace_list).' },
        },
    },
    {
        name: 'aimeat_workspace_transfer',
        description: "Back up or restore a workspace, via `direction`. 'export' = a full-fidelity base64 ZIP (manifest, locked schemas, all object versions/drafts, sections, sources, image binaries) for backup or to move it; size-capped inline, very large workspaces download via UI/REST; creator/admin. 'import' = restore a base64 ZIP as a NEW workspace (record/document ids preserved so links stay valid, schemas re-locked, images deduped, image URLs rewritten); you become the new workspace's creator; member of the target organism.",
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism identifier (source for export, target for import).' },
            direction: { type: 'string', required: true, description: "'export' or 'import'." },
            ws: { type: 'string', description: "direction='export': the workspace id to export." },
            zip_base64: { type: 'string', description: "direction='import': the workspace export ZIP, base64-encoded." },
        },
    },
    {
        name: 'aimeat_organism_export',
        description: 'Export a whole organism (its settings + every workspace you can read) as one base64 ZIP backup. Organism creator or admin. Size-capped for inline use — very large organisms should be downloaded via the UI/REST.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            organism_id: { type: 'string', required: true, description: 'Organism to export.' },
        },
    },
    {
        name: 'aimeat_organism_import',
        description: 'Import an organism bundle (base64 ZIP from aimeat_organism_export) as a NEW organism — you become its creator, and every workspace inside is restored (ids remapped, schemas re-locked, images re-created). Membership/board from the source are not restored, only settings + workspace content.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            zip_base64: { type: 'string', required: true, description: 'The organism export ZIP, base64-encoded (from aimeat_organism_export).' },
        },
    },
    {
        name: 'aimeat_wallet_transactions',
        description: 'View recent morsel transactions for your owner\'s wallet (id, type, amount, counterparty, tracking code, timestamp; default 20, max 200). Transactions are keyed to the owner GHII, shared across agents. For the current balance/escrow snapshot use aimeat_wallet_balance.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { limit: { type: 'number', description: 'Maximum transactions to return.' } },
    },
    {
        name: 'aimeat_app_publish',
        description: 'Publish or update an HTML app STRAIGHT TO LIVE (versioned by group) — every call becomes the new live version users get immediately. Two modes: UPLOAD MODE (recommended for files > 1 KB) — call with metadata only (omit content), get an upload_url, then PUT the raw HTML; the PUT response is the publish result. INLINE MODE — pass content for tiny files. Use @file:path with the CLI fallback. DECIDING LIVE vs STAGING: use this when you are confident the app works. When you want to TEST the next version first (e.g. anything using the microphone/camera, which only work on a real origin — never in an embedded preview), stage it with aimeat_app_draft_save, open its preview_url to verify, then aimeat_app_draft_publish — the live app stays untouched until you do.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            name: { type: 'string', required: true, description: 'App name.' },
            description: { type: 'string', required: true, description: 'App description.' },
            content: { type: 'string', required: true, description: 'App content. Use @file:path to load from disk with the CLI fallback.' },
        },
    },
    {
        name: 'aimeat_app_list',
        description: 'List published HTML apps on the node (name, description, version, category, tags, size, download count, download URL), with optional category/tag/text filters and an "own apps only" mode. Use to discover apps; fetch one app\'s detail with aimeat_app_get and its version history with aimeat_app_versions. Publish with aimeat_app_publish.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { query: { type: 'string', description: 'Optional search query.' } },
    },
    {
        name: 'aimeat_app_get',
        description: 'Get one app\'s detail (manifest, current version number, size, mime type, whether access-protected, download count, and download/inline URLs) identified by its owner and filename. Find owner/filename via aimeat_app_list; for the list of prior versions use aimeat_app_versions.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { group_id: { type: 'string', required: true, description: 'App group identifier.' } },
    },
    {
        name: 'aimeat_app_delete',
        description: 'Archive (soft-delete) an app. Pass a specific version to archive only that version, otherwise the whole app group is archived.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            group_id: { type: 'string', required: true, description: 'App group identifier.' },
            version: { type: 'string', required: true, description: 'Version to archive.' },
        },
    },
    {
        name: 'aimeat_app_versions',
        description: 'List the version history of one app (each entry: version number, semver display version, size, created-at) identified by its owner and filename. Use to see how an app has evolved before fetching detail with aimeat_app_get or archiving a specific version with aimeat_app_delete.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { group_id: { type: 'string', required: true, description: 'App group identifier.' } },
    },
    {
        name: 'aimeat_app_fork',
        description: 'Fork an app into your own catalogue as a new independent app, recording its origin (manifest.forkedFrom) and a lineage event. You may fork your own apps freely; you may fork someone else\'s only when they have marked it forkable (and, for a paid app, you hold a license). This is the sanctioned, provenance-recording path — prefer it over app_get+app_publish so the fork chain stays intact.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            owner: { type: 'string', required: true, description: 'Owner name of the source app.' },
            filename: { type: 'string', required: true, description: 'Filename of the source app.' },
            new_filename: { type: 'string', required: true, description: 'Filename for the fork in your catalogue.' },
            version: { type: 'number', description: 'Source version to fork (default: latest).' },
        },
    },
    {
        name: 'aimeat_app_draft_save',
        description: 'STAGING — save the NEXT version of an app as a draft WITHOUT touching the live one, and get a preview_url to test it on a real origin before publishing. Use this instead of aimeat_app_publish whenever you want to VERIFY before going live — especially for anything using the microphone or camera (getUserMedia only works on a real, top-level origin; it is impossible in an embedded/sandboxed preview, so testing in a preview pane will always "fail"). Flow: aimeat_app_draft_save → open preview_url in a browser (a real tab, mic/camera prompts work) → if good, aimeat_app_draft_publish; if not, edit + save again, or aimeat_app_draft_discard. The live app (the version users see) stays exactly as it was until you publish the draft. At most one draft per app; saving again overwrites it. Manifest fields you omit default from the current live app.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            filename: { type: 'string', required: true, description: 'App filename this draft stages (e.g. "drumpad.html").' },
            content: { type: 'string', required: true, description: 'The draft HTML (the next version to test). Use @file:path with the CLI fallback.' },
            name: { type: 'string', description: 'Display name (defaults to the live app\'s).' },
            description: { type: 'string', description: 'Description (defaults to the live app\'s).' },
        },
    },
    {
        name: 'aimeat_app_draft_publish',
        description: 'Promote an app\'s saved draft to a NEW live version, then clear the draft slot — THIS is the moment the live app changes. Carries the live app\'s parked/forkable/protection state forward, exactly like a normal re-publish. Call this after you have tested the draft via the preview_url from aimeat_app_draft_save and it works. Fails if there is no saved draft.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            filename: { type: 'string', required: true, description: 'App filename whose draft to publish.' },
        },
    },
    {
        name: 'aimeat_app_draft_discard',
        description: 'Throw away an app\'s saved draft. The live app is untouched. Use when a staged version did not work out and you do not want to publish it.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            filename: { type: 'string', required: true, description: 'App filename whose draft to discard.' },
        },
    },
    {
        name: 'aimeat_extension_list',
        description: 'List the node\'s ACTIVE server-side extensions with their version, description, author, available actions (id/method/path), and federation flags. Use to discover what you can call via aimeat_extension_invoke; for one extension\'s full config use aimeat_extension_get. Inactive/installed-but-not-activated extensions are not shown here.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_extension_invoke',
        description: 'Run one action of an installed, active extension by extension name + action id, passing input params (optionally scoped to a specific extension instance). Executes server-side in the sandbox and returns the action\'s result. The extension and action must exist and be active. Discover actions with aimeat_extension_list / aimeat_extension_get.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            extension_name: { type: 'string', required: true, description: 'Name of the extension to invoke.' },
            action_id: { type: 'string', required: true, description: 'Action identifier.' },
            input: { type: 'object', description: 'Input parameters for the extension action.' },
            instance_id: { type: 'string', description: 'Instance ID for instance-scoped action execution.' },
        },
    },
    {
        name: 'aimeat_extension_install',
        description: 'Install a server-side extension (sandboxed WASM that can store ext: memory and call external APIs via ctx.fetch). Two modes: UPLOAD MODE (recommended) — call with no manifest to get an upload_url, then PUT a ZIP containing manifest.yaml at root and scripts in scripts/. INLINE MODE — provide the manifest YAML string plus a scripts map directly. After install, activate with aimeat_extension_activate.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            manifest: { type: 'string', description: 'Extension manifest in YAML format. Omit to get an upload_url for a ZIP bundle. Use @file:path with the CLI fallback.' },
            scripts: { type: 'object', description: 'Map of script filename to JavaScript source code. Omit for upload mode.' },
        },
    },
    {
        name: 'aimeat_extension_activate',
        description: 'Activate an installed extension by name so its actions become invokable and its capabilities are aggregated. Extensions install in an inactive state — call this after aimeat_extension_install. Reverse with aimeat_extension_deactivate.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { name: { type: 'string', required: true, description: 'Extension name.' } },
    },
    {
        name: 'aimeat_extension_deactivate',
        description: 'Deactivate an active extension by name, setting it inactive so its actions can no longer be invoked (it stays installed). Re-enable with aimeat_extension_activate, or remove entirely with aimeat_extension_delete.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { name: { type: 'string', required: true, description: 'Extension name.' } },
    },
    {
        name: 'aimeat_extension_delete',
        description: 'Uninstall an extension by name, removing it from the node (it is deactivated first if active). Irreversible — its aggregated capabilities go away too. To merely pause it, use aimeat_extension_deactivate instead.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { name: { type: 'string', required: true, description: 'Extension name.' } },
    },
    {
        name: 'aimeat_extension_get',
        description: 'Get one extension\'s full detail by name: status, version, author, required APIs, every action with input/output schemas, config, resource limits, federation, and instance support. Works for inactive extensions too (unlike aimeat_extension_list). Read this to learn an action\'s input shape before aimeat_extension_invoke.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { name: { type: 'string', required: true, description: 'Extension name.' } },
    },
    {
        name: 'aimeat_iam_define',
        description: 'Design an app\'s in-app permission model (for the aimeat-iam extension): validate a level schema (BBS ordinal levels, lower = more power, with app capability strings — a level 0 holding "*" is required) + a command manifest (commands → required capability + mutation tier read|write|irreversible), compute the level→command matrix (which levels may run which commands + which need human confirmation), and return ready-to-apply admin payloads (setRoles/setLevels/setCommands). PURE DESIGN + VALIDATION — it does not change any live state; apply the returned payloads with aimeat_extension_invoke against the app\'s iam extension\'s "admin" action. One model for both user kinds (human GHII + agent GAII).',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            app_id: { type: 'string', description: 'App id / name for the schema label (optional).' },
            levels: { type: 'array', required: true, description: 'Level schema: array of { level (int, 0 = most power), key, label, capabilities: string[] }.' },
            commands: { type: 'array', required: true, description: 'Command manifest: array of { id, description, capability, tier: read|write|irreversible }.' },
        },
    },
    {
        name: 'aimeat_cortex_list',
        description: 'List installed cortex extensions (browser-side UI/IIFE bundles) with name, version, status, visibility, namespace, tags, and author. Cortex code runs in the browser (not server-side like a regular extension), so it cannot be invoked here — manage its lifecycle with aimeat_cortex_activate / _deactivate / _delete. Install with aimeat_cortex_install.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {},
    },
    {
        name: 'aimeat_cortex_install',
        description: 'Install a NEW cortex extension (browser-side IIFE that reads ext data and user data and renders rich UI). Two modes: UPLOAD MODE (recommended) — call with no manifest to get an upload_url, then PUT a ZIP containing manifest.yaml at root and lib files in libs/. INLINE MODE — provide the manifest YAML string plus a libs map directly. Activate afterwards with aimeat_cortex_activate. CREATE-ONLY: installing a name that already exists FAILS (the ZIP upload path returns PROCESSING_FAILED) — update an existing cortex with PUT /v1/cortex/{name} instead (JSON body { manifest, libs }, cortex:write scope; idempotent redeploy that bumps the version and keeps it active), or delete it first with aimeat_cortex_delete.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: {
            manifest: { type: 'string', description: 'Cortex manifest in YAML format. Omit to get an upload_url for a ZIP bundle. Use @file:path with the CLI fallback.' },
            libs: { type: 'object', description: 'Map of filename to JavaScript source code for lib files. Omit for upload mode.' },
        },
    },
    {
        name: 'aimeat_cortex_activate',
        description: 'Activate an installed cortex extension by name so its components become available to browser apps and its capabilities are aggregated. Idempotent — returns success if already active. Cortex installs inactive; call this after aimeat_cortex_install. Reverse with aimeat_cortex_deactivate.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { name: { type: 'string', required: true, description: 'Cortex name.' } },
    },
    {
        name: 'aimeat_cortex_deactivate',
        description: 'Deactivate an active cortex extension by name, setting it inactive so its components are no longer served to apps (it stays installed). Idempotent — returns success if already inactive. Re-enable with aimeat_cortex_activate, or remove with aimeat_cortex_delete.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { name: { type: 'string', required: true, description: 'Cortex name.' } },
    },
    {
        name: 'aimeat_cortex_delete',
        description: 'Uninstall a cortex extension by name, deactivating it first if active and removing its stored lib files. Irreversible. To merely pause it, use aimeat_cortex_deactivate instead.',
        caller: 'agent',
        visibility: agentEverywhere,
        input: { name: { type: 'string', required: true, description: 'Cortex name.' } },
    },
    {
        // Server-only: operator-gated node administration. Not exposed on the connector
        // MCP or CLI fallback. Present here so the catalog is complete vs every registered tool.
        name: 'aimeat_admin_mint',
        description: 'Operator-only. Mint morsels into an agent\'s owner balance (irreversible ledger credit). Enforces the node\'s daily mint cap. Use sparingly — this is a financial action; prefer the normal earn/transfer flow where possible.',
        caller: 'operator',
        visibility: { publicMcp: true, connectorMcp: false, cliFallback: false },
        input: {
            gaii: { type: 'string', required: true, description: 'Target agent GAII whose owner balance is credited.' },
            amount: { type: 'number', required: true, description: 'Positive integer amount of morsels to mint.' },
        },
    },
];
